\c one_piece_dev;

INSERT INTO story_Saga ( name, mainArcs ) VALUES
('Sea of Survival: Super Rookies Saga', '{"http://localhost:3333/mainArcs/1", "http://localhost:3333/mainArcs/2", "http://localhost:3333/mainArcs/3", "http://localhost:3333/mainArcs/4", "http://localhost:3333/mainArcs/5", "http://localhost:3333/mainArcs/6"}'),

('The Final Sea: The New World Saga', '{"http://localhost:3333/mainArcs/7", "http://localhost:3333/mainArcs/8", "http://localhost:3333/mainArcs/9", "http://localhost:3333/mainArcs/10"}');

INSERT INTO main_arcs ( name, episode_start, epsiode_end, saga_id ) VALUES
('East Blue', 1, 61, 1),
('Arabasta', 62, 135, 1),
('Sky Island', 136, 206, 1),
('Water 7', 207, 325, 1),
('Thriller Bark', 326, 384, 1),
('Summit War', 385, 516, 1),
('Fish-Man Island', 517, 574, 2),
('Dressrosa', 575, 746, 2),
('Whole Cake Island', 747, 877, 2),
('Wano Country', 878, null, 2);

INSERT INTO sub_arcs ( name, episodes, filler, special, image, descr, main_arcs_id) VALUES
('Romance Dawn', '1 - 3', false, false, 'https://preview.redd.it/i-recreated-the-romance-dawn-cover-with-luffy-zoro-and-v0-l3dvhroiyie91.jpg?width=640&crop=smart&auto=webp&s=80abd9c7323d79867bebd0cddf533bd58d53f8ed', 'Influenced by Shanks, Luffy starts his journey to become the Pirate King. At the beginning of his journey, he meets a boy named Koby, who wants to become a Marine. They reach Shells Town, where they meet corrupt Marine captain Axe-Hand Morgan, his son Helmeppo, and the pirate hunter Roronoa Zoro.', 1),

('Orange Town', '4 - 8', false, false, 'https://mlirhajbvo9v.i.optimole.com/w:669/h:699/q:90/f:avif/https://oceananime.com/wp-content/uploads/2021/09/Orange_Town_Arc2.webp', 'Luffy and his first crew member Zoro arrive at Orange Town where they meet a thief named Nami, who hates pirates. The trio makes an unlikely team, fighting to free the town from the rule of Buggy the Clown.', 1),

('Syrup Village', '9 - 18', false, false, 'http://pm1.narvii.com/6789/62f21ba25456e7c9e5ea8aa5cc171b88c99fcc93v2_00.jpg','After Nami forms a partnership with the two as their navigator, the crew reaches Syrup Village and searches for a ship to use. There, they encounter a chronic liar named Usopp. When a devious plot is revealed, Usopp''s courage is put to the test as the Straw Hat Pirates prepare for a battle with the Black Cat Pirates.', 1),

('Baratie', '19 - 30', false, false, 'https://static.wikia.nocookie.net/onepiece/images/e/eb/Baratie_Infobox.png/revision/latest?cb=20191105160432', 'Usopp joins the crew as a sniper. In search of a cook for their ship, the Straw Hat Pirates go to a sea restaurant known as the Baratie. However, the restaurant is attacked by the powerful Don Krieg, who has returned from the Grand Line and wants to use the Baratie as a vessel to go back.', 1),

('Arlong Park', '31 - 44', false, false, 'http://4.bp.blogspot.com/-b0-GeqxCM3g/VgYmbow6NnI/AAAAAAAAAP8/i86dCKt2H3g/s1600/ussop_zoro_et_yosaku_arrive_a_arlong_park_by_fionadevil-d7ega83.jpg', 'With Sanji from the Baratie joining the crew and Nami stealing the ship, the Straw Hat Pirates follow her to an island under the control of the Fish-Man pirate Arlong. Nami reveals that she is a member of the Arlong Pirates and simply helped the Straw Hat Pirates so she could take their gold later. But why would she follow a man like Arlong?', 1),

('Loguetown', '45, 48 - 53', false, false, 'https://m.media-amazon.com/images/M/MV5BNzQyYjA2NjQtYjU2YS00NmI1LThiODYtMjc1ZTBmZjBkNjA1XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'After Nami officially joins, the crew heads to the last town before the entrance to the Grand Line, Loguetown, the place where Gold Roger was both born and executed. Not only will they have to deal with a powerful Marine captain, but also previous enemies looking for revenge.', 1),

('Buggy''s Crew Adventure Chronicles', '46- 47', false, false, 'https://simkl.net/episodes/46/4604518b2a18634a8_0.jpg', 'Follow Buggy as he finds himself on a wild adventure after losing several of his body parts in a fight with the Straw Hats. What plan is he concocting to get back at Luffy and the crew?', 1),

('Warship Island', '54 - 61', true, false, 'https://boutique-manga.fr/wp-content/uploads/2021/07/Arc-Ile-du-Navire-de-Guerre.png', 'This arc is the only filler arc in the East Blue Saga. It revolves around a girl named Apis who has escaped from Marine Branch 8. Wanting to protect her, they escort her and her old animal friend, Sennenryu, back to his home.', 1),

('Reverse Mountain', '62 - 63', false, false, 'https://www.opgt.it/wp-content/uploads/2018/07/reverse-mountain.jpg', 'The crew has entered the Grand Line, but they encounter an obstacle as soon as they get in: a giant whale that swallows the entire ship.', 2), 

('Whiskey Peak', '64 - 67', false, false, 'https://comicvine.gamespot.com/a/uploads/original/7/72480/5215502-wp.jpg', 'Led by the mysterious Mr. 9 and Ms. Wednesday, the Straw Hats go to Whisky Peak, where the townspeople immediately start a party to celebrate their arrival. But there is more to this town than there appears...', 2),

('Diary of Koby-Meppo', '68 - 69', false, false,'https://vignette.wikia.nocookie.net/onepiece/images/3/3b/Chapter_84_Colored.png/revision/latest?cb=20140302104248&format=original', 'We go back to Koby and Helmeppo who find themselves entangled when Morgan attempts to escape imprisonment. Their actions catch the attention of Vice Admiral Garp, who decides that they are destined for more than mopping up after their superiors. Can these two become real Marines?', 2),

('Little Garden', '70 - 77', false, false,'https://i.pinimg.com/originals/19/92/25/199225fa052e1eb41e23f6705edb9139.jpg', 'On their mission to bring Princess Vivi to Arabasta, the Straw Hats land at Little Garden, which is actually a huge island that is still stuck in the prehistoric era. However, there are more than dinosaurs on this island, as the crew soon finds out when they encounter two giants that have been locked in combat for over 100 years and four high-ranking Baroque Works members.', 2),

('Drum Island', '78 - 91', false, false, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJnkf6GYUqRqolmv6kUuiQT1bnW5Wsf68JgNuSCYmFM-wQafyV', 'When Nami catches a fatal illness, the crew is forced to stop at Drum Island, a kingless country that is trying to establish a new government. Due to the actions of the previous king, Wapol, there is only one doctor left—a "witch" named Kureha who lives at the top of a mountain. Luffy and Sanji must reach the peak, but the exiled King Wapol returns to reclaim his country.', 2),

('Arabasta', '92 - 130', false, false, 'https://cdnb.artstation.com/p/assets/images/images/011/088/779/large/ricard-rodas-alabastra.jpg?1527788190', 'The Straw Hats, with Kureha''s assistant Tony Tony Chopper, finally arrive at Arabasta, which is on the verge of civil war. Vivi must reach the rebels and tell them the real cause behind the conflict, but Crocodile, leader of Baroque Works and one of the Seven Warlords of the Sea, will not just stand by and watch. In the end, Baroque Works, marine forces, pirates, the royal guards, and the rebel army clash in a battle that will determine the fate of the country itself.', 2),

('Post-Arabasta', '131 - 135', true, false, 'https://m.media-amazon.com/images/M/MV5BYjg3M2Q5NGMtNGYzZC00MzhjLThhOGItOTE4ZGE1ZjEyNzlmXkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'The Alabasta Saga also only has one filler arc with five episodes dedicated to each: Zoro, Sanji, Nami, Usopp, and Chopper. Learn more about the history and goals of these characters before tackling the next big saga.', 3),

('Goat Island', '136 - 138', true, false, 'https://m.media-amazon.com/images/M/MV5BYWI5YThkNTUtOWM3Yi00NTRlLWI5ZDctOTQ2YTBjOGVhYjUyXkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'Goat Island is exactly what it sounds like. When Luffy and friends come across an uncharted island they find it inhabited by goats and an old man named Zenny. Why are there so many goats, Zenny?', 3),

('Ruluka Island', '139 - 143', true, false, 'https://boutique-manga.fr/wp-content/uploads/2021/07/Ruluka-Island-Arc.jpg', 'Ruluka Island is being run by a dictator who is hell-bent on building the Rainbow Tower. The crew soon find themselves lost in the Rainbow Mist, but what exactly could be waiting for them behind the veil?', 3),

('Jaya', ' 144 - 152', false, false, 'https://2img.net/h/opwiki.de/images/Jaya_400_Years.jpg', 'The crew tearfully leaves Vivi behind and continue on their journey with Ms. All Sunday, aka Nico Robin, joining as an archaeologist. When a ship inexplicably falls from the sky and the Log Pose begins pointing up, they go to the island of Jaya for information on "Sky Island". There, they encounter Bellamy, a pirate who is heralding a "New Age" where pirates do not dream, and a man named Mont Blanc Cricket.', 3),

('Skypiea', '153 - 195', false, false, 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQkguqR5FLq3GvKTuEf1ZWnhro7XfmCC1x4t9SRetqkpaqCtQI_', 'Riding the Knock Up Stream, the crew finds themselves in the "White Sea", an ocean in the sky. The Straw Hats soon discover that there is a war between the Sky People and the natives who originally inhabited a place known as the Upper Yard. They also learn of the cruel God Enel.', 3),

('G-8', '196 - 206', true, false, 'https://i.servimg.com/u/f68/15/08/91/65/navaro13.jpg', 'When the Straw Hats land slap bang in the middle of G-8, a Marine base, they are forced to abandon ship and separate as Marines are instantly on them. They have to trick the Marines and find a way to get back to the Going Merry before the Marines wise up to their tricks', 3),

('Long Ring Long Island', '207 - 219', false, false,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ2MQA2rM9tO7wCft1BEa9hgHQhv244GY_6gOlNfhaXLOi16FSc', 'The crew returns to the Blue Sea with gold and dials from Skypiea, only to encounter Foxy the Silver Fox, a pirate who challenges them to a "Davy Back Fight", a series of games where the winner takes crewmates from the loser crew. However, even after defeating Foxy, the Straw Hats encounter an enemy whom they have no hope of beating.', 4),

('Ocean''s Dream', '220 - 224', true, false, 'https://jleeson.files.wordpress.com/2008/01/one_piece_220-226.jpg', 'This arc is inspired by the PlayStation game One Piece: Ocean''s Dream! and focuses on the crew, barring Robin, losing their memories. Can Robin keep the crew together when they can''t remember each other and have reverted back to old habits?', 4),

('Foxy''s Return', '225 - 228', true, false, 'https://listfist.com/wp-content/uploads/one-piece-fillers.jpg?ezimgfmt=ng%3Awebp%2Fngcb1%2Frs%3Adevice%2Frscb1-1', 'Some members of Foxy Gang find themselves in a spot of trouble, lost at sea. The Straw Hats take pity on them and help them out. When Foxy reunites with his crew he finds out they have been taken over by the Fanged Toad Pirates. Can he win back captain rights with another game of Davy Back Fight? And what do the Straw Hats have to gain from these two rival crews battling it out?', 4),

('Water 7', '229 - 263', false, false, 'https://m.media-amazon.com/images/M/MV5BNmJkZWE3ZTQtYTNkNy00YTAwLTk5YzgtMDZiYTJkZmU0YjFkXkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_.jpg', 'In search of a shipwright to join the crew, the Straw Hats land at the thriving metropolis of Water 7. Here, the crew falls apart as two members leave. To make matters worse, the Straw Hats are framed for the attempted assassination of Water 7''s mayor, who is also president of the Galley-La shipbuilding company. They try to find the real culprit, but they soon learn that they may have been caught head over heels by the government assassination group CP9.', 4),

('Enies Lobby', '264 - 290, 293 - 302, 304 - 312', false, false, 'https://staticg.sportskeeda.com/editor/2022/09/247e6-16633972055558.png', 'The Straw Hats, the Franky Family, and the Galley-La Company team up to rescue Nico Robin, save Franky, and avenge Iceburg. To do this, they attack Enies Lobby, a government stronghold where CP9 is based, declaring war on the World Government.', 4),

('Boss Luffy Historical Special', '291 - 292, 303, 406 - 407', false, true, 'https://cdn.myanimelist.net/images/anime/9/21651l.jpg', 'The Boss Luffy Historical Special is a stand-alone anime-only special that began airing on December 18, 2005. It is set in an alternate universe, based on 19th century Japan, and uses many different One Piece characters to tell its story.', 4),

('Post-Enies Lobby', '313 - 325', false, false, 'https://qph.cf2.quoracdn.net/main-qimg-3b760823b1250507bd4191e23c281bce-pjlq', 'Resting after their ordeals on Enies Lobby, the Straw Hats'' world is turned upside-down as familiar faces return with unexpected revelations for the continuation of their journey. Down the Grand Line, Shanks makes his move to protect Whitebeard''s subordinate Ace from a familiar face with a horrific new power.', 4),

('Ice Hunter', '326 - 335', true, false, 'https://i0.wp.com/www.comicon.com/wp-content/uploads/2022/10/Ice_Hunter_Arc.png?w=1000&ssl=1', 'The Straw Hats travel through the Florian Triangle, which exhibits similar traits to the Bermuda Triangle. Ships are often found sailing without a crew and many who sail through are never heard from again. What is the secret behind this? Can the Straw Hats get to the bottom of it?', 5),

('Chopper Man Special', '336', false, true,'https://m.media-amazon.com/images/M/MV5BZjdjYWUwNjYtODhkNC00NGViLWFkYjItNDI0YzNjYWUxNGQ0XkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_.jpg', 'Chopper Man (チョッパーマン Choppāman?), alternatively spelled as Chopperman, is a One Piece spin-off franchise based around a character of the same name, who is a superhero counterpart of Tony Tony Chopper.', 5),

('Thriller Bark', '337 - 381', false, false, 'https://comicvine.gamespot.com/a/uploads/original/3/37144/7339059-4899957279-latest', 'The Straw Hats continue their adventure out into the Florian Triangle where they come across a strange barrel which upon opening, sets off a flare. This soon turns into a nightmare when a ghost ship directs them to the haunted island of Thriller Bark, where ghosts, zombies and Warlord of the Sea Gecko Moria await them.', 5),

('Spa Island', '382 - 384', true, false, 'https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/12/spa-island-arc.jpg?q=50&fit=crop&w=750&dpr=1.5', 'Foxy returns… again? What does he want this time?! The Straw Hats just want to relax and enjoy the attractions of Spa Island, but Foxy is up to no good so they are forced to fight. Meanwhile, what is Sayo hiding in her notebook? The curiosity gets the better of the crew and island owner, Doran, with everyone getting more knowledge than they bargained for!', 5),

('Sabaody Archipelago"', '385 - 405', false, false, 'http://1.bp.blogspot.com/-N4byHh1_EKw/VxcUGLI_e_I/AAAAAAAAA-A/X9_uUrhQBi4mXHa6RoFBxvoFBUcckdEgACK4B/s1600/Sabaody_Archipel.jpg', 'Arriving at the Red Line, the crew searches for a way to get to the famed Fish-Man Island. The Straw Hats are soon diverted from their search when a mermaid and a talking starfish appear, and they soon find themselves saving an old enemy from a kidnapping ring. Things take a turn for the worst when the Straw Hats find themselves cornered at every turn with a Warlord of the Sea, a Marine admiral, and World Government officials.', 6),

('Amazon Lily', '408 - 417', false, false, 'https://i.quotev.com/237mwlqwaaaa.jpg', 'Kuma sends each of the Straw Hat Pirates flying from the Sabaody Archipelago to different islands. This arc centers on Luffy, who lands on an island where only women live. Luffy soon discovers that the women on the island are led by Warlord of the Sea Boa Hancock.', 6), 

('Straw Hat''s Separation Serial', '418 - 421, 453 - 456', false, false, 'https://i.postimg.cc/VvhLxdP0/Collage-Maker-11-Sep-2022-04-23-PM.jpg', 'The Straw Hat''s Separation Serial is a set of Cover Stories ranging from the 11th to the 18th, created as a side story on the title pages of each One Piece chapter. It is divided into stories of each crew member of the Straw Hat Pirates apart from Luffy after the crew was separated at the Sabaody Archipelago by Bartholomew Kuma.', 6),

('Impel Down', '422- 425, 4430 - 452', false, false, 'https://voidcatcomics.com/wp-content/uploads/2021/09/Impel_Down.png', 'Winning over the heart of the beautiful Hancock, Luffy manages to storm the prison of Impel Down, hoping to save his brother Ace from execution before it sparks an ultimate showdown between the Whitebeard Pirates and the World Government.', 6),

('Little East Blue', '426 - 429', true, false, 'https://m.media-amazon.com/images/M/MV5BZjQ0OWY2NzItMWRiZC00MGE2LTk4NWMtZWQxMDViYzMwNTliXkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_.jpg', 'These four episodes tie into the movie, One Piece Film: Strong World. This introduces Shiki, the first prisoner to ever escape Impel Down, as he begins to set his own plans into motion.', 6),

('Marineford', '457 - 489', false, false, 'https://lh5.googleusercontent.com/edDGzsEujxAxNzFuY5tajZDMgXS9s9EnJnYW7JMMOCSH7LUeCOT13Ldsi1Otp4GnpTcjHdhf6ymAkbrM-yiRrVwl6TFOKKk6ttaZ-vCE_DgTIgZcO6xL92OcmaUPXnmv8przl2bRm4tOdJUpuWaAfVL8OZaUtwnM-gRxAKmLuLqPN2AuebactK9GUPnUnA', 'Unable to rescue Ace before he was transferred, Luffy and his group of prison escapees follow after him to Marineford. With time running out until Ace''s execution, the Whitebeard Pirates and the World Government prepare their forces to clash in a battle that could drastically change the era.', 6),

('Post-War', '457 - 489', false, false, 'https://pbs.twimg.com/media/E1wvYJdXsAA6RJb.jpg', 'The world reels from the death of Whitebeard, causing chaos to ripple all across the Grand Line. Luffy, struggling to cope with Ace''s death, remembers he has something just as important to him: his crew. Will the Straw Hat Pirates ever reunite?', 6), 

('Toriko Crossover Special', '492', false, true, 'https://m.media-amazon.com/images/M/MV5BM2M3ZWUzMDgtZTJhOS00YTI1LWFkODEtMDEwMDUxYWU0NzRlXkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_.jpg', 'After eating the Hungrila Bird that they captured, Luffy and Toriko team up again to save Nami and Komatsu who have been kidnapped by the Cocoalas.', 6),

('Return to Sabaody', '517 - 522', false, false, 'https://jonahwritesdotblog.files.wordpress.com/2022/02/return_to_sabaody_arc.png?w=766', 'Two years have passed since the crew was separated and the Straw Hats have trained vigorously since then. They are now set to reunite and pick up from where they left off on their journey.', 7),

('Fish-Man Island', '523 - 541, 543 - 574', false, false, 'https://external-preview.redd.it/AjR2AYVQvHMXSpNzsOFMdd-yCadN5jjoJmk5vAZ5v3Q.jpg?auto=webp&s=37c969e75515b006699c3445ab47a8244296b0c4', 'After two years, the Straw Hats are finally beginning their undersea journey to Fish-Man Island. When a local fortuneteller predicts Luffy destroying Fish-Man Island, the Straw Hats are falsely accused as criminals, and to complicate matters further, an alliance between Hody Jones and Vander Decken IX plots to take over the Ryugu Kingdom.', 7),

('Toriko Crossover Special', '542', false, true, 'https://cdn.animenewsnetwork.com/thumbnails/max400x400/cms/news/80088/screen-shot-2014-10-19-at-12.48.12-pm.png.jpg', 'Toriko and Komatsu are seen fishing when Komatsu catches a Harusame. After defeating it, Luffy suddenly comes out of the Harusame''s mouth and surprises Toriko and Komatsu. Soon, Sunny arrives and Chopper is revealed to be sick. In order to make him feel better, they have to find the "Seafood Fruit" and make Chopper eat it. Thus, Luffy, Toriko and the rest head off to To-Chuka Island.', 7),

('Z''s Ambition', '575 - 578', true, false, 'https://cdn.shopify.com/s/files/1/0318/2649/products/61aTiMfCYEL_b410d176-c7e4-403e-91d2-b8acf47b9bc3_720x.jpeg?v=1571440573', 'This arc leads into the movie One Piece Film: Z. The main antagonist of this arc, Shuzo, is a member of the Neo Marines. This team consists of former Marines who aim to kill all pirates, and they are the antagonists of the movie.', 8),

-- ( name, episodes, filler, special, image, main_arcs_id) VALUES
('Punk Hazard', '579 - 589, 591 - 625', false, false, 'hhttps://comicvine.gamespot.com/a/uploads/original/11125/111254686/5693768-5586607264-latest', 'After entering the New World, the Straw Hats are led to Punk Hazard by a distress call. There, they find a samurai in search of his son, run afoul of Smoker''s new Marine platoon, and join Trafalgar Law in a plot to take down one of the Four Emperors. As part of this plot, they are tasked with capturing Caesar Clown, the mad scientist who operates on the island and come to learn of his connections to the Underworld and its influential broker, Warlord of the Sea Donquixote Doflamingo.', 8),

('Toriko & Dragon Ball Crossover Special', '590',  false, true, 'https://www.themoviedb.org/t/p/original/iCK2cw43Zb4dppHvufJg0RXaVes.jpg', '"History''s Strongest Collaboration vs. Glutton of the Sea" is the 590th episode of the One Piece anime. It is a crossover between One Piece, Toriko, and Dragon Ball Z.', 8),

('Caesar Retrieval', '626 - 628', true, false, 'https://derf9v1xhwwx1.cloudfront.net/image/upload/oth/FunimationStoreFront/V1831993/artwork/701d081f-4a0f-408f-b781-ba25e632e89d_keyartofficialvideoimage.jpg', 'Scientist Caesar Clown is kidnapped away from the Straw Hats’ custody. The crew teams up with the Heart Pirates, led by Trafalgar Law, to get him back. He is vital to their plan to take down Donquixote Doflamingo, who treats Caesar as his right-hand man, and he has great knowledge of creating chemical weapons of mass destruction.', 8),

('Dressrosa', '629 - 746', false, false, 'https://cdn.myanimelist.net/s/common/uploaded_files/1447001557-e4aa85a6868f2ebd486d38e76b4242b8.jpeg', 'The Straw Hats, Law, Kin''emon, and Momonosuke head to Dressrosa with a captive Caesar to broker a deal with Doflamingo, destroy his SMILE Factory, and free the samurai''s comrade Kanjuro. They soon discover that both Doflamingo and Dressrosa are shrouded with many secrets, and Law''s conflict with Doflamingo quickly turns personal. Luffy works to obtain his late brother''s Devil Fruit while the other Straw Hats encounter sparks of rebellion among Dressrosa''s populace. The alliance''s efforts are further complicated as a new Marine admiral named Fujitora arrives to deal with them.', 8),

('Silver Mine', '747 - 750', true, false, 'https://m.media-amazon.com/images/M/MV5BZjJlYjY2ZjAtZDY1ZS00YmIyLTg1NWEtYzAzYzZmYWZlNGI0XkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'This arc ties into One Piece Film: Gold and sees Luffy and Bartolomeo being kidnapped by the Silver Pirate Alliance. They''re forced to fight their way back with the help of the all-female crew, the Sweet Pirates. It also introduces One Piece Film: Gold antagonist, Gild Tesoro, who teases the events of the movie.', 9),

('Zou', '751 - 779', false, false, 'https://lh6.googleusercontent.com/SGawGbHvf5cAdvi1S5DpeHv4xyUf9hK0xpTdWZNjUT10O-sVtPpzSYIqJ65ElrD_VK5nwf8aJQf_OX0xUjf7m2tY-EF_wUyiV1RglE0N1X8cDJ7zthlTZmuz5If3auUM2ViJfbBkz-0Aq--RpztSYENM-dFX-ewUsvjpvp2Yv73O5WZR79CFIJvW96Jfsw', 'The Straw Hats, Law, and the samurai head to Zou to reunite with the Straw Hats and Momonosuke who had left Dressrosa early. They meet the Mink Tribe natives and discover that Sanji is gone after getting entangled in a plot between his family and the Big Mom Pirates. They also learn how Jack of the Beasts Pirates attacked Zou earlier, and the samurai reveal just how much Kaidou is connected to them and to their home in Wano, leading to the formation of a new alliance. The Straw Hats then split up again to rescue Sanji and go to Wano.', 9),

('Marine Rookie', '780 - 782', true, false, 'https://cdn.animenewsnetwork.com/thumbnails/max550x550/cms/news/112991/marine-rookie-arc-kv.jpg', 'Sigh. Oh, Luffy. After eating all of the food, Sanji trespasses onto a marine base to steal more. The real question is, does a marine base really have enough food to last with Luffy around?', 9),

('Whole Cake Island', '783 - 877', false, false, 'https://lh5.googleusercontent.com/rH_6nLdYxKMMoqMu3zMdJ4vyjmpOeQ9gWqg3vWsHYlJ6q7Xho2cMUciWZN2vhXPdebq5RDERZUDK4-lCYXCaiv9XCDX3kD01HeiQqPogCHqivZwUzy7oc_QBTq55mgxMBpVzQstnagu70maPmf6_ukQ_lLivDjq4GSXaL18Dn6LqSIvxC1ZlMBF8gHrstA', 'Luffy''s group travels to Whole Cake Island to retrieve Sanji from a political marriage between the Vinsmoke Family and the Charlotte Family. They are caught between the families'' hidden agendas, and form an alliance with Jinbe, Caesar, and the Fire Tank Pirates to take down Big Mom and save the Vinsmokes.', 9),

('Levely', '878 - 889', false, false, 'https://www.opfanpage.com/wp-content/uploads/2020/11/Levely_Arc.png', 'The news of the Straw Hats exploits at Totto Land are reported to the world as the royalty from around the world gather at Mary Geoise for the Levely. Meanwhile, the Revolutionary Army prepares for their next move, and Big Mom talks to Kaidou about Luffy.', 10),

('Wano Country', '890 - 894, 897 - 906, 908 - 1028, 1031 - TBA', false, false, 'https://m.media-amazon.com/images/M/MV5BMjgwNzFjZGYtNTRhNC00YzA0LTliNmYtNTUyYjZiMWM1MDEwXkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', 'The Ninja-Pirate-Mink-Samurai Alliance gather in Wano Country and prepare for the battle against the Beasts Pirates. The history of Kozuki Oden and his ties to Wano Country, Whitebeard and Gol D. Roger are revealed, and the Alliance assaults Onigashima to take down the allied forces of Kaidou and Big Mom, all while alliances shift on all sides of the siege. Meanwhile, after the events during the recent Levely, the world goes through dramatic changes.', 10),

('Cidre''s Guild', '895 - 896', true, false, 'https://static.wikia.nocookie.net/onepiece/images/8/8f/Cidre_Guild_Arc_DVD.png/revision/latest?cb=20191230025953', 'The Cidre Guild Arc is the fourteenth filler arc and the fifth filler arc after the timeskip. It ties into the movie One Piece: Stampede. While going to buy cola for the Thousand Sunny, Luffy teams up with Boa Hancock to fight the bounty hunting Cidre Guild.', 10),

('Anime 20th Anniversary Special', '907', false, true, 'https://pics.filmaffinity.com/one_piece_romansu_don-902150410-large.jpg', 'This episode is a special adaptation of the second one-shot, Romance Dawn, first published in 1996, and follows the origins of Luffy''s pirate adventures.', 10),

('Uta''s Past', '1029 - 1030', true, false, 'https://www.comingsoon.net/wp-content/uploads/sites/3/2022/08/one-piece-ep-1030-luffy-uta.png', 'Uta''s Past is the fifteenth filler arc of the show and was aired recently. This arc directly ties together with the One Piece Film: Red. It is nice to see the addition of Uta, which ties in with Luffy''s past. But only Uta''s character is considered canon as of now and the events that took place haven''t been confirmed. So if you plan on watching the latest One Piece Red movie, this arc is a must-watch, or you can continue watching the raid on Onigashima.', 10);


