\c one_piece_dev;

INSERT INTO all_Characters ( name, alive, info, canon, pirate, marine, other, photo, devil_fruitID, pirate_groupID, marine_RanksID ) VALUES 

('AO', null , 'A O is an infamous New World pirate and captain of the A O Pirates. He and his crew were subordinates to Whitebeard. A O is a very tall man with a long, square shaped face, hollow eyes under prominent eyebrows, dark sideburns that go all the way down to his chin, and greenish long wavy hair. On his head, he wears a yellow and brown striped bandanna and over it is a tricorn captain''s hat with what appears to be his Jolly Roger on it, a white skull wearing an animal-like hood. He also wears a dark blue, open shirt with the sleeves rolled up and a ruffled collar, and elaborate earrings made up by three little jewels each on both ears. Not much is known about A O''s personality other than that he is very loyal to Whitebeard since he was willing to risk his own life to save Ace from execution instead of fleeing through the path he had cleared with his power. He was overjoyed when Luffy saved Ace, cheering with his fellow allies.',true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dd5k0rt-eb7d9729-7fff-40f3-bba0-22aa2c38f2b7.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGQ1azBydC1lYjdkOTcyOS03ZmZmLTQwZjMtYmJhMC0yMmFhMmMzOGYyYjcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.aYl4Dp4EM6p2fq_eq5cEEVp5-vz9AXevmGCN_IwK460', null, 36, null), 

('Abdullah', true, 'Abdullah is a criminal and a former bounty hunter who joined as a gladiator at the Corrida Colosseum to compete for the Mera Mera no Mi, along with his partner Jeet. He is an ally of Luffy during the Dressrosa Arc. After the battle with the Donquixote Pirates at Dressrosa, he joined the XXX Gym Martial Arts Alliance, which later converted to a pirate crew called the Ideo Pirates.',true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dfcr0aj-a0b93263-9eda-4bf3-9ce7-fee6ec56bf99.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGZjcjBhai1hMGI5MzI2My05ZWRhLTRiZjMtOWNlNy1mZWU2ZWM1NmJmOTkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.dvKjMRzwarOMqQYw9Ri2uGOJ9HClwBL0kYtQ0ufn4_g', null, 38, null),

('Absalom', false, 'Absalom of the Graveyard was the leader of the Zombie Soldiers and Zombie Generals of Thriller Bark prior to its collapse. He was one of the Mysterious Four of the Thriller Bark Pirates and one of the major antagonists of the Thriller Bark Saga. \n
Sometime during the timeskip, he became a reporter under the alias Absa. At some point, he was abducted by the Blackbeard Pirates and killed to poach his Devil Fruit powers, with his ability going to Shiryu.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd5zf-7bb00f5f-f563-41fa-a013-462b3cb79a94.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDV6Zi03YmIwMGY1Zi1mNTYzLTQxZmEtYTAxMy00NjJiM2NiNzlhOTQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.zQJe-JK9S1pk7SyfVwqpjIbLUP3z-8HgcTXPTn2hugw', 24, 9, null), 

('Acilia', true, 'Acilia is a gladiator at the Corrida Colosseum who participated in a tournament for the Mera Mera no Mi. She is a large and bulky woman. Has dark colored lipstick, and dark colored hair. She is seen with a jolly smile, and sports an armored helmet', true, false, false, 'gladiator', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de6g611-0b51a215-426f-4276-af1f-defc2f97c941.png/v1/fill/w_818,h_977,strp/acilia_by_hobbj_de6g611-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAzMiIsInBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU2ZzYxMS0wYjUxYTIxNS00MjZmLTQyNzYtYWYxZi1kZWZjMmY5N2M5NDEucG5nIiwid2lkdGgiOiI8PTg2NCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.Myv9LN1hhs13j8UX3Pt5p6EnG-r8oM2pqtExJ7fjyHs', null, null, null),

('Adele', true, 'Adele is a mermaid and an employee at the Mermaid Café. She is a youthful mermaid with beautiful curly hair that reaches past her shoulders, and has dark skin and pink lipstick. She wears a bikini top with a leopard skin pattern, and her tail is red in color with several zig-zag patterns all of which is being different hues of red themselves.', true, false, false, 'mermaid', null, null, null, null), 

('Aggie 68', true, 'Aggie 68 is a member of the Spade Pirates. Aggie 68''s abilities are unknown, but he and his crew were easily defeated by Newgate. He has been seen with a revolver-like gun attached to his wrist, but it is unknown how skilled he is in using it.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8105260c-cfc1-463e-b35b-5de2d500fac9/dei3ncs-7f75b0b3-b23a-4926-ab1c-ddd2fadc2f69.png/v1/fill/w_1280,h_1368,strp/aggie_68___spade_pirate_crew_by_caiquenadal_dei3ncs-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTM2OCIsInBhdGgiOiJcL2ZcLzgxMDUyNjBjLWNmYzEtNDYzZS1iMzViLTVkZTJkNTAwZmFjOVwvZGVpM25jcy03Zjc1YjBiMy1iMjNhLTQ5MjYtYWIxYy1kZGQyZmFkYzJmNjkucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.jQJZ-Gk9Jya7IX3yI5OGhqapZp1swzQWqhmxjVtgFTM', null, 60, null),

('Agotogi', true, 'Agotogi was the leader of a gang of bandits who tried to kidnap Vivi about 11 years before the princess''s return to Arabasta.', true, false, false, 'bandit', 'https://pbs.twimg.com/media/D9DqzWzXUAEV4LO?format=png&name=900x900', null, null, null),

('Agsilly', true, 'Agsilly is a New World pirate who allied himself with the Whitebeard Pirates. He seemed to be loyal to his alliance with the Whitebeard Pirates, willing to fight in the war at Marineford in order to rescue Ace from execution, but his full power has not yet been shown.', true, true, false, null, null, null, 48, null),

('Agyo', true, 'Agyo is a fighting lion and a gladiator competing at the Corrida Colosseum for the Mera Mera no Mi.', true, false, false, 'animal', null, null, null, null),

('Ahho Desunen IX', true, 'Ahho Desunen IX is a noble from the Goa Kingdom and the father of Ahho Zurako. Typical for a corrupted noble, Desunen is cruel and self-centered, as he believes that those who are not nobles are trash', true, false, false, 'noble', 'https://www.nautiljon.com/images/perso/00/63/ahho_desunen_ix_18336.webp', null, null, null),

('Ahho Zurako', true, 'Ahho Zurako is a noble from the Goa Kingdom and the daughter of Ahho Desunen IX. As a noble raised by a corrupted and spoiled parent, Zurako considers all people who are not nobles trash. She states that being burnt is their fault for not being born nobles.', true, false, false, 'noble', 'https://www.nautiljon.com/images/perso/00/43/ahho_zurako_18334.webp', null, null, null),

('Ahiru', true, 'Ahiru is the Deputy Commander of the East Army in the Revolutionary Army and the assistant of Belo Betty. Ahiru is a woman with tanned skin, prominent lips and long brown hair. Her left arm is a mechanical prosthesis with light and dark green (gray in the manga) coloring. She wears a black shirt, a red tie and a green jacket. She also has a pair of goggles on her head.', true, false, false, 'revolutionary', null, null, null, null),

('Aisa', true, 'Aisa is a young Shandia girl who used to sneak onto the Upper Yard frequently to collect Vearth. She is Isa''s daughter. Ever since she was born, she had the ability known as "Mantra". Because of this, she hates it when people die and will try anything to stop it, even rushing into danger without any plans on what to do. Aisa wants to be a strong fighter like everyone else and was originally afraid of Wyper, though she warmed up to him eventually. Aisa is also a bit of a tomboy as she reacted with disgust when Raki suggested she grow her hair longer because it would look cute on her.', true, false, false, 'shandorian', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de6sztl-eadafb80-daae-4cf6-a7d8-c7420b5a39e6.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU2c3p0bC1lYWRhZmI4MC1kYWFlLTRjZjYtYTdkOC1jNzQyMGI1YTM5ZTYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.h3MlxExZKRDBbKTqMEAG2j_a6I_Y2B_3JaCquT0laO0', null, null, null),

('Akehende', true, 'Akehende is a Marine Rear Admiral. Like many other Marines, he considers pirates as nuisances to be eliminated.', true, false, true, null, 'https://api.duniagames.co.id/api/content/upload/file/254093731591020258.jpg', null, null, 4),

('Akudai Kanzaburo', true, 'Akudai Kanzaburo is an arms dealer who lives in the Flower Capital of Wano Country. Kanzaburo''s skills as an arms dealer effectively earned him an invite to the shogun''s banquet.', true, false, false, 'wano civilian', null, null, null, 4),

('Akumai', true, 'Akumai was a Billions agent who followed Mr. 2 Bon Kurei everywhere before he was captured by Hina when Mr. 2 and his crew sacrificed themselves to save the Straw Hat Pirates. Not much of Akumai''s skills or power is ever shown. His only fights are unseen for the most part. His current fate is unknown.', true, false, false, 'billions agent', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de3oggp-3e0a96d3-16ee-46bc-81d5-90101ac6c603.png/v1/fill/w_473,h_925,strp/akumai_by_hobbj_de3oggp-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTI1IiwicGF0aCI6IlwvZlwvMWNlMTM3MmEtYjc1Yy00MDU4LWIwYzgtMWJmMWMyZDY4MzdlXC9kZTNvZ2dwLTNlMGE5NmQzLTE2ZWUtNDZiYy04MWQ1LTkwMTAxYWM2YzYwMy5wbmciLCJ3aWR0aCI6Ijw9NDczIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0._NhFLBouPNQOgEBsdSlwJ7MMBnxgoVPORn9UBr1KyCU', null, null, null), 

('Aladine', true, 'Aladine is a goatsbeard brotula merman. He was originally a Ryugu Kingdom soldier who was then enslaved, but then became a pirate as the doctor and later first mate of the Sun Pirates. He is the husband of Charlotte Praline, serving as the bond between the Sun Pirates and the Charlotte Family.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dfcr0aa-a4dc6048-5d67-44c0-98d6-f92adb1b3b5a.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGZjcjBhYS1hNGRjNjA0OC01ZDY3LTQ0YzAtOThkNi1mOTJhZGIxYjNiNWEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.S0xPPum64F_6R83_G6wbn-J0TqKNjBLaWDOX1Gjvdz0', null, 34, null),

 ('Albion', true, '"Gashed" Albion is one of the rookie pirates who joined the Fake Straw Hat Crew. He has a bounty of 92,000,000 beli''s. Not much is known about his abilities. He has at least four bladed weapons, so it might be assumed that he is a swordsman. He is seen holding three daggers between the fingers on his right hand and using them like claws, similar to Buggy''s knife-combat style. It can be assumed that he is rather strong since he was able to make it all the way to Sabaody Archipelago and almost became a Supernova. He was also able to escape Sentomaru''s platoon, when most of the other recruits were apprehended.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd71j-bcb30839-3226-4fb7-b429-940a32b18036.png/v1/fill/w_640,h_512,strp/albion_by_bodskih_dbcd71j-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kYmNkNzFqLWJjYjMwODM5LTMyMjYtNGZiNy1iNDI5LTk0MGEzMmIxODAzNi5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.RIIV-cZ9o5LSg1D76s4K_z89xDve99GGx5GHVlcZ5kA', null, 34, null),

('Ally', true, 'Ally is a little girl who was being held captive in the Biscuit Room, on Punk Hazard. She was freed with the rest of the children by the Straw Hat Pirates.', true, false, false, 'punk hazard child', 'https://cdn.anime-planet.com/characters/primary/ally-one-piece-1-190x285.jpg?t=1625995172', null, null, null), 

('Alpacaman', true, 'Alpacaman is a Gifter in the Beasts Pirates who serves as a guard in the Prisoner Mines of the Udon Region of Wano Country. He is shown using two sabers during his fight with Hyogoro and Luffy. He possesses some skill with them, and has a habit of spinning them around to show off and attack. He calls this style Alpaca Kenpo.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de8b8fu-d369a8d6-3a13-4edb-a66a-38b15d8f8fd5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU4YjhmdS1kMzY5YThkNi0zYTEzLTRlZGItYTY2YS0zOGIxNWQ4ZjhmZDUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.oJkmwTJB7rTh8GMUIw0dm-hTRLVnSBI8ZOsy8EPwayI', 131, 59, null),

('Alvida', true, '"Iron Mace" Alvida is the former captain of the Alvida Pirates and the first antagonist encountered by Luffy on his journey after going to sea. Due to her actions, she can be regarded as the secondary antagonist of the Romance Dawn Arc and the tertiary antagonist of the Loguetown Arc.
After her defeat against Luffy, she allies with Buggy and becomes one of the two captains of the Buggy and Alvida Alliance. She was the acting captain of the crew during Buggy''s time in Impel Down and during the Summit War of Marineford. After reuniting with Buggy, his army of Impel Down Convicts, and Galdino (and with the addition of Buggy becoming a Warlord of the Sea), her alliance with him has evolved into the Underworld Organization known as Buggy''s Delivery, and once again when that organization was re-integrated into the Organization known as Cross Guild.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd0sj-ce9bee5a-3024-4746-b3d9-99b59a2947d8.png/v1/fill/w_640,h_512,strp/iron_mace_alvida_of_buggy_pirates_by_bodskih_dbcd0sj-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kYmNkMHNqLWNlOWJlZTVhLTMwMjQtNDc0Ni1iM2Q5LTk5YjU5YTI5NDdkOC5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.4K_OW9M_FzdWc20w0iqfyQDWv3BwfVQLTtjQX_-EPYc', 3, 46, null),

('Amadob', true, 'Amadob is an infamous New World pirate who allied himself with Whitebeard. Amadob is a fearsome pirate who has managed to achieve an infamous reputation in the New World, and to make an alliance with Whitebeard. It is still unknown what abilities and weapons he possesses.', true, true, false, null, 'https://api.duniagames.co.id/api/content/upload/file/1080107921586254254.jpg', 3, 48, null),

('Amazon', true, 'Amazon was the elderly gatekeeper of Skypiea and informer at the entrance to Skypiea known as Heaven''s Gate. She let people in even if they could not pay her extol toll, but purposely failed to tell those who did not pay about the consequences for entering the city.
After the timeskip, she became the admission ticket saleswoman for Skypiea''s new theme park, Wagomuland.', true, false, false, 'shandorian', 'https://pbs.twimg.com/media/EBHdtbJX4AAYJLH?format=jpg&name=small', 3, 48, null),

('An Zengaiina', true, 'An Zengaiina is a prisoner on Level 2 of Impel Down. Not much is known about Zengaiina''s abilities, however he is dangerous enough to be imprisoned in the great prison although only on the second least secure level.', true, false, false, 'prisoner', null, 3, 48, null),

('Andre', true, 'Andre is an infamous New World pirate captain who was once a member of the Whitebeard Pirates, before forming his own crew subordinate to Whitebeard. He is the twin brother of the Marine officer Candre. ', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de3b0wq-1f3a0095-09f2-498e-8140-3bfda5845016.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGUzYjB3cS0xZjNhMDA5NS0wOWYyLTQ5OGUtODE0MC0zYmZkYTU4NDUwMTYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.dbazRRzH73ZY3rLSadzIzxftJ2s3ndoZ7C2717m-eSU', 3, 48, null),

('Anjo', true, 'Anjo is a pirate admirer. He witnessed Gol D. Roger''s execution. He has a tattoo of a plain Jolly Roger on his right arm.', true, false, false, 'civilian', null, null, null, null),

('Ankoro', true, 'Ankoro is a gigantic anglerfish formerly under the command of captain Vander Decken IX, residing in the Underworld of the Sea, seven thousand meters underneath the ocean surface. Wadatsumi seems to regard Ankoro as a pet, as apparently Ankoro was told "not to eat ships" before.', true, false, false, 'animal', null, null, null, null),

('Antonio', true, 'Antonio is the owner of "Antonio''s Graman" in Sabaody Archipelago. Chopper, Luffy, and Brook "sampled" multiple boxes of his food, causing him to ask if they would actually buy anything. However, they ended up buying a number of boxes along with some souvenirs.', true, false, false, 'sabaody civilian', 'https://cdn.anime-planet.com/characters/primary/antonio-one-piece-1-190x266.jpg?t=1626018973', null, null, null),

('Aphelandra', true, 'Aphelandra is a member of the tribe of Kuja living on the island of Amazon Lily. Despite her size, she has shown to be rather timid, often repeating what others have said to her as she obeys their command. She is a kind and innocent woman. Aphelandra is most likely a melee-type fighter where her prodigious size affords her a tremendous advantage over many foes. During the timeskip, she became a member of the Kuja Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd2pf-57b053a5-1aab-45a3-9166-4c97b70aa0e9.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDJwZi01N2IwNTNhNS0xYWFiLTQ1YTMtOTE2Ni00Yzk3YjcwYWEwZTkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.SS130t4KZi3_PcJCd0bYt3bpdl7St-iMNjgykw6xTDo', null, 44, null),

('Aramaki', true, 'Aramaki, better known by his alias Ryokugyu, is an admiral in the Marines. He attained his rank during the two-year timeskip, along with Fujitora, both filling the two admiral vacancies left by Kuzan, who had resigned from the Marines, and Sakazuki, who had been promoted to fleet admiral.
Ryokugyu was first mentioned by Donquixote Doflamingo in the Dressrosa Arc, and debuted in the Levely Arc. His full appearance and real name were revealed near the end of the Wano Country Arc, in which he serves as a supporting antagonist.', true, false, true, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b574e24b-607c-4a4d-b81d-40f05cf97d11/df7fbcg-4d9c04d6-5026-4ae4-b0a1-ed243f31c8ac.png/v1/fill/w_1024,h_1449,strp/aramaki_ryokugyu___green_bull_by_robirh_df7fbcg-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTQ0OSIsInBhdGgiOiJcL2ZcL2I1NzRlMjRiLTYwN2MtNGE0ZC1iODFkLTQwZjA1Y2Y5N2QxMVwvZGY3ZmJjZy00ZDljMDRkNi01MDI2LTRhZTQtYjBhMS1lZDI0M2YzMWM4YWMucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.nyRplfl_0cUfW-gHSGaSG6FFafSP8Piac29UPzFUBOY', 173, null, 2),

('Aremo Ganmi', true, 'Aremo Ganmi is a spectator at the Corrida Colosseum. She lives in Primula, a town in the west of Dressrosa.', true, false, false, 'dressrosa civilian', null, null, null, null),

('Arlong', true, 'Arlong the Saw is a sawshark fish-man. He was the captain of the all fish-man crew (excluding Nami), the Arlong Pirates, a former member of the Sun Pirates, and the older half-brother of Madam Shyarly. He is also a major inspirational figure for the New Fish-Man Pirates.
Following the death of his former captain, Fisher Tiger, Arlong was captured and sent to Impel Down, but received a pardon thanks to his comrade Jinbe becoming one of the Seven Warlords of the Sea. Once freed, Arlong set his sights on conquering the East Blue, settling himself on the Conomi Islands alongside his crew and racketeering the local population. He is also the man responsible for killing Bell-mère, Nami and Nojiko''s foster mother. Arlong then had Nami become his subordinate, taking advantage of her cartography skills to one day conquer all of the Blue Sea. He had the highest bounty in the East Blue before being defeated by Monkey D. Luffy. Due to his actions and role, he is the primary antagonist of the Arlong Park Arc.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dcv4cel-1b19d3e1-3b83-47f8-b521-36979b814a2e.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN2NGNlbC0xYjE5ZDNlMS0zYjgzLTQ3ZjgtYjUyMS0zNjk3OWI4MTRhMmUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.9l_PjS2Rouu920tZAe5aVtB02nchgsjrRKHFGz9zqCU', null, 56, null),

('Arrow', false, 'He is tall and thin, with a pointed chin, with face paint around his eyes and around his jawline. He also wears shabby pants. He wields a double-edged sword with a golden hilt. Arrow is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', null, null, null, null),

('Brahm', false, 'He is tall, with a hunchbacked appearance. He wears a turban and has light brown hair that covers his eyes. He wields two pole-arms. Brahm is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', null, null, null, null),

('Barrel', false, 'He is bulky and rotund, and has a prominent nose, wearing thick white ropes around his shoulders, and has face paint around and under his eyes. He wields a large axe with a handle that is reminiscent of a flute. Barrel is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', null, null, null, null),

('Hyota', false, 'He is very muscular, with a very large stubble-covered chin and a bulbous nose. He wields an extra large sword that resembles a butcher-knife. He is the leader of the group, under Chaka. Hyota is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death.', true, false, false, 'alabastian', null, null, null, null),

('Aruyutayan V', false, 'Aruyutayan V was the king of Lvneel Kingdom roughly 400 years ago when Mont Blanc Noland discovered Shandora. Aruyutayan was a greedy and selfish king who was not above making rash decisions if it resulted in personal gains. He was ignorant to the challenges of seafaring, refusing to bring along Noland''s experienced crew in favor of his kingdom''s army, who otherwise had little experience at sea. Aruyutayan was also seemingly unfazed by losing most of his soldiers on the voyage, being driven primarily by his materialistic desires for Shandora.\n
When he was denied the city he so much craved for, Aruyutayan was quick to think Noland had tricked him in spite of the latter''s credibility as a hero and famous explorer. A major egocentric, Aruyutayan did not tolerate being made a fool of, using his authority as a royal to order not only Noland''s execution, but also to carry out a post-mortem smear campaign that would lead to Noland''s legacy being twisted into that of a goofy liar. Aruyutayan went as far as planting a fake witness to trick his subjects into despising the otherwise beloved Noland.', true, false, false, 'king', null, null, null, null),

('Asahija', true, 'Asahija is a Marine Chief Petty Officer whose shadow was once stolen by Gecko Moria.', true, false, true, null, null, null, null, 14),

('Asashichi', true, 'Asashichi is a resident of the Flower Capital who ran a soba shop with his wife. Asashichi cares deeply for his restaurant, as he was distraught when Page One destroyed it. He was angry at Sangoro for not intervening before his shop was destroyed.', true, false, false, 'wano civilian', null, null, null, null),

('Ashura Doji', false, 'Ashura Doji was a former bandit, a samurai from Wano Country and a retainer of the Kozuki Family, serving as one of Kozuki Oden''s Nine Red Scabbards. After Oden''s death, he returned to being a criminal under the name Shutenmaru, assuming leadership of the Mt. Atama Thieves. He initially severed his ties with the Kozuki Family in the present but rejoined after witnessing Yasuie''s death. \n
Ashura eventually met his demise during the Raid on Onigashima, sacrificing himself to protect his fellow Scabbards from one of Kanjuro''s schemes.', true, false, false, 'samurai', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/ddqmght-4b1c2daf-64ee-4239-ba5d-551dad06313a.png/v1/fill/w_640,h_512,strp/ashura_doji_aka_shutenmaru_by_bodskih_ddqmght-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kZHFtZ2h0LTRiMWMyZGFmLTY0ZWUtNDIzOS1iYTVkLTU1MWRhZDA2MzEzYS5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.0BNEhM303wXP9ECB15S6nsTf2uPG1vVuyX6glwL7TBY', null, null, null),

('Aswa', null, 'Aswa is Koza''s mother and Toto''s wife.', true, false, false, 'alabastian', null, null, null, null),

('Atagoyama', true, 'Atagoyama is a sumo wrestler in Wano Country''s Bakura Town.', true, false, false, 'sumo wrestler', null, null, null, null),

('Atlas', true, 'Atlas, also designated as Punk-05, is one of the six satellites of Dr. Vegapunk, embodying his aspect of "violence". Being designated the “violence” satellite of Vegapunk, Atlas has a short temper and is prone to violence upon getting angry, which has been shown to occur if someone attacks her or if people show an inability to utilize her inventions successfully. She is very talkative and will gladly give detailed explanations on the inner workings of her inventions. She is quite interested in the question of the definition of reality, and though she has a firm view on the matter, she thinks other people need to decide the answer for themselves.', true, false, false, 'vegapunk', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/512bfbe4-1969-4c9a-9a06-ef57ffafe2e0/dflrmvo-ca9582d5-600d-4322-8506-261b3ee121bb.png/v1/fill/w_902,h_886,q_70,strp/vegapunk_satellites___atlas__by_corasaan_dflrmvo-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI1OCIsInBhdGgiOiJcL2ZcLzUxMmJmYmU0LTE5NjktNGM5YS05YTA2LWVmNTdmZmFmZTJlMFwvZGZscm12by1jYTk1ODJkNS02MDBkLTQzMjItODUwNi0yNjFiM2VlMTIxYmIucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.Ck5tiBFwep7xO_NFHEUx_EW-nu2s5FWsQusjAeEmOV8', null, null, null),

('Atmos', true, '"Water Buffalo" Atmos is the commander of the 13th division of the Whitebeard Pirates. Atmos carries around two large swords and can deal devastating blows with them, as seen when he attacked and destroyed the swords of some of his crewmates while Doflamingo controlled him. In the anime, he could even block bullets that were shot from rifles to protect his allies.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbo8ktn-2493f5e3-3bb4-412d-847d-014d71689236.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJvOGt0bi0yNDkzZjVlMy0zYmI0LTQxMmQtODQ3ZC0wMTRkNzE2ODkyMzYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.c_zKMPkeCY2i9TYWrAeLdbhZlXWNFt00EadQz7i6Te4', null, 48, null),

('Attach', true, 'Attach, commonly nicknamed Attachan, is a prolific photographer who once headed the Marines'' Photography Department. Though he supplied images of many prominent outlaws - including most of the Straw Hat Pirates - for the Marines'' wanted posters, his frequent blunders eventually led to his dismissal. Subsequently, he became a reporter for the World Economic Journal, under "Big News" Morgans.
Like Minatomo, Attach began as an SBS joke Eiichiro Oda used to "explain" a triviality - namely, how the Marines always had such high-quality illustrations of the world''s most dangerous and/or unreachable criminals. In time, however, he became a fully canon character, with minor but tangible impact on the story.', true, false, false, 'reporter', null, null, null, null),

('Avalo Pizarro', true, 'Avalo Pizarro, also known as the "Corrupt King", is one of the Ten Titanic Captains, and the captain of the Fourth Ship of the Blackbeard Pirates. He was one of the criminals who was given a life sentence in Level 6 of Impel Down, as his crimes were so atrocious he had to be effectively be erased from history. Prior to his life of crime, he was once a king of a North Blue kingdom that overthrew him for his despotic ways. He has since been freed by Marshall D. Teach and has become a member of the Blackbeard Pirates.
He is currently one of the Ten Titanic Captains, and the captain of the Fourth Ship of the Blackbeard Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dehdf0z-702052ee-be96-4344-83eb-9b7ba4928e18.png/v1/fill/w_640,h_512,strp/avalo_pizarro_of_blackbeard_pirates_by_bodskih_dehdf0z-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kZWhkZjB6LTcwMjA1MmVlLWJlOTYtNDM0NC04M2ViLTliN2JhNDkyOGUxOC5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.Ob-F96NqDG3kcdWEII1-9kWcK93ADRXPAUMyPEw5cUY', null, 30, null),

('Azuki', true, 'Azuki is an old woman who lives in Ebisu Town.', true, false, false, 'wano civilian', null, null, null, null),

('Arthur', true, 'Arthur is an infamous New World pirate captain who was subordinate to Whitebeard. During the Summit War of Marineford, Arthur was seen wielding a sword. Although he has not been seen wielding it in direct combat, it can be presumed that his swordsmanship is befitting of his reputation as an infamous pirate captain.', true, true, false, null, null, null, 48, null),

('Babanuki', true, 'Babanuki is a Shinuchi of the Beasts Pirates who serves as the warden of the Prisoner Mine in Udon, a region of Wano Country. Babanuki ate an Elephant SMILE, which caused an elephant''s head to grow out of his chest. Unlike some other SMILE users, Babanuki appears to have full control over his elephant head, having been seen speaking through it. However, it can still act independently at times. The elephant head is capable of unleashing powerful explosive blasts of air out of its trunk.However, the trunk can be tied, which prevents the sneeze from being discharged; it will backfire on Babanuki, causing him grievous injuries. 
After the prison takeover, Babanuki was tamed by Tama.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e3326937-ab01-4757-a35a-a4d4e20a1987/decute3-682d3d42-de27-4184-b4b6-78e5dffc7269.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2UzMzI2OTM3LWFiMDEtNDc1Ny1hMzVhLWE0ZDRlMjBhMTk4N1wvZGVjdXRlMy02ODJkM2Q0Mi1kZTI3LTQxODQtYjRiNi03OGU1ZGZmYzcyNjkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.NaGWzjc7BYuE_N3nNyMCX90ok2Nv2WAe-4AORvoJjls', 131, 59, null),

('Babe', true, '"Catcher-Killing" Babe, better known by his alias Mr. 4, is a former officer agent of the Baroque Works and partner of Miss Merry Christmas. He is also Lassoo''s owner. \n
He was a major antagonist during the Arabasta Arc. He is one of two officer agents without a Devil Fruit ability, the other being Miss Goldenweek. He is tremendously strong, able to wield a baseball bat that weighs 4-tons with no effort and his bat swings can destroy bricks from long distances from the shockwaves alone.', true, true, false, 'baroque works', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ce1a7276-ef29-4188-8b5e-e50c6151ee00/df9wr9b-d240c1c3-53ee-4216-812b-c314794557c1.png/v1/fill/w_800,h_1231,strp/babe__mr_4___original__by_monkeyoflife_df9wr9b-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTIzMSIsInBhdGgiOiJcL2ZcL2NlMWE3Mjc2LWVmMjktNDE4OC04YjVlLWU1MGM2MTUxZWUwMFwvZGY5d3I5Yi1kMjQwYzFjMy01M2VlLTQyMTYtODEyYi1jMzE0Nzk0NTU3YzEucG5nIiwid2lkdGgiOiI8PTgwMCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.7gjzKvaXzzk3tStOicnReoEcCcfXpWbI_L-avoK-1Zk', null, null, null),

('Baby 5', true, 'Baby 5 is a pirate and the wife of Sai, the Happo Navy''s 13th leader. She is a former servant and assassin of the Donquixote Pirates, serving as an officer in the Pica Army. Her real name has not been revealed, as "Baby 5" is a codename given to her upon joining the Donquixote Pirates.
Due to her actions, she is a minor antagonist during the Punk Hazard Arc, and a supporting antagonist during the Dressrosa Arc, before becoming an ally of the Straw Hat Pirates following her engagement with Sai in the same Arc.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ec609a-f5e5-4a17-8390-9f819fcd8e1b/ddud86m-67c979e6-745f-419d-80a8-7dbb148a9448.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2U4ZWM2MDlhLWY1ZTUtNGExNy04MzkwLTlmODE5ZmNkOGUxYlwvZGR1ZDg2bS02N2M5NzllNi03NDVmLTQxOWQtODBhOC03ZGJiMTQ4YTk0NDgucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.V_0tbpEPls5tDVQk0ZeoCCxwie2YYmjX2RU6W3KKqLU', 43, 58, null),

('Bacura', true, 'Bacura is a black panther owned by the Kuja Pirates under Boa Hancock.
She is said to be the executioner of the Kuja tribe, and has been serving the tribe for generations.', true, true, false, 'animal', null, null, 44, null),

('Baggaley', true, 'Baggaley is an infamous New World pirate who allied himself with the Whitebeard Pirates. Having only appeared on a small number of occasions, there is little of his personality that can be ascertained.', true, true, false, null, null, null, 48, null),

('Bakezo', true, 'Bakezo is a member of the G-5 branch of the Marines.', true, false, true, 'G5', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d3f6c26d-2f68-431d-a66f-544d2c4756cd/detq3xo-1f738ce5-18f1-4e35-8a2d-8e06ebd33a67.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2QzZjZjMjZkLTJmNjgtNDMxZC1hNjZmLTU0NGQyYzQ3NTZjZFwvZGV0cTN4by0xZjczOGNlNS0xOGYxLTRlMzUtOGEyZC04ZTA2ZWJkMzNhNjcuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.hynQFOr9uSRKE82w7KdR22uvFzgEyYo8HEphY_BJF3Y', null, null, null),

('Buckingham Stussy', true, 'Miss Buckin, is a former member of both the Rocks Pirates and the illegal science institute MADS, during which she went by the name of Miss Buckingham Stussy. She is the self-proclaimed lover of the deceased Emperor Edward Newgate and the mother of Edward Weevil, a former Warlord of the Sea.
During her time with MADS, she worked alongside other notable scientists like Dr. Vegapunk, Caesar Clown, Queen, and Vinsmoke Judge. However it has been stated that she was a freeloader who simply took and benefited from their research, hardly contributing anything of her own. The group did however, successfully produced a clone of her, Stussy, who is under the employment of CP0.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dct55km-2bbc17b4-cbb3-4d7a-a9cf-00071d9142b0.png/v1/fill/w_640,h_512,strp/stussy_queen_of_the_pleasure_district_by_bodskih_dct55km-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kY3Q1NWttLTJiYmMxN2I0LWNiYjMtNGQ3YS1hOWNmLTAwMDcxZDkxNDJiMC5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.UcAMNz6uouvpQPaGqyN9nNNhHnmJ9WROXu1pYfAXQvA', null, 55, null),

('Ban Dedessinée', true, 'Ban Dedessinée is the queen of Frauce Kingdom in the East Blue. Dedessinée is the queen of a nation affiliated with the World Government and one of the few allowed to attend the Levely, which grants her some authority over matters concerning the world.', true, false, false, 'queen', null, null, null, null),

('Banchi', true, 'Banchi is a giant turtle used by Miss All Sunday for transportation. It is unknown what happened to him after the Arabasta Saga. He is classified as a Type A creature, "Big Friendly".', true, false, false, 'animal', null, null, null, null),

('Banchina', false, 'Banchina was Usopp''s mother and Yasopp''s wife. She was left by her husband to follow his dreams and go to sea with the Red Hair Pirates. However, this caused Usopp to grow up with a sick mother who became bed-ridden due to her illness. \n
Every day Usopp would tell the same lie, that his father had returned to take them away, hoping it would keep her hopes high and help her to recover. However, she knew he would never return, and before her death, she told Usopp that she was glad he had gone out to sea. After she passed away, Usopp continued to tell the same lie, even though he no longer had any reason to do so. After she passed away, Usopp continued to tell the same lie, even though he no longer had any reason to do so.', true, false, false, 'syrup village civilian', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/6793995f-17b2-4605-9f52-a878a3cd655c/d48vf2e-96a4a351-50b7-4d3d-a523-d06734b34327.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzY3OTM5OTVmLTE3YjItNDYwNS05ZjUyLWE4NzhhM2NkNjU1Y1wvZDQ4dmYyZS05NmE0YTM1MS01MGI3LTRkM2QtYTUyMy1kMDY3MzRiMzQzMjcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.0T9SKGxwP9PBSFtfcrlq_koysnICVdqaaXpF0VhMPT0', null, null, null),

('Bankuro', null, 'Bankuro was a member of the Roger Pirates until the crew''s dissolution. His current whereabouts and status are unknown.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8105260c-cfc1-463e-b35b-5de2d500fac9/dedbcfq-feca7a41-c638-4cb6-b82e-5b07b9e768aa.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzgxMDUyNjBjLWNmYzEtNDYzZS1iMzViLTVkZTJkNTAwZmFjOVwvZGVkYmNmcS1mZWNhN2E0MS1jNjM4LTRjYjYtYjgyZS01YjA3YjllNzY4YWEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.Tpn_hQLOoGUXK-uLlLZEKyeTrElmsc16b5Lmr3y6C5I', null, 45, null),

('Banshee', true, 'Banshee was the only female member of the Spade Pirates. Since the Spade Pirates did not have a cook, Banshee was the one who prepared their meals. Banshee wields a flintlock, but her proficiency in using it is unknown.', true, true, false, null, null, null, 60, null),

('Banzaburo', false, 'Banzaburo was a samurai of Wano Country who worked as a servant to the Kozuki Family until their fall 20 years ago.', true, false, false, 'samurai', null, null, null, null),

('Gyoro, Nin, and Bao', false, 'Gyoro, Nin, and Bao were a trio of oddly shaped Soldier Zombies that were first seen reporting to Moria about the Straw Hats'' arrival.', true, true, false, null, 'https://m.media-amazon.com/images/M/MV5BOTlhNDk2M2QtNmYyNi00ZTY1LWFiNDgtMjBjMDQxYzYzYmRlXkEyXkFqcGdeQXVyNzgxMzc3OTc@._V1_.jpg', null, 9, null ),

('Bao Huang', true, 'Bao Huang is a Shinuchi in the Beasts Pirates, being part of the crew''s surveillance division, the "Marys". She appears to have the duty of keeping and presenting daily schedules for the crew and their captain Kaidou.', true, true, false, null, 'https://pbs.twimg.com/media/E75uttmXEAUNdvl?format=jpg&name=large', 131, 59, null),

('Bariete', true, 'Bariete is a monkey mink who is a member of the Recon Squad, and the one in charge of guarding the gates of the Mokomo Dukedom.', true, false, false, 'mink', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de5gc17-a9fd16e7-1f61-4b81-b552-b4dc0c5319d6.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU1Z2MxNy1hOWZkMTZlNy0xZjYxLTRiODEtYjU1Mi1iNGRjMGM1MzE5ZDYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.5THPkBJjM2r5B3UaNIef_eGI_R_oW17EPQTt5C86Fks', null, null, null),

('Barry', true, 'Barry is a member of the Spade Pirates. He is a slim man with long, thin limbs and a pointed nose. He has light-colored hair, wears a light-colored, long-sleeved top that has a high collar and is looser fitting at the bottom. He also wears a light-colored hat, a necklace, striped pants, and pointed boots with a heel.', true, true, false, false, null, null, null, 60, null),

('Bartholomew Kuma', true, 'Bartholomew Kuma is a former Warlord of the Sea, the former king of the Sorbet Kingdom, and an officer and founding member of the Revolutionary Army with a bounty of 296,000,000 Beli''s. He is the father of Jewelry Bonney, a member of the Worst Generation. According to both himself and Bonney, he is part of a special race. Once feared as an extremely vicious pirate, earning himself the title "Tyrant", he is now a human weapon called a "Pacifista", developed by the scientist Vegapunk. Once Vegapunk finished his modifications on Kuma, the Warlord was converted into the first complete Pacifista cyborg, with the serial PX-0, and mentally died in the process. After protecting the Thousand Sunny for 2 years, Kuma became a slave-to-rent for the World Nobles as punishment until his fellow revolutionaries freed him. The Straw Hat Pirates had an encounter with him during the Thriller Bark Arc and later during the Sabaody Archipelago Arc, where he was responsible for separating the crew. He is also a major antagonist in the Marineford Arc where he took part in the Summit War of Marineford and sided with the Marines, along with most of the other Warlords.', true, false, false, 'slave', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de2zztc-dd9c91a0-deab-458a-b644-edc8a50738f9.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGUyenp0Yy1kZDljOTFhMC1kZWFiLTQ1OGEtYjY0NC1lZGM4YTUwNzM4ZjkucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.cN98hDEbwrTMxsBYQrHEZBUTzsUCemmdwpYMDbxRcWI', 25, null, null ),

('Bartolomeo', true, 'Bartolomeo the Cannibal is a Super Rookie, the captain of the Barto Club and the captain of the second ship of the Straw Hat Grand Fleet. He joined as a gladiator to compete for the Mera Mera no Mi at the Corrida Colosseum, where he met Monkey D. Luffy and pledged his loyalty towards him after winning the B Block. Formerly a mob boss from the East Blue, Bartolomeo witnessed Luffy miraculously escaping the execution Buggy had prepared for him during the events of the Loguetown Arc, a scene that changed Bartolomeo''s life and turned him into a major fan of the Straw Hat Pirates. He is an ally of Luffy during the Dressrosa Arc, the beginning of the Zou Arc, the non-canon Silver Mine Arc, the movie One Piece: Stampede and One Piece Film: Red He is also one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbvflxt-ccb11d22-ca73-47a7-859f-ff9198102cd7.png/v1/fill/w_640,h_512,strp/bartolomeo_2nd_commander_of_straw_hat_grand_fleet_by_bodskih_dbvflxt-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kYnZmbHh0LWNjYjExZDIyLWNhNzMtNDdhNy04NTlmLWZmOTE5ODEwMmNkNy5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.XueLDJCnUaWsA2KZJj7hDiNY0Rd3_83dYqBmjoEUkoI', 47, 7, null),

('Baskerville', null, 'Three-Headed Baskerville is the Chief Justice of Enies Lobby, in service of the World Government.[1] Ostensibly a three-headed man, "he" is actually three men—Bas, And, and Kerville—who are such close friends that they prefer acting as one body.', true, false, true, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbqa6bb-4ca83f73-7f5a-48f8-9265-30fe6f436a52.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJxYTZiYi00Y2E4M2Y3My03ZjVhLTQ4ZjgtOTI2NS0zMGZlNmY0MzZhNTIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.XtO1LvK69NXqX7mS9pClsSgURGR0ObWX9hz92a6ZFzc', null, null, null),

('Basil Hawkins', null, 'Basil Hawkins is an infamous pirate from North Blue known as the "Magician" and the captain of the Hawkins Pirates. He is one of twelve pirates who are referred to as the "Worst Generation". His previous known bounty amounted to 249,000,000 Beli''s, but after the timeskip, it was raised to 320,000,000 Beli''s. After encountering Kaidou, he joined the Beasts Pirates and became one of the crew''s Shinuchi. Due to his actions and role, he is a supporting antagonist in the Wano Country Arc.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dczgdlg-6b3d45da-46f7-4785-97aa-12d474f56e9f.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN6Z2RsZy02YjNkNDVkYS00NmY3LTQ3ODUtOTdhYS0xMmQ0NzRmNTZlOWYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.WdZfvvv78Tl0J6vqgQx0n7zf-MAzhd5QCs21QAC2UNU', 29, 13, null),

('Basilisk', true, 'The Basilisk is the second-in-command of Impel Down''s Level 2: Beast Hell, under the Sphinx.', true,false, false, 'animal','https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dczge2h-d4818522-90a8-46dc-ba3a-20b964e68050.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN6Z2UyaC1kNDgxODUyMi05MGE4LTQ2ZGMtYmEzYS0yMGI5NjRlNjgwNTAucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.wNjKUDRL94eNaq0yHNQJDhAm4ZiU9YODVt8h8sXu0zk', null, null, null),

('Bastille', true, '"Shark Cutter" Bastille is a Marine Vice Admiral who took part in the Summit War of Marineford. He later appeared in Dressrosa under the command of Admiral Fujitora.', true, false, true, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dfcr09r-21515f9f-a375-4ab6-9010-8d5ff15c195f.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGZjcjA5ci0yMTUxNWY5Zi1hMzc1LTRhYjYtOTAxMC04ZDVmZjE1YzE5NWYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.M6giFIi6Wd-qvhDYQQp_fiBFhLBO52uL3KpvYMCKV-k', null, null, 3),

('Batman', true, 'Batman is a Gifter in the Beasts Pirates. He is a skilled archer, being able to shoot powerful arrows from the air mid-flight. He was surprised that Roronoa Zoro was able to block his shots, showing he holds his skills in high regard.In the anime, he is shown to be able to control the direction of his arrows with sonar.', true, true, false, null, 'https://static.tvtropes.org/pmwiki/pub/images/496e6249d6b372371792c095d3b2eb50_1.jpg', 131, 59, null ),

('Baxcon', true, 'Baxcon is a dwarf from Tontatta Kingdom who first appeared in the Riku Royal Army Headquarters beneath the Flower Field.', true, true, false, null, null, null, 39, null),

('Beer VI', true, 'Beer VI is the king of the Roshwan Kingdom.', true, false, false, 'king', 'https://cdn.myanimelist.net/images/characters/6/384797.jpg', null, null, null),

('Belo Betty', true, 'Belo Betty is the commander of the East Army in the Revolutionary Army.As a Revolutionary Army executive, Betty is in a powerful position within the organization. As commander of the East Army, she has control over all the soldiers in it. Betty is an extremely charismatic orator. With her Devil Fruit powers, she inspires numerous people to fight. Morley called Betty the flag bearer of freedom for her skills.', true, false, false, 'revolutionary', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dd8emz2-c3ef3b7b-251b-4c82-861e-7e479d881567.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGQ4ZW16Mi1jM2VmM2I3Yi0yNTFiLTRjODItODYxZS03ZTQ3OWQ4ODE1NjcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.uaV5rjD8ONuRnmH5jipk3rvyTwjY-6X7njymYJV2gX4', 75, null, null ),

('Belladonna', true, 'Belladonna is one of the Kuja of Amazon Lily, and the doctor of the island.', true, false, false, 'kuja', null, null, null, null ),

('Bellamy', true, 'Bellamy the Hyena is the former captain of the Bellamy Pirates, and a former member of the Donquixote Pirates. After the Dressrosa Arc, he retired from piracy and became a dyer. When he made his debut, he had a bounty of 55,000,000 Beli''s and was known as the "Big-Time Rookie" within Mock Town. After the timeskip, his bounty has increased to 195,000,000 Beli''s. He was the main antagonist of the Jaya Arc and a minor antagonist in the Dressrosa Arc. He is also one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', true, false, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd1hq-a8ec903b-d681-4d51-9d1b-c5d3902b0ae0.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDFocS1hOGVjOTAzYi1kNjgxLTRkNTEtOWQxYi1jNWQzOTAyYjBhZTAucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.GpptrL_lXB9rCJNO5y260g5qQeFyaTikk4TPnXYxSZM', 13, 53, null ),

('Bellett', true, 'Bellett was the prince of an unnamed kingdom who became a pirate and was consequently imprisoned in Impel Down, and whose gender was unwillingly inverted.', true, true, false, null, null, null, null, null),

('Bell-mère', false, 'Bell-mère was a former Marine and the adoptive mother of Nami and Nojiko, introduced in a flashback during the Arlong Park Arc. She raised the two girls for approximately nine years until she was murdered by Arlong.', true, false, false, 'former marine', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd40k-c6674d59-3505-493e-a736-fd509d5288ee.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDQway1jNjY3NGQ1OS0zNTA1LTQ5M2UtYTczNi1mZDUwOWQ1Mjg4ZWUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.LBJBtw81BGpAJKRvFjE9tzL19WyEryk44_fYBXgydms', null, null, null),

('Benn Beckman', true, 'Benn Beckman, is the first mate of the Red Hair Pirates. Beckman appears to be a lot less fun-loving and a lot more relaxed than the other members of the crew are, acting as the level-headed member. He, Lucky Roux, and Yasopp are some of Shanks'' most trusted crew members, as they are always seen when the Red Hair Pirates are featured, usually when something crucial happens. He is a well-deserved vice-captain who silently supports the crew with a deep attitude despite their liveliness.', true, true, false, null, null, 29, null),

('Bon Clay', true, 'Bentham of the Wild, alias Mr. 2 Bon Clay, is a former officer agent of Baroque Works and an okama. He was a major antagonist during the Arabasta Arc, and (along with his fellow Officer Agents) one of the central characters in Miss Goldenweek''s "Operation: Meet Baroque Works". While he was once an enemy of Luffy''s as a member of Baroque Works, the two became quick friends, leading Bon Kurei to sacrifice himself for Luffy both at Arabasta and later at Impel Down, being one of his main allies during that Story Arc. He is currently the new queen of Newkama Land.', true, true, false, 'newkama land', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ec609a-f5e5-4a17-8390-9f819fcd8e1b/dds66wn-f4dcc41d-0413-4a7f-a26e-48686262981b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2U4ZWM2MDlhLWY1ZTUtNGExNy04MzkwLTlmODE5ZmNkOGUxYlwvZGRzNjZ3bi1mNGRjYzQxZC0wNDEzLTRhN2YtYTI2ZS00ODY4NjI2Mjk4MWIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.SWJEVVU7TFJ4kKOFWIaqjhfCndaCr1ZjHmk4lhoKLQQ', 9, null, null ),

('Bepo', true,'Bepo is a polar bear mink and the navigator of the Heart Pirates. He is the younger brother of the late Nox Pirate Zepo. As the navigator of the Heart Pirates, it can be assumed that Bepo has the knowledge required to navigate the seas. The level of his skills is as yet unknown, though it is expected that he is reasonably capable of navigating through the Grand Line. Interestingly enough, despite his occupation, he is not seen wearing a Log Pose, which is essential for Grand Line navigation. He also has some skill in cartography, as he was the one who drew the map of Dressrosa and Green Bit that Law shared with the Straw Hats. However, he appears to be a bit messy, as the map had his paw print on it, and Nami stated that his map-drawing and navigation skills are far from her own.', true, true, false, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd6yo-6f73582b-ea6a-4f59-8a3e-d2f502949a1c.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDZ5by02ZjczNTgyYi1lYTZhLTRmNTktOGEzZS1kMmY1MDI5NDlhMWMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.SYMPKkwi4cU4TRQXEtcoutfPOzG3ixhq7kcQfbIJIkM', null,15, null ),

('Bian', true, 'Bian is a dwarf from Tontatta Kingdom who serves as the leader of the Pink Bee Squad and a member of the Tontatta Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dchidal-a849149d-1b27-40d0-ad23-df0cc0265ebd.png/v1/fill/w_640,h_512,strp/bian_tonta_corps_leader_of_pink_bee_squad_by_bodskih_dchidal-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kY2hpZGFsLWE4NDkxNDlkLTFiMjctNDBkMC1hZDIzLWRmMGNjMDI2NWViZC5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.pZvUa7k4W6MEHuIKeprhlf86kLK_ja2r70vKVqQYg7Q', 128, 39, null), 

('Big Pan', true, 'Big Pan is the largest member of the Foxy Pirates and a combatant of the Groggy Monsters. He is a wotan, a half fish-man (loach fish-man) half giant breed. Due to his actions, he is a major antagonist during the Long Ring Long Land Arc', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbze5pz-1393c60a-6b3f-4fd2-9d46-832871280841.png/v1/fill/w_438,h_350,strp/big_pan_of_the_foxy_pirates_by_bodskih_dbze5pz-350t.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kYnplNXB6LTEzOTNjNjBhLTZiM2YtNGZkMi05ZDQ2LTgzMjg3MTI4MDg0MS5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.5ER1210RBE8akRdDXvSyz143bh0jzBfMmHNW9jz5GhE' null, 18, null),

('Bimine', true, 'Bimine is the mayor of Pucci, "The Gourmet Town". He was first mentioned when the town Pucci was brought up by Kalifa.', true, false, false, 'mayor', null, null, null, null),

('Bingo', true, 'Bingo is a former priest and cooper who currently lives in Ebisu Town in Wano Country. Bingo is a remorseless criminal, having entered a three-person con with Bongo and Bungo to swindle the citizens of Wano. Bingo, in particular, was taking advantage of people mourning their deceased relatives by selling them caskets at outrageous prices. Bingo is also a foolish man whose base instincts and passion led him to ruin. The prospect of having a life with the highest-ranking courtesan Komurasaki was enough to get Bingo to sell everything he had, to the point of committing the typically immoral act of selling his family. This consuming passion made him trusting of Komurasaki to a fault, being willing to leave all the money he earned with her without using any legal safeguards. After finding out that Komurasaki had swindled him, Bingo fell into complete despair, leading him to go all the way toward trying to kill the courtesan he was once enamored with to avenge his destitution, and this desire was all he cared about to the point where he did not care if he was killed afterward. Upon his exile, he, along with his two accomplices, were very unhappy being forced to live in the poverty-ridden Ebisu Town, and despite Tonoyasu''s kindness to meet their every need, the three continued to make it very difficult.', true, false, false, 'wano civilian', null, null, null, null),

('Bishamon', true, 'Bishamon is a ninja and a member of the Beasts Pirates. He previously was a member of the Orochi Oniwabanshu which served the shogun of Wano Country, Kurozumi Orochi.', true, true, false, 'ninja', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/df2sjyp-e6600840-8daa-4e03-b8fc-c244893a0d97.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGYyc2p5cC1lNjYwMDg0MC04ZGFhLTRlMDMtYjhmYy1jMjQ0ODkzYTBkOTcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.ZNUjIpNjFf0M4aXVEkedfWMa3uMvN69q1NIHOiGLSzI', null, 59, null),

('Biyo', true, 'Biyo is a child who was held captive on Punk Hazard by Caesar Clown. He was freed with the rest of the children by the Straw Hat Pirates.', true, false, false, 'punk hazard child', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4acf81a0-04ec-4d63-b73d-f6936c84f13b/dervg3i-4c2911cd-9251-4b6f-854a-6e68ac8499d6.png/v1/fill/w_586,h_1363,strp/biyo___children_experiment_from_punk_hazard_render_by_lowr0_dervg3i-pre.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzRhY2Y4MWEwLTA0ZWMtNGQ2My1iNzNkLWY2OTM2Yzg0ZjEzYlwvZGVydmczaS00YzI5MTFjZC05MjUxLTRiNmYtODU0YS02ZTY4YWM4NDk5ZDYucG5nIiwiaGVpZ2h0IjoiPD0yOTc2Iiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uud2F0ZXJtYXJrIl0sIndtayI6eyJwYXRoIjoiXC93bVwvNGFjZjgxYTAtMDRlYy00ZDYzLWI3M2QtZjY5MzZjODRmMTNiXC9sb3dyMC00LnBuZyIsIm9wYWNpdHkiOjk1LCJwcm9wb3J0aW9ucyI6MC40NSwiZ3Jhdml0eSI6ImNlbnRlciJ9fQ.XYKkJ4f7WELXmFcQrGTe5XO14ewuC-aQAgJU2iQPVg4', null, null, null), 

('Bizarre', true, 'Bizarre is an infamous New World pirate captain who was allied with Whitebeard.', true, true, false, false, null, null, null, null, null),

('Black Maria', true, 'Black Maria is one of the Tobiroppo, the strongest six Shinuchi of the Beasts Pirates.[5] She owns her own brothel on Onigashima near Kaidou''s castle. Due to her actions and role, she is a supporting antagonist in the Wano Country Arc.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/deqkgtm-7fb49618-3cef-436e-9d7b-f028add750ae.png/v1/fill/w_640,h_512,strp/black_maria_one_of_the_tobiroppo_by_bodskih_deqkgtm-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kZXFrZ3RtLTdmYjQ5NjE4LTNjZWYtNDM2ZS05ZDdiLWYwMjhhZGQ3NTBhZS5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.qNlsd91aucoMSEgSfJUnU9Ccv-dyudUCrCqr00HeJyI', 151, 59, null),

('Blackback', true, 'Blackback, also known by his initials BB, is a gorilla mink and a Guardian of the Whale Forest.', true, false, false, 'mink', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dcicw05-264b10aa-e4f8-4e6c-8c1f-98b281cacf47.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGNpY3cwNS0yNjRiMTBhYS1lNGY4LTRlNmMtOGMxZi05OGIyODFjYWNmNDcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.lK40hELrbi_iwPNA8EjfyjrLfG7GyjCRrsrnh3Ja19c', null, null, null),

('Blamenco', true, 'Blamenco is the commander of the 6th division of the Whitebeard Pirates. Blamenco is extremely strong, as he is seen wielding a gigantic hammer more than twice the size of his body with ease. During the Summit War of Marineford he is seen as being able to fight and defeat multiple Marine officers with one strike, and later emerge uninjured and unharmed at the end of the battle.', true, true, false, null 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcqbrk-e145f845-d5ac-4278-9e34-3494615c2143.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjcWJyay1lMTQ1Zjg0NS1kNWFjLTQyNzgtOWUzNC0zNDk0NjE1YzIxNDMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.YRU_WvWQ2oWIeMu7MSIT5RMjj3sAG0Mq0T8bk9w5iSA', 37, 48, null ),

('Blenheim', true, 'Blenheim is the commander of the 9th division of the Whitebeard Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbo8kti-c6a7f0fe-cb1a-4214-9e82-71e278e09429.png/v1/fill/w_640,h_512,strp/blenheim_9th_commander_of_whitebeard_pirates_by_bodskih_dbo8kti-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTEyIiwicGF0aCI6IlwvZlwvNTExNTgzMTYtZmQ3ZS00OGNhLWI1ZmUtODU0MmU5ZGZlMzU3XC9kYm84a3RpLWM2YTdmMGZlLWNiMWEtNDIxNC05ZTgyLTcxZTI3OGUwOTQyOS5wbmciLCJ3aWR0aCI6Ijw9NjQwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.Hs5iy2_GjmZbIH9_fvAkTw5osyHPa-F1iwJN79RDpno', null, 48, null)

('Blondie', true, 'Blondie is an infamous New World pirate who was allied with Whitebeard.', true, true, false, null,'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de9647o-3da23438-b12b-47a2-81fd-8a4e6e358653.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU5NjQ3by0zZGEyMzQzOC1iMTJiLTQ3YTItODFmZC04YTRlNmUzNTg2NTMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.-Rg-NeG9JI1BRS3ornoQ6PQ58tiFSFVcXwWeycNFdx4', null, null, null),

('Blue Fan', true, 'Blue Fan is a member of the Kuja Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de634vv-68d9ff36-db2e-402b-ab1e-165e19301bf5.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU2MzR2di02OGQ5ZmYzNi1kYjJlLTQwMmItYWIxZS0xNjVlMTkzMDFiZjUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.TUvA63c1s_CiX1_9Ycngqmvr2QoZYcTtGpyK4KUWcWw', null, 44, null),

('Blue Gilly', true, 'Blue Gilly is a martial artist from the Longleg Tribe. He joined as a gladiator at the Corrida Colosseum to compete for the Mera Mera no Mi. He is an ally of Luffy during the Dressrosa Arc. After the battle with the Donquixote Pirates at Dressrosa, he became part of the Straw Hat Grand Fleet when he joined the XXX Gym Martial Arts Alliance, which later converted to a pirate crew called the Ideo Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dczgdob-6772174e-0a49-45a3-84c3-237f18373753.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN6Z2RvYi02NzcyMTc0ZS0wYTQ5LTQ1YTMtODRjMy0yMzdmMTgzNzM3NTMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.Rjcr1mXh7BZS8RBjXjlTssXMRHtSCexLNiEENwMh07A', null, 38, null),

('Bluejam', true, 'Bluejam was the captain of the Bluejam Pirates, and an infamous pirate of the East Blue. He was one of the main antagonists of the Post-War Arc.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dd0digx-6477d369-22c3-45e7-af0f-040e73e02e15.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGQwZGlneC02NDc3ZDM2OS0yMmMzLTQ1ZTctYWYwZi0wNDBlNzNlMDJlMTUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.67ZvLmQqE3nE_KEqHkChpd2Kj95KR290917zsD0avJE', null, 6, null),

('Blueno', true, 'Blueno is a member of CP0. Prior to being instated into CP0, he was a member of CP9 who worked undercover as the bartender of a bar in Water 7. After CP9''s defeat at the hands of the Straw Hat Pirates, he and the rest of CP9 were dismissed by Spandam. For unexplained reasons, he was later reinstated and promoted to CP0. He was one of the major antagonists during the Water 7 Arc and a minor antagonist during the Enies Lobby Arc.', true, false, false, 'cipher pol agent', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd0vp-b2967560-6a71-43b7-b9ad-1c20b7b467aa.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDB2cC1iMjk2NzU2MC02YTcxLTQzYjctYjlhZC0xYzIwYjdiNDY3YWEucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.DFs1oi22WLTnhv32i-NXS35MyaL_immUoivaImRIl1Q', 16, null, null),

('Blumarine', null, 'Blumarine was a member of the Roger Pirates until the crew''s dissolution. His current whereabouts and status are unknown.', true, true, false, null, null, null, 45, null),

('Boa Hancock', true, '"Pirate Empress" Boa Hancock is the captain of the Kuja Pirates and was the only female Warlord of the Sea prior to the organization''s disbandment. She is the current empress, known as the "Snake Princess", of Amazon Lily and rules over the Kuja tribe with her two younger Gorgon sisters, Boa Sandersonia and Boa Marigold. She was first mentioned by the Risky Brothers at the end of the Thriller Bark Arc when comparing her legendary beauty to the beauty of mermaids. She is the main antagonist of the Amazon Lily Arc, before befriending and falling in love with Monkey D. Luffy in the same arc and eventually pledged both her love and loyalty to him after she understood the story behind how he punched a Celestial Dragon and heard his declaration that he only despises the World Nobles, and not her who had to suffer through their egregious actions, leading to her becoming one of his most stalwart allies. She becomes his ally during the rest of the Summit War Saga, as well as the Return to Sabaody Arc. She also acts as an ally of Luffy during the 3D2Y special, the Cidre Guild filler Arc, and the movie One Piece: Stampede. While she used to be employed within the Seven Warlords, her love for Monkey D. Luffy has caused her to turn against the World Government on a number of occasions, thus putting her status as a Warlord in jeopardy. It was not until the most recent Levely where the Warlords were officially abolished due to the exposed nefarious actions of Crocodile and Doflamingo towards the other monarchs, causing her to lose her status as a warlord as well.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd4ed-b80e9027-edaf-45c0-825c-41b58033981b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDRlZC1iODBlOTAyNy1lZGFmLTQ1YzAtODI1Yy00MWI1ODAzMzk4MWIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.XqC5I8I-J07U5NNm-I4GUyVTExnpUQsU1n9qn516Ync', 31, 44, null),

('Boa Marigold', true, 'Boa Marigold is one of the three Gorgon Sisters that rule over Amazon Lily, and one of the second-in commands of the Kuja Pirates. She and her sisters are called the Gorgon sisters for supposedly heroically slaying a monster called the Gorgon. She is the younger sister of Boa Hancock and Boa Sandersonia.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dczgdmx-376f62ca-60da-472f-94c9-0dbccf805a97.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN6Z2RteC0zNzZmNjJjYS02MGRhLTQ3MmYtOTRjOS0wZGJjY2Y4MDVhOTcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.tZwYDRttEp3fVg4tExkF0qYmWtqeXt7UDDc5nToyrb4', 126, 44, null),

('Boa Sandersonia', true, 'Boa Sandersonia is one of the three Gorgon Sisters that rule over Amazon Lily, and one of the second-in commands of the Kuja Pirates. She and her sisters are called the Gorgon Sisters for supposedly heroically slaying a monster called the Gorgon. She is the younger sister of Boa Hancock and the elder sister of Boa Marigold.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dbcd2p6-0dd75e1b-382f-4c08-b5fe-d5cf678366df.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGJjZDJwNi0wZGQ3NWUxYi0zODJmLTRjMDgtYjVmZS1kNWNmNjc4MzY2ZGYucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.2kmH4rKaO4hd0GpekOKPsy_IBNEHy2MuH-nhFfxs5p8', 125, 44, null),

('Bobbin', null, '"Sweeper" Bobbin is a bishop-ranked combatant[3] of the Big Mom Pirates.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dfcr0j6-34102a14-38ba-405e-975f-63cc32bff772.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGZjcjBqNi0zNDEwMmExNC0zOGJhLTQwNWUtOTc1Zi02M2NjMzJiZmY3NzIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.jB6IGKBRBPgITEm5F2aVm9yXjvHBf6pXc3aWbKCqbw4', null, 42, null),

('Bobby Funk', true, 'Bobby Funk is an assassin from the Mogaro Kingdom and Kelly Funk''s younger brother. He joined as a gladiator at the Corrida Colosseum to compete for the Mera Mera no Mi.', true, false, false, 'assassin', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/51158316-fd7e-48ca-b5fe-8542e9dfe357/dczgdo3-b089cdda-22f3-4686-9f65-dbb31b05c49b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzUxMTU4MzE2LWZkN2UtNDhjYS1iNWZlLTg1NDJlOWRmZTM1N1wvZGN6Z2RvMy1iMDg5Y2RkYS0yMmYzLTQ2ODYtOWY2NS1kYmIzMWIwNWM0OWIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.X2-TuBnGrhQB0fKhJqeqPUbF9DYNartYI9muEvFoQoI', null, null, null),

('Bobomba', true, 'Bobomba is a dwarf from Tontatta Kingdom who first appeared on Green Bit. He is the younger brother of Bomba.', true, true, false, null, null, null, 39, null),

('Bogard', true, 'Bogard is a Marine Headquarters Marine and the right hand man of Vice Admiral Monkey D. Garp. His actual rank is currently unknown.', true, false, true, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1ce1372a-b75c-4058-b0c8-1bf1c2d6837e/de53zx6-7245808f-476d-433d-8145-72fd28f8cc97.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFjZTEzNzJhLWI3NWMtNDA1OC1iMGM4LTFiZjFjMmQ2ODM3ZVwvZGU1M3p4Ni03MjQ1ODA4Zi00NzZkLTQzM2QtODE0NS03MmZkMjhmOGNjOTcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.CsANgrMiL8Cm7vcyFPw2-q4D4-63MxhH1jFfjhJxl5Q', null, null, null),

('Bomba', true, 'Bomba is a member of the Marines G-5 Branch Unit 01. He is a subordinate of Smoker and Tashigi.', true, false, true, 'G5', null, null, null, null),

('Bomba', true, 'Bomba is a dwarf from Tontatta Kingdom. He is one of the two vice chiefs of the Tontatta Kingdom along with Rampo, under Gancho and Leo, and serves under Leo in the Tontatta Pirates. He is the elder brother of Bobomba.', true, true, false, null, 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/05018cf7-3182-4470-a12c-7075477d4a21/d7759vj-1cd87c53-a3c8-4b80-991a-81f8e729d934.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzA1MDE4Y2Y3LTMxODItNDQ3MC1hMTJjLTcwNzU0NzdkNGEyMVwvZDc3NTl2ai0xY2Q4N2M1My1hM2M4LTRiODAtOTkxYS04MWY4ZTcyOWQ5MzQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.SXrMkkap0H23y5L9yCjAHRYveJS1CYyWpcMHOTuHypE', null, 39, null),

('Bongo', true, 'Bongo is a former lumber dealer who currently lives in Ebisu Town in Wano Country.[4] He formerly lived in the Flower Capital, but was exiled after being swindled by Komurasaki.', true, false, false, 'wano civilian', null, null, null, null )



-- name, alive, info, canon, pirate, marine, other, photo, devil_fruitID, pirate_groupID, marine_RanksID
;