\c one_piece_dev;

INSERT INTO pirate_GroupNames ( eng_name, romanized_name, canon, info, jollyRoger ) VALUES

('Straw Hat Pirates', 'Mugiwara no Ichimi', true, 'The Straw Hat Pirates, also known as the Mugiwara Pirates, Straw Hat Crew or simply the Straw Hats, are an infamous and powerful pirate crew that originated from the East Blue. They are the main focus and protagonists of the manga and anime One Piece and are led by the main protagonist Monkey D. Luffy. \n 
The "Straw Hats" are named after Luffy''s signature hat that was given to him by "Red-Haired" Shanks and are first referred to as the Straw Hat Pirates by Smoker in the Arabasta Kingdom.The crew sailed on the Going Merry, their first official Straw Hat ship, up until the Water 7 Arc. During the Post-Enies Lobby Arc, Franky and Iceburg built them a new ship which was named the Thousand Sunny by Iceburg, even though the members fought over different names.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7ab-099b3d5e-9de5-406a-a5c9-2eeaf288dd42.png/v1/fill/w_1068,h_748,q_70,strp/straw_hat_pirates_jolly_roger_by_jormxdos_dfgi7ab-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2FiLTA5OWIzZDVlLTlkZTUtNDA2YS1hNWM5LTJlZWFmMjg4ZGQ0Mi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.EdbBrUixE920pT8cWlemX_nJ9RE877BfgfeHCaqo5sA'),

('Buggy Pirates', 'Bagī Kaizokudan', true, 'The Buggy Pirates are a band of pirates led by Buggy, who is a former apprentice of the Roger Pirates. They are the main antagonists of the Orange Town Arc and one of the antagonist groups of the Loguetown Arc. Their current goal is finding Captain John''s legendary treasure. The crew has since combined with the remnants of the Alvida Pirates, forming the Buggy and Alvida Alliance. After the events of the Summit War Saga, Buggy became a member of the Seven Warlords of the Sea and used his new infamy and influence to evolve the alliance into a New World-based, Underworld organization now known as Buggy''s Delivery.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7sw-962a7147-e5c2-4b61-858f-b5ef6c3d6ee5.png/v1/fill/w_1068,h_748,q_70,strp/buggy_pirates_jolly_roger_by_jormxdos_dfgi7sw-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3N3LTk2MmE3MTQ3LWU1YzItNGI2MS04NThmLWI1ZWY2YzNkNmVlNS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.J8nL_68CPJJW6-ys-RFz0gcMVPT511SseaAhMJfOMn4' ),

('Black Cat Pirates', 'Kuroneko Kaizokudan', true, 'The Black Cat Pirates is an East Blue pirate crew formerly headed by Jango, and Kuro before that. They are the main antagonist group in the Syrup Village Arc.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7t7-092176a9-16ce-46a8-94e8-78f07e2532ae.png/v1/fill/w_1280,h_897,q_80,strp/black_cat_pirates_jolly_roger_by_jormxdos_dfgi7t7-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3Q3LTA5MjE3NmE5LTE2Y2UtNDZhOC05NGU4LTc4ZjA3ZTI1MzJhZS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.KUqD_MQimvZvogypXTSXytcY6VV400W4744_JTahcu0'),

('Krieg Pirates', 'Kurīku Kaizokudan', true, 'The Krieg Pirates, also known as the Pirate Armada due to their sheer size, were East Blue''s largest and most feared pirate crew led by Don Krieg. They consisted of a fleet of fifty pirate ships and five thousand pirates that posed as a fearsome force until the fleet was decimated by Dracule Mihawk. Due to their actions and role, they are the main antagonists of the Baratie Arc.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-krieg-pirates.png'), 

('Yes Pirates', 'Iesu Kaizokudan', true, 'The Yes Pirates were a pirate crew that originated from the East Blue.Billy, the captain of the Yes Pirates, had a bounty of 3,000,000 belis, which is considered a standard low for East Blue, the weakest of the Four Blues. The crew is rather weak, as the captain was easily arrested by Smoker, and Koze and Packy attempted a surprise attack against Tashigi, but also lost.', null),

('Bluejam Pirates', 'Burūjamu Kaizoku-dan', true, 'The Bluejam Pirates was a pirate crew led by Bluejam. They came into conflict with Luffy, Ace, and Sabo 12 years ago on Dawn Island, which began with Ace and Sabo stealing money from one of the crew members.', null),

('Barto Club', 'Baruto Kurabu', true, 'The Barto Club is a pirate crew led by Bartolomeo and the second ship of the Straw Hat Grand Fleet. They also are one of the central characters from ''The Stories of the Self-Proclaimed Straw Hat Grand Fleet'' Cover Page Serial.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7h5-d1cd6c67-50f5-460f-8220-a757a0e9ef5c.png/v1/fill/w_1280,h_897,q_80,strp/barto_club_jolly_roger_by_jormxdos_dfgi7h5-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2g1LWQxY2Q2YzY3LTUwZjUtNDYwZi04MjIwLWE3NTdhMGU5ZWY1Yy5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.t5DI137ssJSx4XJKDoLdH6PZhOk_6mlePAFGuAmdsG4'),

('Gally Pirates', 'Gyarī Kaizokudan', true, 'The Gally Pirates are a pirate crew that appeared in Romance Dawn, Version 1. Their captain is Crescent-Moon Gally.', null),

('Thriller Bark Pirates', 'Surirā Bāku Kaizokudan', true, 'The Thriller Bark Pirates is the second pirate crew captained by the former Warlord, Gecko Moria. They are the main antagonist group in the Thriller Bark Arc, where they operated from the mysterious Florian Triangle to abduct unsuspecting victims of their shadows for their undead zombie army.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-thriller-bark-pirates.jpg'),

('Fire Tank Pirates', 'Faia Tanku Kaizokudan', true, 'The Fire Tank Pirates[6] are an infamous and notable rookie pirate crew who are led by Capone Bege, originated in the West Blue, and arrived on the Sabaody Archipelago around the time the Straw Hat Pirates arrived there two years ago, along with other rookie crews. As such, they are part of the Worst Generation. \n
Following the two-year timeskip, they briefly became subordinate to Big Mom, one of the Four Emperors, and her crew on Whole Cake Island. They formed a temporary alliance with the Sanji Retrieval Team to assassinate Big Mom, which ended in failure, and they ended their alliance after escaping the Whole Cake Chateau.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7w5-ebf8866b-a66d-4ab2-98e0-558f2caa5e43.png/v1/fill/w_357,h_250,q_70,strp/firetank_pirates_jolly_roger_by_jormxdos_dfgi7w5-250t.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3c1LWViZjg4NjZiLWE2NmQtNGFiMi05OGUwLTU1OGYyY2FhNWU0My5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.BsEeNDn7b6UsJr-xNJCSJnm9JyeV7XuORzO_xa62MfY'),

('Happo Navy', 'Happō Suigun', true, 'he Happo Navy is a pirate crew led by the Chinjao Family of the Kano Country. Under Sai, the Happo Navy is the third ship of the Straw Hat Grand Fleet. \n
They also are one of the central characters from ''The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial''.','https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7hl-242de520-e5e4-4fbe-9004-5b58a374feef.png/v1/fill/w_1068,h_748,q_70,strp/happo_navy_jolly_roger_by_jormxdos_dfgi7hl-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2hsLTI0MmRlNTIwLWU1ZTQtNGZiZS05MDA0LTViNThhMzc0ZmVlZi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.bc8-zbCGQE3KSBPWMb0n5h7z45vIM2fqPB3r4H0dQpY' ),

('Masira Pirates', 'Mashira Kaizokudan', true, 'The Masira Pirates is a crew of treasure hunters and shipwreck salvagers. They are part of the Saruyama Alliance, alongside the Shoujou Pirates and Mont Blanc Cricket.', 'https://comicvine.gamespot.com/a/uploads/scale_small/7/72480/5222419-mp.jpg'),

('Hawkins Pirates', 'Hōkinsu Kaizokudan', true, 'The Hawkins Pirates are an infamous and notable rookie pirate crew introduced in Sabaody Archipelago around the time the Straw Hat Pirates arrived there two years ago. As such, they are part of the Worst Generation, with their captain being Basil Hawkins. \n
After having been part of a short-lived alliance with the Kid and On Air Pirates, the crew is currently a subordinate to the Beasts Pirates, and thus operates in Wano Country.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7wh-57593281-45cb-4765-9d7f-2354ba98afc7.png/v1/fill/w_1280,h_897,q_80,strp/hawkins_pirates_jolly_roger_by_jormxdos_dfgi7wh-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3doLTU3NTkzMjgxLTQ1Y2ItNDc2NS05ZDdmLTIzNTRiYTk4YWZjNy5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.UgPcC0YFm0jzRFLf8fryEfrtX2JvoCjGTiQeckRuOek' ),

('Drake Pirates', 'Dorēku Kaizokudan', true, 'The Drake Pirates are an infamous and notable rookie pirate crew originating from the North Blue, and are led by X Drake, who is later revealed to still be part of the Marines. They were introduced on Sabaody Archipelago around the time the Straw Hat Pirates arrived there two years ago and are part of the Worst Generation.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7wn-8f1c0c96-ee6a-4528-bb7b-9f2d31dacaa2.png/v1/fill/w_1280,h_897,q_80,strp/drake_pirates_jolly_roger_by_jormxdos_dfgi7wn-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3duLThmMWMwYzk2LWVlNmEtNDUyOC1iYjdiLTlmMmQzMWRhY2FhMi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.TNm1kLHTBjBF1JfGa_VXakhHuxIKN4nJIdO3-UkltNg' ),

('Heart Pirates', 'Hāto no Kaizokudan', true, 'The Heart Pirates are an infamous and notable rookie pirate crew from the North Blue and introduced on Sabaody Archipelago around the time the Straw Hat Pirates arrived there two years ago. Their captain, Trafalgar D. Water Law, is a member of the Worst Generation and a former member of the Seven Warlords of the Sea. They were in an alliance with the Straw Hat Pirates, Kozuki Family, and Mink Tribe with the goal of taking down Kaidou of the Four Emperors. The alliance was dissolved after their objective of taking down Kaidou was achieved.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7uq-9e758026-85f6-48ea-8cd5-ed32e87aba8a.png/v1/fill/w_1068,h_748,q_70,strp/heart_pirates_jolly_roger_by_jormxdos_dfgi7uq-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3VxLTllNzU4MDI2LTg1ZjYtNDhlYS04Y2Q1LWVkMzJlODdhYmE4YS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.QDOdAALjk_WZPTVQNiCi_HTGG9-DFtSYovj63jrO_3s' ),

('Caribou Pirates', 'Karibū Kaizokudan', true, 'The Caribou Pirates are a crew who arrived at Sabaody Archipelago around the same time as the Straw Hats were reuniting. Their captains are the brothers Caribou and Coribou, which temporarily changed to Demaro Black when they joined the Fake Straw Hat Crew, under the belief they were real until the truth was disclosed.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/680bb227-0c56-4551-9057-05acdfa8ecbe/d5dbain-983d8b73-0bef-40c5-bf05-7a790b6c5cc9.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzY4MGJiMjI3LTBjNTYtNDU1MS05MDU3LTA1YWNkZmE4ZWNiZVwvZDVkYmFpbi05ODNkOGI3My0wYmVmLTQwYzUtYmYwNS03YTc5MGI2YzVjYzkuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.omNVtwVpXG0IILKEwV_WcroInUebb5seanXgLhJKJ2w'),

('Shoujou Pirates', 'Shōjō Kaizokudan', true, 'The Shoujou Pirates is a crew of treasure hunters and echolocating explorers. Their captain is Shoujou. They are part of the Saruyama Alliance, alongside the Masira Pirates and Mont Blanc Cricket.', null),

('Foxy Pirates', 'Fokushī Kaizokudan', true, 'The Foxy Pirates are a group of pirates led by Foxy the Silver Fox. A majority of the crew is composed mostly of crewmen won through the Davy Back Fight. The crew is composed of 500 members, according to the anime. \n
They are the main antagonist group in the Long Ring Long Land Arc. They also act as an antagonist group in the Foxy''s Return and Spa Island filler Arcs.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-foxy-pirates.png'),

('Bonney Pirates', 'Bonī Kaizokudan', true, 'The Bonney Pirates are an infamous and notable rookie pirate crew from South Blue that made their debut on the Sabaody Archipelago the same time the Straw Hat Pirates arrived there two years ago. As such, they are part of the Worst Generation. Following being defeated by the Blackbeard Pirates and captured by Akainu in the New World, Bonney was taken to Marine Headquarters, during which she was able to escape unlike her crew.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7ws-f83ae7a1-5208-4141-a221-27e1fae4b810.png/v1/fill/w_1068,h_748,q_70,strp/bonney_pirates_jolly_roger_by_jormxdos_dfgi7ws-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3dzLWY4M2FlN2ExLTUyMDgtNDE0MS1hMjIxLTI3ZTFmYWU0YjgxMC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.EFiLco4LzTLrRR4-pd8QNNnFEqLekvr8nq6y3GrOiCg'), 

('Kid Pirates', 'Kiddo Kaizokudan', true, 'The Kid Pirates are an infamous and notable rookie pirate crew introduced during the Sabaody Archipelago Arc during the time the Straw Hat Pirates arrived there two years ago. As such, they are part of the Worst Generation. Like the Straw Hats, this crew has two bounties above 100,000,000 Beli. Both members had slightly higher bounties than the respective members of the Straw Hat Pirates before the timeskip. Their captain is Eustass Kid.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7v3-b40582d3-e45d-4437-9ce2-f05e69c93722.png/v1/fill/w_1068,h_748,q_70,strp/kid_pirates_jolly_roger_by_jormxdos_dfgi7v3-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3YzLWI0MDU4MmQzLWU0NWQtNDQzNy05Y2UyLWYwNWU2OWM5MzcyMi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.HQa__nqVygwGXlwfPPe_sLow96Mf57V7O5MRejsgNjc'),

('Gyro Pirates', 'Jairo Kaizokudan', true, 'is a pirate crew from South Blue, under captain Gyro.', null),

('Bliking Pirates', 'Burikingu Kaizokudan', true, 'was a pirate crew led by Wapol.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7tz-7add33bc-4652-45ce-91cb-6a8fd2bae758.png/v1/fill/w_1280,h_897,q_80,strp/bliking_pirates_jolly_roger_by_jormxdos_dfgi7tz-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3R6LTdhZGQzM2JjLTQ2NTItNDVjZS05MWNiLTZhOGZkMmJhZTc1OC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.r63P0FPpUjQGBEXdSmbanSk6FGcKtnXZVehmTB0ceEY'),

('Saruyama Alliance', 'Saruyama Rengō-gun', true, 'The Saruyama Alliance (literally meaning "Monkey Mountain Alliance") is a Pirate Alliance that was formed between three pirate captains, Mont Blanc Cricket and his surrogate sons "Salvage King" Masira and his brother "Sonar King" Shoujou. As it is an alliance, it composes of two pirate crews led by the brothers: the Masira Pirates and Shoujou Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7y1-4b23a401-5949-4529-97ca-527d15da33c7.png/v1/fill/w_1068,h_748,q_70,strp/saruyama_alliance_jolly_roger_by_jormxdos_dfgi7y1-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3kxLTRiMjNhNDAxLTU5NDktNDUyOS05N2NhLTUyN2QxNWRhMzNjNy5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.Hd5cOw_sEzQWLekBFQr34tfuaUg_KD6wlGQKCXuWrFQ'),

('Macro Pirates', 'Makuro Ichimi', true, 'The Macro Pirates are a trio of fish-men who are notable for attempting to abduct the mermaid Camie thirty-one times.', null),

('Fallen Monk Pirates', 'Hakaisō Kaizokudan', true, 'The Fallen Monk Pirates are an infamous and notable rookie pirate crew who were first seen on Sabaody Archipelago around the time the Straw Hat Pirates arrived there two years ago. As such, they are part of the Worst Generation, with their captain being Urouge.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7wz-fae80a9c-101b-4c37-bd4d-37be674b9c28.png/v1/fill/w_1280,h_897,q_80,strp/fallen_monk_pirates_jolly_roger_by_jormxdos_dfgi7wz-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3d6LWZhZTgwYTljLTEwMWItNGMzNy1iZDRkLTM3YmU2NzRiOWMyOC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.KgR3ZiaYhDQxQiXXh-nCnCddjXIrE-46c3YV6-3l8YM'),

('On Air Pirates', 'On Ea Kaizokudan', true, 'The On Air Pirates are an infamous and notable rookie pirate crew discovered on the Sabaody Archipelago around the time the Straw Hat Pirates arrived two years ago. As such, they are part of the Worst Generation, with their captain being Scratchmen Apoo. During the timeskip, they became a subordinate crew to the Beasts Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7vv-14cbdce2-9c52-4bdd-a1af-a24c79edad01.png/v1/fill/w_1280,h_897,q_80,strp/on_air_pirates_jolly_roger_by_jormxdos_dfgi7vv-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3Z2LTE0Y2JkY2UyLTljNTItNGJkZC1hMWFmLWEyNGM3OWVkYWQwMS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.QkoLoOgY0REYe8CCDNjJh2c7Jj32_izfTlxRJmNBvqQ'),

('Golden Lion Pirates', 'Kinjishi Kaizokudan', true, 'The Golden Lion Pirates was a pirate crew led by Shiki the Golden Lion. They are the main antagonist group of One Piece: Strong World.', 'https://pbs.twimg.com/media/FA8xmXVVEAUT7f2.png'),

('Candy Pirates', 'Kyandi Kaizokudan', true, 'The Candy Pirates are a crew of pirates who debuted in the cover story CP9''s Independent Report.', null),

('Red Hair Pirates', 'Akagami Kaizoku-dan', true, 'The Red Hair Pirates are an infamous and powerful pirate crew ruling in the New World, captained by their chief, Red-Haired Shanks, one of the Four Emperors and a former apprentice of the Roger Pirates. \n
The Red Hair Pirates are the first pirate crew to appear in the manga and second to appear (next to the Alvida Pirates) in the anime. They are the main influences of both Luffy (he was inspired by Shanks) and Usopp''s (he wants to become a brave warrior of the sea like his father Yasopp) journeys.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7q1-9142c08d-f867-43e1-95b0-c048b8373006.png/v1/fill/w_1280,h_897,q_80,strp/red_hair_pirates_jolly_roger_by_jormxdos_dfgi7q1-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3ExLTkxNDJjMDhkLWY4NjctNDNlMS05NWIwLWMwNDhiODM3MzAwNi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.iBMiqQy-2x9kUStTCplDE0XlF9BcybcGmJdeno3QBcU'),

('Blackbeard Pirates', 'Kurohige Kaizokudan', true, 'The Blackbeard Pirates are an extremely infamous and powerful pirate fleet led by their admiral, Marshall D. Teach, better known as "Blackbeard", one of the Four Emperors and one of the main antagonist groups of the series. \n
Blackbeard was originally a member of the Whitebeard Pirates (and Portgas D. Ace''s subordinate), until he murdered one of his crewmates over a Devil Fruit and defected, heading out to form his own crew. Blackbeard was Crocodile''s replacement among the Seven Warlords of the Sea, having captured the wanted pirate Ace to obtain his position, but resigned after forfeiting the privilege by raiding Impel Down and recruiting several notorious prisoners for his crew from Level 6. \n
During the timeskip, after clashing with the remnants of the Whitebeard Pirates led by Marco the Phoenix and emerging victorious, Blackbeard usurped the status of the deceased Whitebeard as one of the Four Emperors. Following the Rocky Port Incident, the Blackbeard Pirates made Hachinosu their main base.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7q4-d5cdbd5d-9d13-48f9-8905-36a86a7e9ef7.png/v1/fill/w_1068,h_748,q_70,strp/blackbeard_pirates_jolly_roger_by_jormxdos_dfgi7q4-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3E0LWQ1Y2RiZDVkLTlkMTMtNDhmOS04OTA1LTM2YTg2YTdlOWVmNy5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.r6yLjX4gWAqGf_POr04coWXsjTZ-wcRbT8Wf_qVMyHo'),

('Rolling Pirates', 'Rōringu Kaizokudan', true, 'The Rolling Pirates are a group of pirates introduced in the Thriller Bark Arc. They are led by the 23rd daughter of the Charlotte Family, Charlotte Lola. The crew had their own shadows taken away by Gecko Moria, and they aid Luffy in helping him defeat Moria by stuffing as many shadows as they can into him, making him more powerful.', null),

('Maelstrom Spider Pirates', 'Ō Uzu Gumo Kaizokudan', true, 'The Maelstrom Spider Pirates is a pirate crew, led by Squard. It is a subordinate crew of the Whitebeard Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7ou-6a39e709-449e-4f93-911b-4c2cf45fea1c.png/v1/fill/w_1068,h_748,q_70,strp/maelstrom_spider_pirates_jolly_roger_by_jormxdos_dfgi7ou-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN291LTZhMzllNzA5LTQ0OWUtNGY5My05MTFiLTRjMmNmNDVmZWExYy5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.W_4bDECnWucrQIMPfqBeeviUUGKoVCqnGDGczDL6pX4'),

('Little Pirates', 'Ritoru Kaizokudan', true, 'The Little Pirates is a pirate crew led by Little Oars Jr. It is a subordinate crew of the Whitebeard Pirates.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5dACHN3vws0W22T75g9E1YFIntnm1zQWyvIODp2zgcw4spDmzFrvfPoCT_HRNkpTtUxU&usqp=CAU'),

('Sun Pirates', 'Taiyō no Kaizokudan', true, 'The Sun Pirates, sometimes known as the Fish-Man Pirates, are a pirate crew formed by the late Fisher Tiger. The crew is notable for having Jinbe and Arlong as part of its members, the former eventually becoming the second captain of the crew, and later, one of the Seven Warlords of the Sea. This crew split apart into three factions eleven years ago: the Sun Pirates under Jinbe, the Arlong Pirates under Arlong, and the Macro Pirates under Macro. The Sun Pirates were pardoned by the World Government when Jinbe became a Warlord of the Sea, but lost the pardon when he abdicated his title. They later went to serve under Emperor Big Mom until Jinbe rebelled and joined the Straw Hat Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7qy-61f2744b-82fa-4379-b04d-ad53ee3388e5.png/v1/fill/w_1280,h_897,q_80,strp/sun_pirates_jolly_roger_by_jormxdos_dfgi7qy-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3F5LTYxZjI3NDRiLTgyZmEtNDM3OS1iMDRkLWFkNTNlZTMzODhlNS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.lLoc8fOedDU2_M8RpCRRy0JY3xy5mx8lemM6ecA2qpE'),

('Beautiful Pirates', 'Utsukushiki Kaizoku-dan', true, 'The Beautiful Pirates are the first ship of the Straw Hat Grand Fleet, a crew commanded by Cavendish.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7gx-baf06ff2-1b9c-4027-9f2e-6653ab33dad4.png/v1/fill/w_1068,h_748,q_70,strp/beautiful_pirates_jolly_roger_by_jormxdos_dfgi7gx-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2d4LWJhZjA2ZmYyLTFiOWMtNDAyNy05ZjJlLTY2NTNhYjMzZGFkNC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.bEiwof9jV3dNiel37q58Hehjn2eIOO55drGxknDioBk'),

('A O Pirates', 'Ā Ō Kaizokudan', true, 'The A O Pirates[2] are a pirate crew led by A O. They were a subordinate crew of the Whitebeard Pirates prior to Whitebeard''s death.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7om-91196265-8079-4c16-9458-ea02eb3954e6.png/v1/fill/w_1068,h_748,q_70,strp/a_o_pirates_jolly_roger_by_jormxdos_dfgi7om-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN29tLTkxMTk2MjY1LTgwNzktNGMxNi05NDU4LWVhMDJlYjM5NTRlNi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.UD_en_LASBFAtVlnot3-JsKAvfzzoSua3LXVn9g4Lwc'),

('Takotopus Pirates', 'Takotopasu Kaizokudan', true, 'The Takotopus Pirates are a pirate crew led by Karma. They were a subordinate crew of the Whitebeard Pirates prior to Whitebeard''s death.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7p3-e5dc4f97-17a1-494a-85df-0a6ec2a787af.png/v1/fill/w_1068,h_748,q_70,strp/takotopus_pirates_jolly_roger_by_jormxdos_dfgi7p3-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3AzLWU1ZGM0Zjk3LTE3YTEtNDk0YS04NWRmLTBhNmVjMmE3ODdhZi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.VRjn2F9nveUUareY31vODphBE3crVX8W2zlQXkudtRE' ),

('Ideo Pirates', 'Ideo Kaizokudan', true, 'The Ideo Pirates, formerly known as the XXX Gym Martial Arts Alliance (pronounced "Triple X Gym Martial Arts Alliance") is a pirate crew led by Ideo and the fourth ship of the Straw Hat Grand Fleet. \n
The crew''s four members were allies of Luffy during the Dressrosa Arc. They also are one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7hw-f91d25b7-77b5-4252-9792-fac147f5c61f.png/v1/fill/w_1280,h_897,q_80,strp/ideo_pirates_jolly_roger_by_jormxdos_dfgi7hw-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2h3LWY5MWQyNWI3LTc3YjUtNDI1Mi05NzkyLWZhYzE0N2Y1YzYxZi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.PKLYCxGCTF_5UUaEP8H74GkPDMej3Mjjlja6Q6UkEac'),

('Tontatta Pirates', 'Tontatta Kaizokudan', true, 'The Tontatta Pirates, formerly known as Tonta Corps, are the armed forces of the Tontatta Tribe formed in order to commence Operation SOP, and later, reformed as a pirate crew. They are composed of 200 dwarves under the command of Leo, forming the fifth ship of the Straw Hat Grand Fleet. \n
They are allies of the Straw Hat Pirates during the Dressrosa Arc, and also one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7i5-27fa1144-b95b-4ce3-9aa5-cee8c689eded.png/v1/fill/w_1068,h_748,q_70,strp/tontatta_pirates_jolly_roger_by_jormxdos_dfgi7i5-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2k1LTI3ZmExMTQ0LWI5NWItNGNlMy05YWE1LWNlZThjNjg5ZWRlZC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.RIvZp-NorWrHJgw2_r_TI37rjxlgFaa5lbJ79aNz9aE' ),

('New Giant Warrior Pirates', 'Shin Kyo Hei Kaizoku-dan', true, 'The New Giant Warrior Pirates are a pirate crew of Giants led by Hajrudin. The crew is a spiritual revival of the Giant Warrior Pirates that disbanded 100 years ago. They were once part of Buggy''s Delivery, before leaving to become the sixth ship of the Straw Hat Grand Fleet after the events on Dressrosa. \n
They also are one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7rq-afe5a48b-00b8-4607-8134-4eb69e3c0e9f.png/v1/fill/w_1280,h_897,q_80,strp/giant_warrior_pirates_jolly_roger_by_jormxdos_dfgi7rq-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3JxLWFmZTVhNDhiLTAwYjgtNDYwNy04MTM0LTRlYjY5ZTNjMGU5Zi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.e15fI36uw80Tebe_9Ijk4iboVuTJ1eJgRMPnBVTnM3Q'),

('Yonta Maria Grand Fleet', 'Yonta Maria Dai-sendan', true, 'The Yonta Maria Grand Fleet is a group of 56 ships led by Orlumbus. It shares its name with its flagship, the Yonta Maria. After the defeat of Doflamingo, the flagship became the seventh ship of the Straw Hat Grand Fleet[3][4] and with it the entire Yonta Maria Grand Fleet. \n
They also are one of the central characters from The Stories of the Self-Proclaimed Straw Hat Grand Fleet Cover Page Serial.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7il-94a51a8b-963a-45c0-a3b6-9b39bf4421a4.png/v1/fill/w_1280,h_897,q_80,strp/yonta_maria_grand_fleet_jolly_roger_by_jormxdos_dfgi7il-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2lsLTk0YTUxYThiLTk2M2EtNDVjMC1hM2I2LTliMzliZjQ0MjFhNC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.evcVFvN1Df3QQjPeeIDUGEE1Fx6Eejlk03Nq2q6r-b8'),

('Big Mom Pirates', 'Biggu Mamu Kaizokudan', true, 'The Big Mom Pirates are an extremely infamous and powerful pirate crew led by their captain, Charlotte Linlin, better known as "Big Mom", formerly one of the Four Emperors. They are in control of the powerful nation of Totto Land, with their captain ruling it as its queen and their base of operations being Whole Cake Island, the country''s main island. The captain agreed to an alliance with the Beasts Pirates for plans to take over the world. However, the captain was defeated during the Raid on Onigashima by two members of the Worst Generation, and she was subsequently stripped of her position as an Emperor, leaving the crew''s status unknown. \n
Due to their actions and role, they are the main antagonists of the Whole Cake Island Arc and one of the central antagonist groups of the Whole Cake Island Saga.', 'https://res.cloudinary.com/zenbusiness/image/upload/v1670445040/logaster/logaster-2022-07-big-mom.jpg'),

('Peachbeard Pirates', 'Momohige Kaizokudan', true, 'The Peachbeard Pirates is a pirate crew under captain Peachbeard that affiliated themselves with the Blackbeard Pirates.', null),

('Kuja Pirates', 'Kuja Kaizokudan', true, 'The Kuja Pirates (literally meaning "Nine Snakes Pirates") is a crew of female pirates from Amazon Lily. All of the crew members are women chosen from the Kuja tribe of their homeland. Their captain is the Empress of the Kuja tribe, as well as the former member of the Seven Warlords of the Sea, Boa Hancock. Second in command are Hancock''s younger sisters, Boa Sandersonia and Boa Marigold. \n
Though only the elite warriors of the tribe were selected to be members of the Kuja Pirates crew, every member of the Kuja tribe has been classified as a pirate by the World Government whether they are an islander or an actual pirate.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-kuja-pirates.png'),

('Roger Pirates', 'Rojā Kaizokudan', true, 'The Roger Pirates were the pirate crew of the late Pirate King, Gol D. Roger. They were, and still are, the only known crew to ever reach Laugh Tale, the end of the New World in the Grand Line. They encountered Vice Admiral Garp on several occasions and were strong rivals to the Whitebeard Pirates. \n
This was the crew that traveled around the Grand Line together and the things they did were part of legends. They made it as far as Skypiea and the end of the Grand Line, Laugh Tale, on their ship, the Oro Jackson. Roger was the most famous figure of his era, while the names of his first mate, Silvers Rayleigh, and rival Edward Newgate is widely known and famed as well. \n
The first introduction to their crew comes from Buggy, who recalls his days with Shanks as apprentices in their crew. Their captain, Roger, is the first character introduced in the series.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-roger-pirates.jpg'),

('Alvida Pirates', 'Arubida Kaizokudan', true, 'The Alvida Pirates were a group of pirates led by the female pirate "Iron Mace" Alvida. They were the first enemy pirates Luffy was seen to encounter. The crew has since dissolved into an alliance with the Buggy Pirates, forming the Buggy and Alvida Alliance, which later becomes the Pirate Dispatch Organization known as Buggy''s Delivery. They are one of the antagonist groups in the Romance Dawn Arc.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7sp-d69cc963-e804-4445-8abd-1506809375f6.png/v1/fill/w_1280,h_897,q_80,strp/alvida_pirates_jolly_roger_by_jormxdos_dfgi7sp-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3NwLWQ2OWNjOTYzLWU4MDQtNDQ0NS04YWJkLTE1MDY4MDkzNzVmNi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.rA_YF4sjVjaxwbETYdH8E2Y7tb-yGU-zT3nLymm7BT8'),

('Giant Warrior Pirates', 'Kyo Hei Kaizoku-dan', true, 'The Giant Warrior Pirates were a pirate crew made up of giants from Elbaf lead by Dorry and Brogy. Before them, the crew''s captains were Jarul and Jorul. They disbanded 102 years ago when Dorry and Brogy began their duel. \n
Currently, Hajrudin leads a spiritual revival crew, the New Giant Warrior Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7rq-afe5a48b-00b8-4607-8134-4eb69e3c0e9f.png/v1/fill/w_1280,h_897,q_80,strp/giant_warrior_pirates_jolly_roger_by_jormxdos_dfgi7rq-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3JxLWFmZTVhNDhiLTAwYjgtNDYwNy04MTM0LTRlYjY5ZTNjMGU5Zi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.e15fI36uw80Tebe_9Ijk4iboVuTJ1eJgRMPnBVTnM3Q'),

('Whitebeard Pirates', 'Shirohige Kaizokudan', true, 'The Whitebeard Pirates were once one of the strongest pirate crews in the world, as their late captain, Edward Newgate, better known as Whitebeard, was one of the Four Emperors and the only man to have ever been a match for the Pirate King, Gol D. Roger, in a fight. Whitebeard''s crew was segmented into divisions, instead of all under their captain''s direct command. The crew had multiple subordinate crews operating in the New World, allowing the pirate crew to function as a massive pirate fleet. \n
Following the deaths of Whitebeard and Ace, the remaining members of the crew engaged the Blackbeard Pirates'' full forces in the Payback War, which ended with the Blackbeard Pirates brutally defeating them, followed by conquering their former territories, with their admiral usurping Whitebeard''s position in the Four Emperors. As a result, the crew had lost most of its power and influence, and they disbanded. \n
After the timeskip, the remaining crew members and subordinate crews are being hunted down by Edward Weevil and his mother Bakkin, who proclaim themselves as their captain''s biological son and lover, to gain his fortune. Marco and Izou however, supported the Ninja-Pirate-Mink-Samurai Alliance in their raid against a then-Emperor crew, which succeeded, resulted in one of the alliance leader became one of the Four Emperors.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7lv-e65fcee1-6c84-4990-bec1-910439f700c0.png/v1/fill/w_1280,h_897,q_80,strp/whitebeard_pirates_jolly_roger_by_jormxdos_dfgi7lv-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2x2LWU2NWZjZWUxLTZjODQtNDk5MC1iZWMxLTkxMDQzOWY3MDBjMC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.3umuFB2cLR30Jr3Gkan2JLcoHEG3pnfb_BgxaIA3Lsg' ),

('Brownbeard Pirates', 'Chahige Kaizokudan', true, 'The Brownbeard Pirates were a pirate crew in the New World headed by Chadros Higelyges, better known as "Brownbeard".', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7yr-0ea596f9-a8b2-4d86-b6d4-2d8f28a8e37f.png/v1/fill/w_1280,h_897,q_80,strp/brownbeard_pirates_jolly_roger_by_jormxdos_dfgi7yr-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3lyLTBlYTU5NmY5LWE4YjItNGQ4Ni1iNmQ0LTJkOGYyOGE4ZTM3Zi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.wM9SWwjyzWKYTC_nOTkmzOUwlFvmERzIKHwrdB_Djn0'), 

('Fake Straw Hat Crew', 'Nise Mugiwara no Ichimi', true, 'The Fake Straw Hat Crew was a group of pirates that attempted to impersonate the real Straw Hat Pirates in order to benefit from their reputation. They first appeared after the two year time skip[1] and disbanded when the truth about the impostors was revealed. The recruits were arrested by the Marines except for Albion and the Caribou Pirates, who escaped, while the members of the Fake Straw Hat Crew were either captured or buried alive by the Caribou Pirates.', null),

('New Fish-Man Pirates', 'Shin Gyojin Kaizoku-dan', true, 'The New Fish-Man Pirates were a pirate crew led by Hody Jones. The crew was comprised almost entirely of fish-men residing on Fish-Man Island, though they also included several merfolk, sea beasts, and enslaved humans. The New Fish-Man Pirates were the most prominent figures in the long history of human/fish-men hate over their hero Fisher Tiger''s death. They carried on the legacy of Arlong, having established their crew based on Arlong''s ideals. Like Arlong, they wished to make fish-men the supreme race and aimed to sink the humans into the ocean. Due to their actions and role, they are the main antagonists of the Fish-Man Island Arc. \n
Following their defeat at the hands of the Straw Hat Pirates and the arrest of their captain and officers, the New Fish-Man Pirates are no longer active. The remaining crew members were allowed to live on the mainland of Fish-Man Island under the supervision of the Royal Army while their human slaves were freed and allowed to leave the island.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7ui-e3470589-cd41-44f0-8cdf-b4423237ea5f.png/v1/fill/w_1280,h_897,q_80,strp/new_fishman_pirates_jolly_roger_by_jormxdos_dfgi7ui-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3VpLWUzNDcwNTg5LWNkNDEtNDRmMC04Y2RmLWI0NDIzMjM3ZWE1Zi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.WUR_u2LT8AXWHyLXH8JRpXbK0akEU_kmaMEMdD6SI3k'), 

('Flying Pirates', 'Furaingu Kaizokudan', true, 'The Flying Pirates were a pirate crew led by Vander Decken IX, floating over the ocean floor and endangering the citizens of Fish-Man Island. The crew is possibly named after the flagship used by Vander Deckens for nine generations, the Flying Dutchman. The captains of the Flying Pirates and the New Fish-Man Pirates had sworn an alliance with each other before the captains betrayed one another. Upon Decken''s arrest and imprisonment, the crew''s status is currently unknown. They are the secondary antagonist group in the Fish-Man Island Arc.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7xp-2beba9d3-5c3f-463c-998b-a775545f649f.png/v1/fill/w_1068,h_748,q_70,strp/flying_pirates_jolly_roger_by_jormxdos_dfgi7xp-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3hwLTJiZWJhOWQzLTVjM2YtNDYzYy05OThiLWE3NzU1NDVmNjQ5Zi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.B7K4D2U5F9D4FjdK_wbcOu48RDtQChZluq55saDat6E'),

('Bellamy Pirates', 'Beramī Kaizokudan', true, 'The Bellamy Pirates were a former pirate crew that was based in Jaya on the Grand Line, once led by Bellamy the Hyena. They originated from the North Blue. They are the main antagonist group in the Jaya Arc.', 'https://res.cloudinary.com/zenbusiness/q_auto/v1/logaster/logaster-2022-07-bellamy-pirates-1.png'),

('Nox Pirates', 'Nokkusu Kaizokudan', true, 'The Nox Pirates, initially known as the Nox Expedition Party,was a pirate crew of minks led by Pedro. They initially set sail from Zou as explorers with the intention of finding poneglyphs, but were chased by the World Government and ended up receiving bounties. The crew was defeated in Totto Land five years ago, causing it to be disbanded.', null),

('Rocks Pirates', 'Rokkusu Kaizokudan', true, 'The Rocks Pirates were a legendary and powerful pirate crew that sailed the seas until their defeat 38 years before the current storyline. \n
They were led by Rocks D. Xebec and considered to be the most dangerous and strongest pirate crew of their time. They ruled the seas before the rise of Gol D. Roger and his crew.', null),

('Arlong Pirates', 'Āron Ichimi', true, 'The Arlong Pirates were a pirate crew led by Arlong. Every member of the crew was a fish-man, except for Nami (who later left). They existed before the Sun Pirates but joined with them when they were formed. After the death of Fisher Tiger, they split from Jinbe''s crew after he became a Warlord and became their own crew once again. They believed they were above humans as the stronger species and looked down on them as inferior. After they were defeated, they were arrested. Due to their actions and role, they are the main antagonists of the Arlong Park Arc. After their leader''s defeat by the Straw Hats, they are arrested and the crew itself is disbanded. Momoo was never taken into custody and Hatchan later escaped.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7tq-86c29c76-4cc8-4e53-9283-cb39a63b2856.png/v1/fill/w_1068,h_748,q_70,strp/arlong_pirates_jolly_roger_by_jormxdos_dfgi7tq-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3RxLTg2YzI5Yzc2LTRjYzgtNGU1My05MjgzLWNiMzlhNjNiMjg1Ni5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.9aJgvWZUdeaBf-RDae9doTMVLXVSlCo86LawblBz-u0'), 

('Tulip Pirates', 'Chūrippu Kaizokudan', true, 'The Tulip Pirates are a group of pirates that appeared in Jango''s cover story.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7xw-d8bfd502-aca5-4b32-8ca5-dfac8e43e396.png/v1/fill/w_1280,h_897,q_80,strp/tulip_pirates_jolly_roger_by_jormxdos_dfgi7xw-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3h3LWQ4YmZkNTAyLWFjYTUtNGIzMi04Y2E1LWRmYWM4ZTQzZTM5Ni5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.feDNQvyw6pjaLxJ51An0LB6m3FjK3oY79ORUs9K3MV0'),

('Donquixote Pirates', 'Donkihōte Kaizoku-dan', true, 'The Donquixote Pirates, also known as the Donquixote Family, was a powerful pirate crew led by the former Warlord, Donquixote Doflamingo. They used to rule the kingdom of Dressrosa as the governing body, with their captain as the king. Due to their actions and role, they are the main antagonists of the Dressrosa Arc and the Dressrosa Saga as a whole. \n
The crew is now disbanded after Doflamingo and the other higher-ups'' defeat at the hands of the Straw Hat Pirates-Heart Pirates alliance, resulting in Doflamingo being dethroned as king and his title of a Warlord of the Sea being stripped from him. Most of the high-ranking members were arrested by Admiral Fujitora.', 'https://res.cloudinary.com/zenbusiness/image/upload/v1670445040/logaster/logaster-2022-07-donquixote-pirates.jpg' ),

('Beasts Pirates', 'Hyakujū Kaizokudan', true, 'The Beasts Pirates are an extremely infamous and powerful pirate crew led by their governor-general, Kaidou, formerly one of the Four Emperors. They were based in Wano Country, specifically headquartered on Onigashima. \n

For the past 25 years, the Beast Pirates consolidated their power in Wano, which they occupied through an alliance with the country''s shogun, Kurozumi Orochi. Over the past two years, the crew partnered with Donquixote Doflamingo and Caesar Clown to create artificial Zoan Devil Fruits called SMILE Fruits, leading to the crew having over 500 users with Devil Fruit powers. After the Ninja-Pirate-Mink-Samurai Alliance captured Caesar, destroyed the SMILE Factory and defeated Doflamingo, Kaidou turned to a new alliance with the Big Mom Pirates. The two Emperors'' alliance planned to conquer the world by obtaining the Ancient Weapons and the One Piece. Part of this plan is Kaidou''s "New Onigashima Project", which sought to replace Orochi as shogun with Yamato during the latest Fire Festival. This scheme ultimately failed, as during the Raid on Onigashima, all their top officers, alongside his fellow Emperor Big Mom, were defeated one after another by the Ninja-Pirate-Mink-Samurai Alliance and Kaidou himself was defeated by Monkey D. Luffy, captain of the Straw Hat Pirates.[10] After the battle, Kaidou was sent flying down into an underground magma chamber and was caught in a massive volcanic explosion, while the fates of the remaining members are unclear. \n
As a result, Kaidou was no longer considered as one of the Four Emperors following the announcement of his defeat, leaving the overall status of the Beasts Pirates unknown. \n
Due to their actions and role, they are the main antagonists of the Zou Arc and Wano Country Arc, and one of the central antagonist groups of the Whole Cake Island Saga and Wano Country Saga.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7pg-ff1cc14d-b6e7-4258-a8ab-d6ef3b2e8ddd.png/v1/fill/w_1068,h_748,q_70,strp/beasts_pirates_jolly_roger_by_jormxdos_dfgi7pg-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3BnLWZmMWNjMTRkLWI2ZTctNDI1OC1hOGFiLWQ2ZWYzYjJlOGRkZC5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.wOMP0iFoZrHe-ZJnoITI_LFYBbxNkIMdjVY518cKcNQ' ),

('Spade Pirates', 'Supēdo Kaizokudan', true, 'The Spade Pirates was the former pirate crew of Portgas D. Ace that was founded five years before the current storyline. The crew later disbanded when its members integrated into the Whitebeard Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7m2-cd790745-2799-42b7-bf9b-5b6edb6a993e.png/v1/fill/w_1068,h_748,q_70,strp/spade_pirates_jolly_roger_by_jormxdos_dfgi7m2-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN20yLWNkNzkwNzQ1LTI3OTktNDJiNy1iZjliLTViNmVkYjZhOTkzZS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.6R_NWFK_r5Xt0IwAQhX8Y1phZP1SQGnFVqSNmGYwwA4'), 

('Sasaki Pirates', 'Sasaki Kaizokudan', true, 'The Sasaki Pirates were a pirate crew originating from the Grand Line that was once captained by Sasaki before he joined the Beasts Pirates. Given that the crew originated from the Grand Line and was led by someone who became a top officer in an Emperor-led crew, it can be assumed that the Sasaki Pirates were a formidable crew in its own right. However, details on their overall power are not known.', null ),

('Who''s-Who Pirates', 'Fūzu Fū Kaizokudan', true, 'The Who''s-Who Pirates were a pirate crew that was once captained by Who''s-Who before he joined the Beasts Pirates. Currently the only known member is the captain Who''s-Who. Given that the crew was led by someone who was once among the strongest members of CP9 and then became one of the top officers of the Emperor-led Beasts Pirates, it can be assumed that the Who''s-Who Pirates were formidable. However, nothing is known about their overall strength in detail.', null),

('Cook Pirates', 'Kukku Kaizokudan', true, 'The Cook Pirates was Zeff''s old pirate crew. The crew''s ship was the Cooking George. Their pirates flag symbol was a duck wearing a chef hat and the knife and fork replaced the crossbones. They had a general rule that they would never steal food from their targets, no matter what the situation was; Zeff brutally kicked any crew members who dare break this rule. While the crew laughed at the idea of All Blue, Zeff alone believed in it.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7j0-9e833b96-d265-4552-96a3-0f630755c0c5.png/v1/fill/w_1068,h_748,q_70,strp/cook_pirates_jolly_roger_by_jormxdos_dfgi7j0-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN2owLTllODMzYjk2LWQyNjUtNDU1Mi05NmEzLTBmNjMwNzU1YzBjNS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.ys8xJdhtjAo2o8ldiB-QFRAlVYKdS-5vngppJSet8pI' ),

('Rumbar Pirates', 'Runbā Kaizokudan', true, 'The Rumbar Pirates are a long dead pirate crew from the West Blue. They were first mentioned by Crocus as the group of pirates who brought Laboon to the Twin Capes.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/680bb227-0c56-4551-9057-05acdfa8ecbe/d5db1vf-1c0c8bd1-87d9-4f75-a65e-88c0a90eb22c.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzY4MGJiMjI3LTBjNTYtNDU1MS05MDU3LTA1YWNkZmE4ZWNiZVwvZDVkYjF2Zi0xYzBjOGJkMS04N2Q5LTRmNzUtYTY1ZS04OGMwYTkwZWIyMmMuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.7Uk4kRc0PgtGK4lkXDIrBue7q3rg4PvD-nQUQHDs9TM' ),

('Eraser Pirates', 'Ireizā Kaizokudan', true, 'The Eraser Pirates were a crew of pirates. They were attacked by Wyper when they entered Skypiea.', null ),

('Barrels Pirates', 'Bareruzu Kaizokudan', true, 'The Barrels Pirates was a pirate crew led by Diez Barrels. The crew possessed enough strength to somehow acquire the Ope Ope no Mi, but not wishing to use its power (apparently not knowing its ultimate ability to grant eternal life), they intended to sell it for 5,000,000,000 belis. However, they were incapable of keeping it from being stolen by Donquixote Rosinante, and they were nowhere near strong enough to challenge Doflamingo and his crew, leaving them at the complete mercy of the mighty broker. Barrels'' son, Dory was noted by his father to be the strongest member of the crew, but weak in fortitude, and was the only one lucky enough to escape while his former crew was trapped and slaughtered by Doflamingo.', null),

('Gecko Pirates', 'Gekkō Kaizokudan', true, 'The Gecko Pirates were the former pirate crew of Gecko Moria. According to Moria, his subordinates were greatly renowned and skilled. Moria himself was said to have been powerful enough to compete against Kaidou. However, the crew eventually suffered a complete defeat at the hands of Kaidou and his crew. Moria later came to blame the loss on his crew''s mortality.', null),

('Roshio Pirates', 'Roshio Kaizoku-dan', true, 'The Roshio Pirates were a group of pirates led by Roshio. With his death, the fate of the crew is unknown.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/No_flag.svg/225px-No_flag.svg.png6' ),

('Hokahoka Pirates', 'Hokahoka Kaizokudan', true, 'It can presumed the Hokahoka Pirates were quite strong, as they managed to travel to Jaya. They were on Jaya at the same time as the Straw Hat Pirates. Nothing else is known about this crew' , null ),

('Fanged Toad Pirates', 'Kiba Gaeru Kaizokudan', false, 'The Fanged Toad Pirates were a crew from Paradise. In their first encounter with the Straw Hat Pirates, the crew''s ship had no flag, helmsman, navigator or even a captain, and were in a panic when confronting the Straw Hats, then met their fate against the sea monkeys.It was revealed that the reason why they were in such a state when the Straw Hats saw them was because they lost five matches against Foxy and his crew in the Davy Back Fight. All the core crew members were taken and made part of Foxy''s crew.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7y9-e304d87c-f192-4983-9884-c5862bb96a4b.png/v1/fill/w_1068,h_748,q_70,strp/fanged_toad_pirates_jolly_roger_by_jormxdos_dfgi7y9-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3k5LWUzMDRkODdjLWYxOTItNDk4My05ODg0LWM1ODYyYmI5NmE0Yi5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.u2sNnm3OpxV3decjrFS7NUWudT3TIid0HNNHNMt2Mkg'), 

('Big Helmet Pirates', 'Ō Kabuto Kaizokudan', true, 'The Big Helmet Pirates is a pirate band led by Mikazuki. \n
The pirate crew came is introduced during Water 7, when their ship was being repaired by the Galley-La Company, but chose to not pay for the ship due to the price of the work being too high. For intimidating the various workers (including Paulie, Kaku, Peepley Lulu and Rob Lucci), Mikazuki and his entire crew were crushed by the power of the carpenters.', null),


('Akumate Pirates', 'Akumeito Kaizokudan', true, 'The Acumate Pirates are a group of pirates from an unknown region, under the captaincy of Devil Dias.\n 
Under Dias, a pirate with a bounty of 60,000,000 beli''s, the crew planned to head to the New World.\n
However, Dias was captured and sold into slavery to Saint Rosward on Sabaody Archipelago. Dias eventually attempted to escape, only to have the bomb within his collar shackle detonate and his body was dragged off by the Marines.\n
The crew''s fate is unknown due to the capture of their captain, but Sentomaru noted that Dias was not prepared for the New World due to his low caliber.', null),

('Space Pirates', 'Uchū Kaizoku', true, 'The Space Pirates are a pirate crew of aliens originating from outer space. They are moon miners that mine anything they can find.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e8ddc4da-23dd-4502-b65b-378c9cfe5efa/dfgi7yf-b60c0659-0663-4657-b795-b80a6520b887.png/v1/fill/w_1280,h_897,q_80,strp/space_pirates_jolly_roger_by_jormxdos_dfgi7yf-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9ODk3IiwicGF0aCI6IlwvZlwvZThkZGM0ZGEtMjNkZC00NTAyLWI2NWItMzc4YzljZmU1ZWZhXC9kZmdpN3lmLWI2MGMwNjU5LTA2NjMtNDY1Ny1iNzk1LWI4MGE2NTIwYjg4Ny5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.BV2ztoKNHCDAcvJmnRISlEbLmu6hQE3gdNImHkcJ69Y'),

('Niho Navy', 'Nihō Suigun', true, 'The Niho Navy is a pirate crew led by Chichilisia that planned to join forces with the Happo Navy until Sai called off his engagement. At some point, a marriage between the daughter of the Niho Navy''s leader, Uholisia, and Sai was arranged in order to create an alliance with the Happo Navy.', null),

('Germ Pirates', 'Baikin Kaizokudan', true, 'The Germ Pirates are a crew of pirates who debuted in the cover story ''Gang'' Bege''s Oh My Family. They possess a type of infection, known as the Kiss-Kiss Germ, that causes those who are infected to want to kiss those around them, spreading the virus.',null),

('Usopp Pirates', 'Usoppu Kaizokudan', true, 'The Usopp Pirates was a group of children who pretended to be pirates in Syrup Village. It was formerly led by Usopp until he chose to join the Straw Hat Pirates.', 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/669dbabb-d4c5-4170-bbe6-1fffd7b4bb09/d18uflg-937ab7b0-bb00-4551-9491-d1aeae372902.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzY2OWRiYWJiLWQ0YzUtNDE3MC1iYmU2LTFmZmZkN2I0YmIwOVwvZDE4dWZsZy05MzdhYjdiMC1iYjAwLTQ1NTEtOTQ5MS1kMWFlYWUzNzI5MDIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.KB9PAICWmCsV_xQpSgJnmGi7wJjt1LR7F4vyPdeJO7o'),

('Pumpkin Pirates', 'Panpukin Kaizokudan', false, 'The Pumpkin Pirates were an anime-only group of children who pretended to be pirates that lived on Ruluka island 50 years ago. \n
They were allies of the Straw Hat Pirates during the Ruluka Island Arc.', null );
