INSERT INTO all_Characters ( name, alive, info, canon, pirate, marine, photo, devil_fruitID, pirate_groupID, marine_RanksID ) VALUES 

('AO', 'A O is an infamous New World pirate and captain of the A O Pirates. He and his crew were subordinates to Whitebeard. A O is a very tall man with a long, square shaped face, hollow eyes under prominent eyebrows, dark sideburns that go all the way down to his chin, and greenish long wavy hair. On his head, he wears a yellow and brown striped bandanna and over it is a tricorn captain''s hat with what appears to be his Jolly Roger on it, a white skull wearing an animal-like hood. He also wears a dark blue, open shirt with the sleeves rolled up and a ruffled collar, and elaborate earrings made up by three little jewels each on both ears. Not much is known about A O''s personality other than that he is very loyal to Whitebeard since he was willing to risk his own life to save Ace from execution instead of fleeing through the path he had cleared with his power. He was overjoyed when Luffy saved Ace, cheering with his fellow allies.',true, true, false, 'https://static.wikia.nocookie.net/onepiece/images/8/8c/A_O_Anime_Infobox.png/revision/latest?cb=20160102105316', null, 36, null), 

('Abdullah', true, 'Abdullah is a criminal and a former bounty hunter who joined as a gladiator at the Corrida Colosseum to compete for the Mera Mera no Mi, along with his partner Jeet. He is an ally of Luffy during the Dressrosa Arc. After the battle with the Donquixote Pirates at Dressrosa, he joined the XXX Gym Martial Arts Alliance, which later converted to a pirate crew called the Ideo Pirates.',true, true, false, 'https://static.wikia.nocookie.net/onepiece/images/…/latest/scale-to-width-down/700?cb=20151004140309', null, 38, null),

('Absalom', false, 'Absalom of the Graveyard was the leader of the Zombie Soldiers and Zombie Generals of Thriller Bark prior to its collapse. He was one of the Mysterious Four of the Thriller Bark Pirates and one of the major antagonists of the Thriller Bark Saga. \n
Sometime during the timeskip, he became a reporter under the alias Absa. At some point, he was abducted by the Blackbeard Pirates and killed to poach his Devil Fruit powers, with his ability going to Shiryu.', true, true, false, 'https://static.wikia.nocookie.net/onepiece/images/…/latest/scale-to-width-down/699?cb=20230101154942', 24, 9, null), 

('Acilia', true, 'Acilia is a gladiator at the Corrida Colosseum who participated in a tournament for the Mera Mera no Mi. She is a large and bulky woman. Has dark colored lipstick, and dark colored hair. She is seen with a jolly smile, and sports an armored helmet', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/0/0c/Acilia_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20180527001719', null, null, null),

('Adele', true, 'Adele is a mermaid and an employee at the Mermaid Café. She is a youthful mermaid with beautiful curly hair that reaches past her shoulders, and has dark skin and pink lipstick. She wears a bikini top with a leopard skin pattern, and her tail is red in color with several zig-zag patterns all of which is being different hues of red themselves.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/d/dd/Adele_Anime_Infobox.png/revision/latest?cb=20130210042308', null, null, null), 

('Aggie 68', true, 'Aggie 68 is a member of the Spade Pirates. Aggie 68''s abilities are unknown, but he and his crew were easily defeated by Newgate. He has been seen with a revolver-like gun attached to his wrist, but it is unknown how skilled he is in using it.', true, true, false, 'https://i.pinimg.com/originals/3a/8e/c4/3a8ec497882b626f807160b38177d96d.jpg', null, 60, null),

('Agotogi', true, 'Agotogi was the leader of a gang of bandits who tried to kidnap Vivi about 11 years before the princess''s return to Arabasta.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/8/8b/Agotogi_Anime_Infobox.png/revision/latest?cb=20130919224447', null, null, null),

('Agsilly', true, 'Agsilly is a New World pirate who allied himself with the Whitebeard Pirates. He seemed to be loyal to his alliance with the Whitebeard Pirates, willing to fight in the war at Marineford in order to rescue Ace from execution, but his full power has not yet been shown.', true, true, false, 'https://static.wikia.nocookie.net/onepiece/images/e/e8/Agsilly_Anime_Infobox.png/revision/latest?cb=20130810194016', null, 48, null)

('Agyo', true, 'Agyo is a fighting lion and a gladiator competing at the Corrida Colosseum for the Mera Mera no Mi.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/1/11/Agyo_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20140707173009', null, null, null),

('Ahho Desunen IX', true, 'Ahho Desunen IX is a noble from the Goa Kingdom and the father of Ahho Zurako. Typical for a corrupted noble, Desunen is cruel and self-centered, as he believes that those who are not nobles are trash', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/5/5f/Ahho_Desunen_IX_Anime_Infobox.png/revision/latest?cb=20130114035654', null, null, null),

('Ahho Zurako', true, 'Ahho Zurako is a noble from the Goa Kingdom and the daughter of Ahho Desunen IX. As a noble raised by a corrupted and spoiled parent, Zurako considers all people who are not nobles trash. She states that being burnt is their fault for not being born nobles.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/b/b2/Ahho_Zurako_Anime_Infobox.png/revision/latest?cb=20180417213414', null, null, null),

('Ahiru', true, 'Ahiru is the Deputy Commander of the East Army in the Revolutionary Army and the assistant of Belo Betty. Ahiru is a woman with tanned skin, prominent lips and long brown hair. Her left arm is a mechanical prosthesis with light and dark green (gray in the manga) coloring. She wears a black shirt, a red tie and a green jacket. She also has a pair of goggles on her head.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/f/f1/Ahiru_Anime_Infobox.png/revision/latest?cb=20190703102730', null, null, null),

('Aisa', true, 'Aisa is a young Shandia girl who used to sneak onto the Upper Yard frequently to collect Vearth. She is Isa''s daughter. Ever since she was born, she had the ability known as "Mantra". Because of this, she hates it when people die and will try anything to stop it, even rushing into danger without any plans on what to do. Aisa wants to be a strong fighter like everyone else and was originally afraid of Wyper, though she warmed up to him eventually. Aisa is also a bit of a tomboy as she reacted with disgust when Raki suggested she grow her hair longer because it would look cute on her.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/4/45/Aisa_Anime_Pre_Timeskip_Infobox.png/revision/latest/scale-to-width-down/393?cb=20220403074416', null, null, null),

('Akehende', true, 'Akehende is a Marine Rear Admiral. Like many other Marines, he considers pirates as nuisances to be eliminated.', true, false, true, 'https://static.wikia.nocookie.net/onepiece/images/e/e8/Akehende_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20190511072409', null, null, 4),

('Akudai Kanzaburo', true, 'Akudai Kanzaburo is an arms dealer who lives in the Flower Capital of Wano Country. Kanzaburo's skills as an arms dealer effectively earned him an invite to the shogun's banquet.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/5/56/Akudai_Kanzaburo_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20210905202949', null, null, 4),

('Akumai', true, 'Akumai was a Billions agent who followed Mr. 2 Bon Kurei everywhere before he was captured by Hina when Mr. 2 and his crew sacrificed themselves to save the Straw Hat Pirates. Not much of Akumai''s skills or power is ever shown. His only fights are unseen for the most part. His current fate is unknown.', true, false, false, 'https://static.wikia.nocookie.net/onepiece/images/4/48/Akumai_Anime_Infobox.png/revision/latest?cb=20130626054008', null, null, null), 



-- name, alive, info, canon, pirate, navy, photo, devil_fruitID, pirate_groupID, marine_RanksID