\c one_piece_dev;

INSERT INTO all_Characters ( name, alive, info, canon, pirate, marine, other, photo, devil_fruitID, pirate_groupID, marine_RanksID ) VALUES 

('AO', null , 'A O is an infamous New World pirate and captain of the A O Pirates. He and his crew were subordinates to Whitebeard. A O is a very tall man with a long, square shaped face, hollow eyes under prominent eyebrows, dark sideburns that go all the way down to his chin, and greenish long wavy hair. On his head, he wears a yellow and brown striped bandanna and over it is a tricorn captain''s hat with what appears to be his Jolly Roger on it, a white skull wearing an animal-like hood. He also wears a dark blue, open shirt with the sleeves rolled up and a ruffled collar, and elaborate earrings made up by three little jewels each on both ears. Not much is known about A O''s personality other than that he is very loyal to Whitebeard since he was willing to risk his own life to save Ace from execution instead of fleeing through the path he had cleared with his power. He was overjoyed when Luffy saved Ace, cheering with his fellow allies.',true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/8/8c/A_O_Anime_Infobox.png/revision/latest?cb=20160102105316', null, 36, null), 

('Abdullah', true, 'Abdullah is a criminal and a former bounty hunter who joined as a gladiator at the Corrida Colosseum to compete for the Mera Mera no Mi, along with his partner Jeet. He is an ally of Luffy during the Dressrosa Arc. After the battle with the Donquixote Pirates at Dressrosa, he joined the XXX Gym Martial Arts Alliance, which later converted to a pirate crew called the Ideo Pirates.',true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/…/latest/scale-to-width-down/700?cb=20151004140309', null, 38, null),

('Absalom', false, 'Absalom of the Graveyard was the leader of the Zombie Soldiers and Zombie Generals of Thriller Bark prior to its collapse. He was one of the Mysterious Four of the Thriller Bark Pirates and one of the major antagonists of the Thriller Bark Saga. \n
Sometime during the timeskip, he became a reporter under the alias Absa. At some point, he was abducted by the Blackbeard Pirates and killed to poach his Devil Fruit powers, with his ability going to Shiryu.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/…/latest/scale-to-width-down/699?cb=20230101154942', 24, 9, null), 

('Acilia', true, 'Acilia is a gladiator at the Corrida Colosseum who participated in a tournament for the Mera Mera no Mi. She is a large and bulky woman. Has dark colored lipstick, and dark colored hair. She is seen with a jolly smile, and sports an armored helmet', true, false, false, 'gladiator', 'https://static.wikia.nocookie.net/onepiece/images/0/0c/Acilia_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20180527001719', null, null, null),

('Adele', true, 'Adele is a mermaid and an employee at the Mermaid Café. She is a youthful mermaid with beautiful curly hair that reaches past her shoulders, and has dark skin and pink lipstick. She wears a bikini top with a leopard skin pattern, and her tail is red in color with several zig-zag patterns all of which is being different hues of red themselves.', true, false, false, 'mermaid', 'https://static.wikia.nocookie.net/onepiece/images/d/dd/Adele_Anime_Infobox.png/revision/latest?cb=20130210042308', null, null, null), 

('Aggie 68', true, 'Aggie 68 is a member of the Spade Pirates. Aggie 68''s abilities are unknown, but he and his crew were easily defeated by Newgate. He has been seen with a revolver-like gun attached to his wrist, but it is unknown how skilled he is in using it.', true, true, false, null, 'https://i.pinimg.com/originals/3a/8e/c4/3a8ec497882b626f807160b38177d96d.jpg', null, 60, null),

('Agotogi', true, 'Agotogi was the leader of a gang of bandits who tried to kidnap Vivi about 11 years before the princess''s return to Arabasta.', true, false, false, 'bandit', 'https://static.wikia.nocookie.net/onepiece/images/8/8b/Agotogi_Anime_Infobox.png/revision/latest?cb=20130919224447', null, null, null),

('Agsilly', true, 'Agsilly is a New World pirate who allied himself with the Whitebeard Pirates. He seemed to be loyal to his alliance with the Whitebeard Pirates, willing to fight in the war at Marineford in order to rescue Ace from execution, but his full power has not yet been shown.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e8/Agsilly_Anime_Infobox.png/revision/latest?cb=20130810194016', null, 48, null),

('Agyo', true, 'Agyo is a fighting lion and a gladiator competing at the Corrida Colosseum for the Mera Mera no Mi.', true, false, false, 'animal', 'https://static.wikia.nocookie.net/onepiece/images/1/11/Agyo_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20140707173009', null, null, null),

('Ahho Desunen IX', true, 'Ahho Desunen IX is a noble from the Goa Kingdom and the father of Ahho Zurako. Typical for a corrupted noble, Desunen is cruel and self-centered, as he believes that those who are not nobles are trash', true, false, false, 'noble', 'https://static.wikia.nocookie.net/onepiece/images/5/5f/Ahho_Desunen_IX_Anime_Infobox.png/revision/latest?cb=20130114035654', null, null, null),

('Ahho Zurako', true, 'Ahho Zurako is a noble from the Goa Kingdom and the daughter of Ahho Desunen IX. As a noble raised by a corrupted and spoiled parent, Zurako considers all people who are not nobles trash. She states that being burnt is their fault for not being born nobles.', true, false, false, 'noble', 'https://static.wikia.nocookie.net/onepiece/images/b/b2/Ahho_Zurako_Anime_Infobox.png/revision/latest?cb=20180417213414', null, null, null),

('Ahiru', true, 'Ahiru is the Deputy Commander of the East Army in the Revolutionary Army and the assistant of Belo Betty. Ahiru is a woman with tanned skin, prominent lips and long brown hair. Her left arm is a mechanical prosthesis with light and dark green (gray in the manga) coloring. She wears a black shirt, a red tie and a green jacket. She also has a pair of goggles on her head.', true, false, false, 'revolutionary', 'https://static.wikia.nocookie.net/onepiece/images/f/f1/Ahiru_Anime_Infobox.png/revision/latest?cb=20190703102730', null, null, null),

('Aisa', true, 'Aisa is a young Shandia girl who used to sneak onto the Upper Yard frequently to collect Vearth. She is Isa''s daughter. Ever since she was born, she had the ability known as "Mantra". Because of this, she hates it when people die and will try anything to stop it, even rushing into danger without any plans on what to do. Aisa wants to be a strong fighter like everyone else and was originally afraid of Wyper, though she warmed up to him eventually. Aisa is also a bit of a tomboy as she reacted with disgust when Raki suggested she grow her hair longer because it would look cute on her.', true, false, false, 'shandorian', 'https://static.wikia.nocookie.net/onepiece/images/4/45/Aisa_Anime_Pre_Timeskip_Infobox.png/revision/latest/scale-to-width-down/393?cb=20220403074416', null, null, null),

('Akehende', true, 'Akehende is a Marine Rear Admiral. Like many other Marines, he considers pirates as nuisances to be eliminated.', true, false, true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e8/Akehende_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20190511072409', null, null, 4),

('Akudai Kanzaburo', true, 'Akudai Kanzaburo is an arms dealer who lives in the Flower Capital of Wano Country. Kanzaburo''s skills as an arms dealer effectively earned him an invite to the shogun''s banquet.', true, false, false, 'wano civilian', 'https://static.wikia.nocookie.net/onepiece/images/5/56/Akudai_Kanzaburo_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20210905202949', null, null, 4),

('Akumai', true, 'Akumai was a Billions agent who followed Mr. 2 Bon Kurei everywhere before he was captured by Hina when Mr. 2 and his crew sacrificed themselves to save the Straw Hat Pirates. Not much of Akumai''s skills or power is ever shown. His only fights are unseen for the most part. His current fate is unknown.', true, false, false, 'billions agent', 'https://static.wikia.nocookie.net/onepiece/images/4/48/Akumai_Anime_Infobox.png/revision/latest?cb=20130626054008', null, null, null), 

('Aladine', true, 'Aladine is a goatsbeard brotula merman. He was originally a Ryugu Kingdom soldier who was then enslaved, but then became a pirate as the doctor and later first mate of the Sun Pirates. He is the husband of Charlotte Praline, serving as the bond between the Sun Pirates and the Charlotte Family.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/0/07/Aladine_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20170528042907', null, 34, null),

 ('Albion', true, '"Gashed" Albion is one of the rookie pirates who joined the Fake Straw Hat Crew. He has a bounty of 92,000,000 beli''s. Not much is known about his abilities. He has at least four bladed weapons, so it might be assumed that he is a swordsman. He is seen holding three daggers between the fingers on his right hand and using them like claws, similar to Buggy''s knife-combat style. It can be assumed that he is rather strong since he was able to make it all the way to Sabaody Archipelago and almost became a Supernova. He was also able to escape Sentomaru''s platoon, when most of the other recruits were apprehended.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c9/Albion_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20130207055626', null, 34, null),

('Ally', true, 'Ally is a little girl who was being held captive in the Biscuit Room, on Punk Hazard. She was freed with the rest of the children by the Straw Hat Pirates.', true, false, false, 'punk hazard child', 'https://static.wikia.nocookie.net/onepiece/images/f/f2/Ally_Anime_Infobox.png/revision/latest?cb=20140917053123', null, null, null), 

('Alpacaman', true, 'Alpacaman is a Gifter in the Beasts Pirates who serves as a guard in the Prisoner Mines of the Udon Region of Wano Country. He is shown using two sabers during his fight with Hyogoro and Luffy. He possesses some skill with them, and has a habit of spinning them around to show off and attack. He calls this style Alpaca Kenpo.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/a/a0/Alpacaman_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20200419035006', 131, 59, null),

('Alvida', true, '"Iron Mace" Alvida is the former captain of the Alvida Pirates and the first antagonist encountered by Luffy on his journey after going to sea. Due to her actions, she can be regarded as the secondary antagonist of the Romance Dawn Arc and the tertiary antagonist of the Loguetown Arc.
After her defeat against Luffy, she allies with Buggy and becomes one of the two captains of the Buggy and Alvida Alliance. She was the acting captain of the crew during Buggy''s time in Impel Down and during the Summit War of Marineford. After reuniting with Buggy, his army of Impel Down Convicts, and Galdino (and with the addition of Buggy becoming a Warlord of the Sea), her alliance with him has evolved into the Underworld Organization known as Buggy''s Delivery, and once again when that organization was re-integrated into the Organization known as Cross Guild.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/c/cd/Alvida_Anime_Infobox.png/revision/latest/scale-to-width-down/576?cb=20221116234952', 3, 46, null),

('Amadob', true, 'Amadob is an infamous New World pirate who allied himself with Whitebeard. Amadob is a fearsome pirate who has managed to achieve an infamous reputation in the New World, and to make an alliance with Whitebeard. It is still unknown what abilities and weapons he possesses.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/8/81/Amadob_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20130722051116', 3, 48, null),

('Amazon', true, 'Amazon was the elderly gatekeeper of Skypiea and informer at the entrance to Skypiea known as Heaven''s Gate. She let people in even if they could not pay her extol toll, but purposely failed to tell those who did not pay about the consequences for entering the city.
After the timeskip, she became the admission ticket saleswoman for Skypiea''s new theme park, Wagomuland.', true, false, false, 'shandorian', 'https://static.wikia.nocookie.net/onepiece/images/b/b1/Amazon_Anime_Pre_Timeskip_Infobox.png/revision/latest?cb=20130210103249', 3, 48, null),

('An Zengaiina', true, 'An Zengaiina is a prisoner on Level 2 of Impel Down. Not much is known about Zengaiina''s abilities, however he is dangerous enough to be imprisoned in the great prison although only on the second least secure level.', true, false, false, 'prisoner', 'https://static.wikia.nocookie.net/onepiece/images/0/04/An_Zengaiina_Anime_Infobox.png/revision/latest?cb=20190404152656', 3, 48, null),

('Andre', true, 'Andre is an infamous New World pirate captain who was once a member of the Whitebeard Pirates, before forming his own crew subordinate to Whitebeard. He is the twin brother of the Marine officer Candre. ', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b0/Andre_Anime_Infobox.png/revision/latest?cb=20101221185141', 3, 48, null),

('Anjo', true, 'Anjo is a pirate admirer. He witnessed Gol D. Roger''s execution. He has a tattoo of a plain Jolly Roger on his right arm.', true, false, false, 'civilian', 'https://static.wikia.nocookie.net/onepiece/images/a/ad/Anjo_Anime_Infobox.png/revision/latest?cb=20130610015428', null, null, null),

('Ankoro', true, 'Ankoro is a gigantic anglerfish formerly under the command of captain Vander Decken IX, residing in the Underworld of the Sea, seven thousand meters underneath the ocean surface. Wadatsumi seems to regard Ankoro as a pet, as apparently Ankoro was told "not to eat ships" before.', true, false, false, 'animal', 'https://static.wikia.nocookie.net/onepiece/images/0/07/Ankoro_Anime_Infobox.png/revision/latest?cb=20130901191817', null, null, null),

('Antonio', true, 'Antonio is the owner of "Antonio''s Graman" in Sabaody Archipelago. Chopper, Luffy, and Brook "sampled" multiple boxes of his food, causing him to ask if they would actually buy anything. However, they ended up buying a number of boxes along with some souvenirs.', true, false, false, 'sabaody civilian', 'https://static.wikia.nocookie.net/onepiece/images/4/48/Antonio_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20100104144419', null, null, null),

('Aphelandra', true, 'Aphelandra is a member of the tribe of Kuja living on the island of Amazon Lily. Despite her size, she has shown to be rather timid, often repeating what others have said to her as she obeys their command. She is a kind and innocent woman. Aphelandra is most likely a melee-type fighter where her prodigious size affords her a tremendous advantage over many foes. During the timeskip, she became a member of the Kuja Pirates.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/3/31/Aphelandra_Anime_Infobox.png/revision/latest?cb=201409281624093', null, 44, null),

('Aramaki', true, 'Aramaki, better known by his alias Ryokugyu, is an admiral in the Marines. He attained his rank during the two-year timeskip, along with Fujitora, both filling the two admiral vacancies left by Kuzan, who had resigned from the Marines, and Sakazuki, who had been promoted to fleet admiral.
Ryokugyu was first mentioned by Donquixote Doflamingo in the Dressrosa Arc, and debuted in the Levely Arc. His full appearance and real name were revealed near the end of the Wano Country Arc, in which he serves as a supporting antagonist.', true, false, true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/38/Aramaki_Manga_Infobox.png/revision/latest/scale-to-width-down/509?cb=20220621135221', 173, null, 2),

('Aremo Ganmi', true, 'Aremo Ganmi is a spectator at the Corrida Colosseum. She lives in Primula, a town in the west of Dressrosa.', true, false, false, 'dressrosa civilian', 'https://static.wikia.nocookie.net/onepiece/images/9/9b/Aremo_Ganmi_Anime_Infobox.png/revision/latest?cb=20140323063216', null, null, null),

('Arlong', true, 'Arlong the Saw is a sawshark fish-man. He was the captain of the all fish-man crew (excluding Nami), the Arlong Pirates, a former member of the Sun Pirates, and the older half-brother of Madam Shyarly. He is also a major inspirational figure for the New Fish-Man Pirates.
Following the death of his former captain, Fisher Tiger, Arlong was captured and sent to Impel Down, but received a pardon thanks to his comrade Jinbe becoming one of the Seven Warlords of the Sea. Once freed, Arlong set his sights on conquering the East Blue, settling himself on the Conomi Islands alongside his crew and racketeering the local population. He is also the man responsible for killing Bell-mère, Nami and Nojiko''s foster mother. Arlong then had Nami become his subordinate, taking advantage of her cartography skills to one day conquer all of the Blue Sea. He had the highest bounty in the East Blue before being defeated by Monkey D. Luffy. Due to his actions and role, he is the primary antagonist of the Arlong Park Arc.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/0/01/Arlong_Anime_Infobox.png/revision/latest?cb=20220420175931', null, 56, null),

('Arrow', false, 'He is tall and thin, with a pointed chin, with face paint around his eyes and around his jawline. He also wears shabby pants. He wields a double-edged sword with a golden hilt. Arrow is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', 'https://static.wikia.nocookie.net/onepiece/images/d/d8/Arrow_Portrait.png/revision/latest/scale-to-width-down/120?cb=20200114015005', null, null, null),

('Brahm', false, 'He is tall, with a hunchbacked appearance. He wears a turban and has light brown hair that covers his eyes. He wields two pole-arms. Brahm is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', 'https://static.wikia.nocookie.net/onepiece/images/e/e4/Brahm_Portrait.png/revision/latest/scale-to-width-down/120?cb=20200114015158', null, null, null),

('Barrel', false, 'He is bulky and rotund, and has a prominent nose, wearing thick white ropes around his shoulders, and has face paint around and under his eyes. He wields a large axe with a handle that is reminiscent of a flute. Barrel is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death', true, false, false, 'alabastian', 'https://static.wikia.nocookie.net/onepiece/images/6/6f/Barrel_Portrait.png/revision/latest/scale-to-width-down/120?cb=20200112073317', null, null, null),

('Hyota', false, 'He is very muscular, with a very large stubble-covered chin and a bulbous nose. He wields an extra large sword that resembles a butcher-knife. He is the leader of the group, under Chaka. Hyota is one of the four Tsumegeri Guards who drank the Hero Water and attempted to take down Crocodile, but failed and died from the water''s side effects shortly after Crocodile refused to even fight them to give them an honorable death.', true, false, false, 'alabastian', 'https://static.wikia.nocookie.net/onepiece/images/b/b2/Hyota_Portrait.png/revision/latest/scale-to-width-down/120?cb=20200112073054', null, null, null),

('Aruyutayan V', false, 'Aruyutayan V was the king of Lvneel Kingdom roughly 400 years ago when Mont Blanc Noland discovered Shandora. Aruyutayan was a greedy and selfish king who was not above making rash decisions if it resulted in personal gains. He was ignorant to the challenges of seafaring, refusing to bring along Noland''s experienced crew in favor of his kingdom''s army, who otherwise had little experience at sea. Aruyutayan was also seemingly unfazed by losing most of his soldiers on the voyage, being driven primarily by his materialistic desires for Shandora.\n
When he was denied the city he so much craved for, Aruyutayan was quick to think Noland had tricked him in spite of the latter''s credibility as a hero and famous explorer. A major egocentric, Aruyutayan did not tolerate being made a fool of, using his authority as a royal to order not only Noland''s execution, but also to carry out a post-mortem smear campaign that would lead to Noland''s legacy being twisted into that of a goofy liar. Aruyutayan went as far as planting a fake witness to trick his subjects into despising the otherwise beloved Noland.', true, false, false, 'king', 'https://static.wikia.nocookie.net/onepiece/images/0/08/Aruyutayan_V_Anime_Infobox.png/revision/latest?cb=20210903180254', null, null, null),

('Asahija', true, 'Asahija is a Marine Chief Petty Officer whose shadow was once stolen by Gecko Moria.', true, false, true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/de/Asahija_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20140512043917', null, null, 14),

('Asashichi', true, 'Asashichi is a resident of the Flower Capital who ran a soba shop with his wife. Asashichi cares deeply for his restaurant, as he was distraught when Page One destroyed it. He was angry at Sangoro for not intervening before his shop was destroyed.', true, false, false, 'wano civilian', 'https://static.wikia.nocookie.net/onepiece/images/e/e1/Asashichi_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20211010093618', null, null, null),

('Ashura Doji', false, 'Ashura Doji was a former bandit, a samurai from Wano Country and a retainer of the Kozuki Family, serving as one of Kozuki Oden''s Nine Red Scabbards. After Oden''s death, he returned to being a criminal under the name Shutenmaru, assuming leadership of the Mt. Atama Thieves. He initially severed his ties with the Kozuki Family in the present but rejoined after witnessing Yasuie''s death. \n
Ashura eventually met his demise during the Raid on Onigashima, sacrificing himself to protect his fellow Scabbards from one of Kanjuro''s schemes.', true, false, false, 'samurai', 'https://static.wikia.nocookie.net/onepiece/images/e/ef/Ashura_Doji_Anime_Concept_Art.png/revision/latest/scale-to-width-down/1000?cb=20200806205842', null, null, null),

('Aswa', null, 'Aswa is Koza''s mother and Toto''s wife.', true, false, false, 'alabastian', 'https://static.wikia.nocookie.net/onepiece/images/e/ef/Aswa_Anime_Infobox.png/revision/latest?cb=20130918202446', null, null, null),

('Atagoyama', true, 'Atagoyama is a sumo wrestler in Wano Country''s Bakura Town.', true, false, false, 'sumo wrestler', 'https://static.wikia.nocookie.net/onepiece/images/f/f7/Atagoyama_Anime_Infobox.png/revision/latest/scale-to-width-down/700?cb=20210711144015', null, null, null),

('Atlas', true, 'Atlas, also designated as Punk-05, is one of the six satellites of Dr. Vegapunk, embodying his aspect of "violence". Being designated the “violence” satellite of Vegapunk, Atlas has a short temper and is prone to violence upon getting angry, which has been shown to occur if someone attacks her or if people show an inability to utilize her inventions successfully. She is very talkative and will gladly give detailed explanations on the inner workings of her inventions. She is quite interested in the question of the definition of reality, and though she has a firm view on the matter, she thinks other people need to decide the answer for themselves.', true, false, false, 'vegapunk', 'https://static.wikia.nocookie.net/onepiece/images/0/08/Atlas_Manga_Infobox.png/revision/latest?cb=20221010163059', null, null, null),

('Atmos', true, '"Water Buffalo" Atmos is the commander of the 13th division of the Whitebeard Pirates. Atmos carries around two large swords and can deal devastating blows with them, as seen when he attacked and destroyed the swords of some of his crewmates while Doflamingo controlled him. In the anime, he could even block bullets that were shot from rifles to protect his allies.', true, true, false, null, 'https://static.wikia.nocookie.net/onepiece/images/6/6f/Atmos_Anime_Infobox.png/revision/latest?cb=20180904201451', null, 48, null),

-- name, alive, info, canon, pirate, marine, other, photo, devil_fruitID, pirate_groupID, marine_RanksID