\c one_piece_dev;

INSERT INTO types_of_devilFruits ( name, sub_type, rare ) VALUES
('Paramecia', null, false),
('Zoan', null, false),
('Zoan', 'Ancient', true),
('Zoan', 'Mythical', true),
('Logia', null, true),
('Artifical', null, null);


INSERT INTO devil_fruits ( org_name, eng_name, canon, movie, photo, descr, awakened, currentUser, previous_user, type_of_fruit ) VALUES
('Gomu Gomu no Mi', 'Gum-Gum Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/12/Gomu_Gomu_no_Mi_Infobox.png/revision/latest?cb=20190419140206', 'grants the user the properties of rubber, effectively turning them into a Rubber Human. It was originally known as the Hito Hito no Mi, Model: Nika and was classified as a Mythical Zoan-type fruit that allows the user to transform into the legendary "Sun God" Nika and gain his attributes before being reclassified by the World Government.', 'grants the user the properties of rubber, effectively turning them into a Rubber Human. It was originally known as the Hito Hito no Mi, Model: Nika and was classified as a Mythical Zoan-type fruit that allows the user to transform into the legendary "Sun God" Nika and gain his attributes before being reclassified by the World Government.', 'Monkey D. Luffy', null, 1),

('Bara Bara no Mi', 'Chop-Chop Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/9c/Bara_Bara_no_Mi_Infobox.png/revision/latest?cb=20201102125104', 'allows the user to split their own body into pieces and control said pieces however they wish, making the user a Splitting Human.', null, 'Buggy', null, 1),

('Sube Sube no Mi', 'Smooth-Smoth Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e9/Sube_Sube_no_Mi_Infobox.png/revision/latest?cb=20200912191823', 'makes the user''s body smooth and slippery, which in turn makes most attacks and objects slide off their body, protecting the user from harm in most situations.', null, '''Iron Mace'' Alvida', null, 1),

('Bomu Bomu no Mi', 'Bomb-Bomb Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/1a/Bomu_Bomu_no_Mi_Infobox.png/revision/latest?cb=20210204030003', 'allows the user to make any part of their body explode, whether it be their limbs, hair, mucus, or even breath; making the user a Bomb Human.', null, 'Gem of the Border aka Mr. 5', null, 1), 

('Kiro Kiro no Mi', 'Kilo-Kilo Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/89/Kiro_Kiro_no_Mi_Infobox.png/revision/latest?cb=20210204030042', 'allows the user to change their weight from 1 to 10,000 kilograms without, in any way, affecting the overall size of their body', null, 'Mikita aka Miss Valentine', null, 1),

('Hana Hana no Mi','Flower-Flower Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/21/Hana_Hana_no_Mi_Infobox.png/revision/latest?cb=20191228120242', 'allows the user to replicate and sprout pieces of their body from the surface of any object or living thing.', null, 'Nico Robin aka Miss All Sunday', null, 1),

('Doru Doru no Mi', 'Wax-Wax Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/5f/Doru_Doru_no_Mi_Infobox.png/revision/latest?cb=20200507205151', 'allows the user to create large quantities of candle wax from their body and control it, making the user a Candle Human.', null, 'Galdino aka Mr. 3', null, 1),

('Baku Baku no Mi', 'Munch-Munch Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c6/Baku_Baku_no_Mi_Infobox.png/revision/latest?cb=20200507163319', 'allows the user to eat anything. The eaten items can then be merged into and manifested from the user''s body or be combined to create something else.', null, '''Tin-Plate'' Wapol', null, 1),

('Mane Mane no Mi', 'Clone-Clone Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/0e/Bentham_Anime_Infobox.png/revision/latest/scale-to-width-down/281?cb=20160929070742', 'allows the user to turn into a physical double of anyone they have touched, making the user an Imitating Human (マネ人間 Mane Ningen?).[2] When the user changes, they also imitate the copied person''s flexibility, strength, and abilities, aside from those bestowed by a Devil Fruit. They can change to someone else by touching their face with their right hand and switch back to their normal state by touching their face with their left hand.', null, 'Bentham aka Mr. 2 Bon Kurei', 'Kurozumi Higurashi', 1),

('Supa Supa no Mi', 'Dice-Dice Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/f/f9/Supa_Supa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160925122350', 'allows the user to transform any part of their body into a blade, thus gaining slashing abilities and making their skin as hard as steel.', null, 'Daz Bonez aka Mr.1', null, 1),

('Toge Toge no Mi', 'Spike-Spike Fruit', true, null,'https://static.wikia.nocookie.net/onepiece/images/e/ee/Toge_Toge_no_Mi_Infobox.png/revision/latest?cb=20130120203503', 'allows the user to grow strong pointy spikes from their body.', null, 'Zala aka Miss Doublefinger', null, 1),

('Ori Ori no Mi', 'Cage-Cage Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7a/Ori_Ori_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130115015011', 'allows the user to bind their foes in iron shackles created by the user''s body.' , null, 'Hina', null, 1),

('Bane Bane no Mi', 'Spring-Spring Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/1d/Bane_Bane_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160913222919', 'allows the user to turn their limbs into springs, making the user a Spring Human.', null, 'Belamy', null, 1),

('Ito Ito no Mi', 'String-String Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/ae/Ito_Ito_no_Mi_Infobox.png/revision/latest/scale-to-width-down/700?cb=20151220070449', 'allows the user to create and manipulate strings, making the user a String Human. If awoken, the fruit''s power can allow the consumer to transmute the surrounding area, like the ground and buildings, into strings as well, which they can utilize for much stronger attacks and defense.', true, 'Donquixote Donflamingo', null, 1),

('Noro Noro no Mi', 'Slow-Slow Fruit', true, null,'https://static.wikia.nocookie.net/onepiece/images/7/7a/Noro_Noro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130414195444', 'allows the user to emit special unique photons. Anything hit by these photons will be trapped in a state of slow motion for 30 seconds.', null, 'Foxy', null, 1),

('Doa Doa no Mi', 'Door-Door Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/04/Doa_Doa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130629174737', 'allows the user to create doors through anything they touch, making the user a Door Human (ドア人間 Doa Ningen).The doors they create can be created from any part of their body, from the palm of their hands to their whole body itself, and usually take the shape and form of the body part creating it. The doors remain as passageways anyone can pass through until closed completely.', null, 'Blueno', null, 1),

('Awa Awa no Mi', 'Bubble-Bubble Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/51/Awa_Awa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/700?cb=20131206044150', 'allows the user to emit and control soap and bubbles that can not only clean off dirty but can also ''clean off'' power, making the user a Soap Human.', null, 'Kalifa', null, 1),

('Beri Beri no Mi', 'Berry-Berry Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/27/Beri_Beri_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130503053935', 'allows the user to transform their body parts into a multitude of orbs or spheres shaped like the round parts of berries, making the user a Grape Human (ブドウ人間 Budō Ningen). The effect is similar to that of the Bara Bara no Mi.', null, 'Very Good', null, 1),

('Sabi Sabi no Mi', 'Rust-Rust Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7c/Sabi_Sabi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160708014101', 'allows the user to cause metallic items to rust and come apart, making the user a Rust Human (サビ人間 Sabi Ningen).', null, 'Shu', null, 1),

('Shari Shari no Mi', 'Wheel-Wheel Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e4/Shari_Shari_no_Mi_Infobox.png/revision/latest?cb=20220723150343', 'allows the user to transform their arms and feet into wheels, making the user a Wheel Human (車輪人間 Sharin Ningen).', null, 'Sharinguru', null, 1),

('Horo Horo no Mi', 'Hollow-Hollow Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/14/Horo_Horo_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130922165024', 'allows the user to create and control ghosts with different abilities, such as inflicting feelings of despair on people whom they pass through, or exploding with great force. The user can also make their own ghost leave their body as a form of astral projection.', null, 'Perona', null, 1),

('Yomi Yomi no Mi', 'Revive-Revive Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/3b/Yomi_Yomi_no_Mi_Infobox.png/revision/latest?cb=20201116170233', 'enhances the user''s soul to the point where they resurrect after their first death, allowing them to live a second time and to use several other soul-based abilities, making the user a Reviving Human.', null, '''Soul King'' Brook', null, 1),

('Kage Kage no Mi', 'Shadow-Shadow Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7b/Kage_Kage_no_Mi_Infobox.png/revision/latest?cb=20201116170246', 'allows the user to manifest and control shadows. They can animate and freely manipulate their own shadow, as well as steal and absorb other people''s shadows, making the user bigger and stronger. Stolen shadows can also be implanted into corpses, reanimating them.', null, 'Gecko Moria', null, 1), 

('Suke Suke no Mi', 'Clear-Clear Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/bb/Suke_Suke_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20200112035251', 'allows the user to become invisible, as well as make anything they touch invisible.', null, 'Shiryu', 'Absalom', 1),

('Nikyu Nikyu no Mi', 'Paw-Paw Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e4/Nikyu_Nikyu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190411220015', 'bestows its user the ability to repel everything they touch, and is physically represented as paws on the user''s palms, making the user a Paw Human. The paws are permanently engraved into the user, as Kuma is always seen wearing gloves when his powers are not in use.', null, 'Bartholomew Kuma', null, 1),

('Jiki Jiki no Mi', 'Magnet-Magnet Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/13/Jiki_Jiki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220525022232', 'allows the user to create magnetic forces and use them to control metal', null, 'Eustass Kid', null, 1),

('Ope Ope no Mi', 'Op-Op Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/0e/Ope_Ope_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210409181034', 'grants the ability to manifest a spherical space in which the user can manipulate the orientation, movements, and physical configureation of anything and anyone (themselves included) in a ''surgical'' fashion, making the user a Free Modification Human', null, 'Trafalgar D. Water Law', null, 1),

('Shiro Shiro no Mi', 'Castle-Castle Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e8/Shiro_Shiro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160115065100', 'allows the user to become a living fortress equipped with cannons, as well as letting them shrink people and objects who enter their body and house them inside.', null, 'Capone Bege', null, 1),

('Wara Wara no Mi', 'Straw-Straw Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b4/Wara_Wara_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180803070246', 'allows the user to create and control straw. They can also create straw voodoo dolls, allowing the user to transfer the damage they take to the dolls and, by extension, the people connected to them.', null, 'Basil Hawkins', null, 1),

('Oto Oto no Mi', 'Tone-Tone Frui', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/1e/Apoo_Using_Musical_Powers.png/revision/latest/scale-to-width-down/350?cb=20130209042848', 'By transforming their body parts into instruments (such as turning teeth into piano keys or an arm into a trumpet) and playing specific notes and tunes, the user can release music that causes damaging effects to their opponents, the type of damage being determined by what they play. There is a wide range of attacks the user can perform, from physical strikes like punches and slashes (which can dismember victims) to elemental attacks like explosions.', null, 'Scratchman Apoo', null, 1),

('Mero Mero no Mi', 'Love-Love Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/98/Mero_Mero_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180627192522', 'user is able to transform those who lust or love after the user into stone in varying degrees by using their ''dirty thoughts''. Victims that have been completely turned to stone are incapable of consciousness and susceptible to physical damage unless the user de-petrifies them. Petrification can also be achieved through physically striking an opponent, although the only area that is turned to stone is the contacted area, as opposed to the entire body. The power also extends to nonliving objects.', null, 'Boa Hancock', null, 1),

('Doku Doku no Mi', 'Venom-Venom Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/21/Doku_Doku_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160129102538', 'grants the user the ability to produce and control different types of poison, as well as grants immunity to all forms of poison, making the user a Poison Human (毒人間 Doku Ningen).', null, 'Magellan', null, 1), 

('Horu Horu no Mi', 'Horm-Horm Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/53/Horu_Horu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20120328040657', 'allows the user to create special hormones that can alter a person''s body in various ways, as well as turn their fingers into syringes that they can use to inject the hormones into a person''s body.', null, 'Emporio Ivankov', null, 1),

('Choki Choki no Mi', 'Shear-Shear Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/0f/Choki_Choki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130224140928', 'allows the user to transform parts of their body into scissors and cut solid objects as if they were paper, making the user a Scissors Human (ハサミ人間 Hasami Ningen).', null, 'Inazuma', null, 1),

('Gura Gura no Mi', 'Tremor-Tremor Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e3/Gura_Gura_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20200716073745', 'the user is its ability to generate massive vibrations, or shockwaves, which can travel through virtually any medium, including the ground, the seafloor, and even the air.', null, 'Marshall D. Teach', 'Edward Newgate aka Whitebeard', 1),

('Kira Kira no Mi', 'Twinkle-Twinkle Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/ad/Kira_Kira_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20101021104815', 'allows the user to transform their body into diamond.', null, 'Jozu', null, 1),

('Poke Poke no Mi', 'Pocket-Pocket Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/26/Poke_Poke_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220426093454', 'allows the user to store various things inside pockets in their body. The objects stored inside can be much larger than the opening of the pocket, as they change size accordingly. It is stated that the user can have infinite pockets in their person, effectively giving them limitless storage capacity.', null, 'Blamenco', null, 1), 

('Woshu Woshu no Mi', 'Wash-Wash Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/4c/Woshu_Woshu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20121228203008', 'allows the user to ''wash and hang out to dry'' people and objects as if they were clothes. This seems to render their victims unable to fight back or move.', null, 'Tsuru', null, 1),

('Fuwa Fuwa no Mi', 'Float-Float Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/df/Fuwa_Fuwa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/1000?cb=20130323001748', 'allows the user to levitate themselves and non-living things into the air.', null, 'Shiki', null, 1),

('Mato Mato no Mi', 'Mark-Mark Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b7/Mato_Mato_no_Mi_Infobox.png/revision/latest?cb=20220726190549', 'makes the user capable of aiming at whoever they touch with their hands. The user can also memorize as many targets with as many hands as they have.', null, 'Vander Decken IX', null, 1),

('Fuku Fuku no Mi', 'Garb-Grab Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/9c/Fuku_Fuku_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20181020010802', 'allows the user to create clothing and other apparel out of leaves or stones by visualizing them.', null,'Kin''emon', null, 1),

('Hobi Hobi no Mi', 'Hobby-Hobby Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/3d/Hobi_Hobi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190416040233', 'allows the user to transform living people into toys, and erase memories of their existence from others. It has a secondary side effect of granting the eater eternal youth.', null, 'Sugar', null, 1),

('Buki Buki no Mi', 'Arms-Arms Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/3e/Buki_Buki_no_Mi_Infobox.png/revision/latest?cb=20141206174322', 'gives the user the ability to change their body into any kind of weapon. The user can either transform small parts of their body, like the fingers, hands or arms; or a larger body-section, such as their entire torso or even their whole body, into a weapon.', null, 'Baby 5', null, 1),

('Guru Guru no Mi', 'Spin-Spin Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/0a/Guru_Guru_no_Mi_Infobox.png/revision/latest?cb=20141206170537', 'grants its eater the power to transform any part of their body or piece of worn clothing into propellers capable of rotation at high speed. The force of the spinning is strong enough to enable propelled flight by the user over very long distances, to assist in the carrying or thrown launch of objects and other people, and to create powerful windstorms.', null, 'Buffalo', null, 1),

('Beta Beta no Mi', 'Stick-Stick Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d9/Beta_Beta_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180513215218', 'allows the user to create and control mucus, making the user a Mucus Human (粘液人間 Nen''eki Ningen).', null, 'Trebol', null, 1), 

('Zushi Zushi no Mi', 'Press-Press Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/ba/Zushi_Zushi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160529113354', 'Whoever eats from this fruit is granted the power to create gravitational forces of extreme potency. The ability user is able to move about living things and objects with little effort, ranging from debris to send flying against an enemy in smaller or massive numbers, to a massive battleship. The range of the generable gravity field appears incredibly big, as it can pull down meteors from the highest of skies (possibly the outer atmosphere, or even space itself.', null, 'Issho aka Admiral Fujitora', null, 1),

('Bari Bari no Mi', 'Barrier-Barrier Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/de/Bari_Bari_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160212174221', 'The fruit''s bestowed ability is the conjuration of physical barriers—either invisible or visibly transparent, resembling panes of glass—which is done by the user''s crossing their fingers. This protects the user from attacks from either front or back. The barriers have immense defensive power.', null, 'Bartolomeo', null, 1),

('Nui Nui no Mi', 'Stitch-Stitch Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/00/Nui_Nui_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190526000026', 'allows the user to stitch objects to any surface. This makes it useful for restraining people, pinning them to the ground, to a wall or even other nearby individuals. The user is also able to undo the stitches of the object with ease, freeing it from their power.', null, 'Leo', null, 1),

('Giro Giro no Mi', 'Glare-Glare Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/23/Giro_Giro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20201101164342', 'allows the user to see through everything, both literally and figuratively. By forming circles out of their index finger and thumb and putting their hands next to their eyes, like glasses, the user can see through a person''s clothes and skin, much like X-ray specs, but also read their minds and memories, allowing them to see through any lies. It also allows the user to transfer their own memories to another person''s mind, by letting another person look through the circled fingers.', null, 'Viola', null, 1),

('Ato Ato no Mi', 'Art-Art Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/0f/Ato_Ato_no_Mi_Infobox.png/revision/latest?cb=20160708134450', 'allows the user to transform any target into an abstract art, distorting it in both appearance and usage. This is accomplished by the user creating a thought cloud, and then tossing it at the target, causing it to distort. Any weapons or vehicles warped by this power loses its functionality; even natural weapons such as hooves and antlers are turned useless.', null, 'Giolla', null, 1),

('Jake Jake no Mi', 'Jacket-Jacket Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/ce/Kelly_Funk_Immediately_After_Transforming.png/revision/latest?cb=20140525204909', 'Allows the user to transform into a whole-body jacket and control the body of the person wearing them. While being worn, the user can take advantage of both their own physical abilities and those of the person wearing them.', null, 'Kelly Funk', null, 1),

('Pamu Pamu no Mi', 'Pop-Pop Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/a9/Pamu_Pamu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141215214103', 'allows the user to cause anything inorganic they touch to swell up, which will then rupture and explode violently. The user can also apply it to themselves. The user remains unharmed from the explosion.', null, 'Gladius', null, 1),

('Sui Sui no Mi', 'Swim-Swim Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/9d/Sui_Sui_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141019165710', 'allows the user to swim in solid matter such as ground and walls as if it were water, the latter even allowing the user to swim upwards, seemingly disregarding gravity. It also allows the user to submerge into the ground to avoid colliding with it upon falling from a great height by performing a high dive. The fruit can also allow the user to move discreetly, as they will be mostly covered by the ground, allowing them to infiltrate places more easily.', null, 'Señor Pink', null, 1),

('Ton Ton no Mi', 'Ton-Ton Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/40/Ton_Ton_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20151003022742', 'allows the user to increase their body weight by incredible amounts, leveled by metric tons. This allows them to land crushing attacks that can easily crack the ground and even a giant''s bones.', null, 'Machvise', null, 1),

('Hira Hira no Mi', 'Ripple-Ripple Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/5a/Hira_Hira_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20151110020239', 'allows the user to make their body and anything they touch gain the malleable properties of cloth fabric. As such, the affected materials become completely flexible, flat, and foldable; this effect is strong enough to let hardened metal flutter like a flag in the breeze at the user''s command. At the same time, all other natural characteristics such as toughness, strength, or sharpness are retained by the material, so metal objects can still resist forceful impact from enemies and blades retain an edge.', null, 'Diamante', null, 1),

('Ishi Ishi no Mi', 'Stone-Stone Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/90/Ishi_Ishi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180529180105', 'allows the user to take control of anything made of stone that they come in contact with. While under the user''s control, the stone gains a surprising level of flexibility and dexterity that it otherwise would not have.', null, 'Pica', null, 1),

('Fude Fude no Mi', 'Brush-Brush Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b4/Fude_Fude_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210710161433', 'allows the user to generate ink from their body and use a painting brush to turn images created with that ink into three-dimensional, lifelike objects.', null, 'Kurozumi Kanjuro', null, 1),

('Nagi Nagi no Mi', 'Calm-Calm Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/37/Nagi_Nagi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20150802120152', 'user of this Devil Fruit has the ability to create a soundproof field. The field makes it so that the sounds inside the field cannot be heard from the outside, and vice versa. The user can also use this fruit''s ability to cancel all noises coming from the user or somebody else''s actions, making it ideal for situations requiring stealth since the lack of noise helps the user prevent drawing attention from enemies while realizing tasks that, otherwise, would be hard to conceal.', null, 'Donquixote Rosinante', null, 1),

('Chiyu Chiyu no Mi', 'Heal-Heal Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b2/Chiyu_Chiyu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20151129192854', 'allows the user to heal any living thing that is wounded or injured. The healing powers manifest in the form of tears from the user''s body. As soon as they touch a living thing, it is restored to perfect health and can even recover people suffering from a massive shock; however, despite being able to heal body parts back together, it cannot create them from nothing.', null, 'Mansherry', null, 1),

('Soru Soru no Mi', 'Soul-Soul Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/9d/Soru_Soru_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20170521101146', 'the fruit''s power of soul manipulation consists of manifesting and drawing out the souls of people who feel fear. The manifested souls take the form of a light-pink, spectral-looking but (for the user) tangible substance, which leaks out of the victim''s body like smoke. The user can extract the victim''s soul by grabbing it once it is surrounding the target''s body and pulling it out. This effectively steals from the victim''s very lifespan, the amount of which is determined by the user: it is possible to steal decades of a person''s life at once should they desire, or mere seconds. The user can steal part of the victim''s lifespan, leaving their remaining lifespan that much shorter, or even take enough years to steal a victim''s entire remaining lifespan, killing them instantly.', null, 'Charlotte Linlin aka Big Mom', 'Mother Carmel', 1),

('Mira Mira no Mi', 'Mirror-Mirror Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c3/Mira_Mira_no_Mi_Infobox.png/revision/latest/scale-to-width-down/334?cb=20170709205701', 'allows the user to create multiple mirrors in their own vicinity with their own hands. These mirrors can be used as a shield against enemy attacks, absorbing them and reflecting them back at the attacker, turning their own power against them. These mirrors can also be used as portals into what appears to be a pocket dimension within the mirrors known as Mirro-World (鏡世界ミロワールド Miro Wārudo), with no apparent way back through, leaving their opponents trapped.', null, 'Charlotte Brûlée', null, 1),

('Pero Pero no Mi', 'Lick-Lick Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/77/Pero_Pero_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190412202445', 'allows the user to create and control seemingly limitless amounts of candy, even being able to make it move as if it were a mechanical construct, like escalators and prostheses. The candy created by the user is edible. When hardened, the candy becomes incredibly strong and resilient.', null, 'Charlotte Perospero', null, 1), 

('Bisu Bisu no Mi', 'Bis-Bis Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/8b/Bisu_Bisu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20170730022308', 'allows the user to generate and manipulate biscuits at will, making them a Biscuit Human (ビスケット人間 Bisuketto Ningen).', null, 'Charlotte Cracker', null, 1),

('Bata Bata no Mi', 'Butter-Butter Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/6/61/Bata_Bata_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20181203192223', 'allows the user to control seemingly limitless amounts of butter. Despite butter usually making objects slippery, the created butter has been shown to be quite sticky and adhesive when in semi-liquid form, capable of immobilizing an opponent by wrapping it around their hands or bodies', null, 'Charlotte Galette', null, 1), 

('Buku Buku no Mi', 'Book-Book Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/44/Buku_Buku_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180904134020', 'grants the user the ability to control nearby books, regardless of their size, allowing them to telekinetically move them around and even use them as footholds. The biggest strength of this fruit is the ability to trap living things inside a book''s setting.', null, 'Charlotte Mont-d''Or', null, 1),

('Kuri Kuri no Mi', 'Cream-Cream Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/73/Kuri_Kuri_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180913105124', 'allows the user to create and control seemingly limitless amounts of cream, which they can use to attack and capture their foes. The cream''s sugar is capable of inflicting painful second or third degree burns to anyone it comes in contact with, allowing the user to physically harm their opponents while also making them hard to approach in battle due to the risk of coming in contact with the cream.', null, 'Charlotte Opera', null, 1),

('Shibo Shibo no Mi', 'Wring-Wring Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d7/Shibo_Shibo_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20180531213234', 'allows its user to drain liquid from both living and non-living things by wringing them, as well as absorb liquid into themselves and their weapons, making them a Dehydration Human (脱水人間 Dassui Ningen).', null, 'Charlotte Smoothie', null, 1),

('Memo Memo no Mi', 'Memo-Memo Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c0/Memo_Memo_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20171217105138', 'allows the user to turn people''s memories into strips of film and manipulate them.', null, 'Charlotte Pudding', null, 1),

('Mochi Mochi no Mi', 'Mochi-Mochi Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/2c/Mochi_Mochi_no_Mi_Infobox.png/revision/latest?cb=20220525022420', 'allows the user to create, control, and transform into mochi', null, 'Charlotte Katakuri', null, 1),

('Hoya Hoya no Mi', 'Puff-Puff Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/97/Hoya_Hoya_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210208063127', 'allows the user to summon a genie from their body, making the user a Lamp Human (ランプ人間 Ranpu Ningen).', null, 'Charlotte Daifuku', null, 1),

('Netsu Netsu no Mi', 'Heat-Heat Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c5/Netsu_Netsu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210208063018', 'The user is capable of heating parts of their body to temperatures greater than most people can withstand. This greatly aids them in a confrontation. They can transfer the heat to other objects, most notably the opponents'' weapons, making them too hot to wield. This transfer of heat can even happen without physical contact, as demonstrated when Oven seemingly projected heat energy to set a gun ablaze.', null, 'Charlotte Oven', null, 1),

('Kuku Kuku no Mi', 'Cook-Cook Fruit', true, null, '/latest/scale-to-width-down/350?cb=20180527032147', 'allows the user to turn objects into food.', null, 'Streusen', null, 1),

('Gocha Gocha no Mi', 'Pile-Pile Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/47/Gocha_Gocha_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190324125515', 'allows the user to merge themselves with other people.', null, 'Charlotte Newshi', null, 1),

('Oshi Oshi no Mi', 'Push-Push Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/1f/Oshi_Oshi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220721051214', 'allows the user to freely move and shape the ground as though it was malleable like clay.', null, 'Morley', null, 1),

('Kobu Kobu no Mi', 'Pump-Pump Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/75/Kobu_Kobu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190414130522', 'allows the user to encourage and rally other people to awaken their latent potential to fight.', null, 'Belo Betty', null, 1),

('Kibi Kibi no Mi', 'Millet-Millet Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/35/Kibi_Kibi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190819140148', 'allows the user to create ''dango'' from their cheeks that can tame animals and those of part-animal nature.', null, 'Tama', null, 1),

('Toki Toki no Mi', 'Time-Time Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/6/6b/Toki_Toki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210221040316', 'allows the user to send themselves and others forward in time. By using this power, the user will send themselves or people of their choosing into the future, disappearing from the present day and appearing at the selected moment in time instantaneously. The user is also apparently able to decide the specific amount of time skipped for each trip. It is impossible to travel into the past, meaning that any and all trips forward in time are irreversible. Also, the fruit''s power cannot teleport the travelers to other locations, meaning that the user must be careful of where they or others are standing at the moment of the time-jump.', null, 'Kozuki Toki', null, 1),

('Juku Juku no Mi', 'Ripe-Ripe Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/f/f1/Juku_Juku_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20200412160241', 'allows the user to mature and decay anything they touch. Using it on the ground will cause it to become a sinkhole, allowing the user to potentially avoid attacks by sinking into the ground. The fruit can also help the user get past physical obstacles by weakening them through aging, causing them to collapse or be easily broken through. This power can also be applied on living beings, causing them to grow older in an instant.', null, 'Shinobu', null, 1),

('Maki Maki no Mi', 'Scroll-Scroll Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d1/Maki_Maki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220118062718', 'allows the user to create and control scrolls at will, which have special properties including storing objects and generating drawings.', null, 'Raizo', null, 1),

('Goe Goe no Mi', null, false, '["One Piece: The Movie"]', 'https://static.wikia.nocookie.net/onepiece/images/a/a7/Goe_Goe_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130124065628', 'allows the user to create beams of sound that look like energy beams by shouting.', null, 'Eldoraggo', null, 1),

('Hiso Hiso no Mi', 'Whisper-Whisper Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/f/fe/Hiso_Hiso_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160901213949', 'allows the user to understand the heart of an animal; in other words, it allows them to ''speak'' telepathically to animals.', null, 'Apis', null, 1),

('Kama Kama no Mi', 'Sickle-Sickle Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b9/Kama_Kama_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130929180103', 'gives the user long, sharp nails that they can use to create slicing air blades.', null, 'Eric the Whirlwind', null, 1),

('Kachi Kachi no Mi', 'Hard-Hard Fruit', false, '["One Piece: Clockwork Island Adventure"]', 'https://static.wikia.nocookie.net/onepiece/images/9/9e/Kachi_Kachi_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130626010944', 'allows the user to harden their body and raise their body temperature.', null, 'Bear King', null, 1),

('Nemu Nemu no Mi', null, false, null, 'https://static.wikia.nocookie.net/onepiece/images/8/89/Nemu_Nemu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20140131234604', 'grants the user the ability to make anyone fall asleep.', null, 'Noko', null, 1),

('Mini Mini no Mi', 'Mini-Mini Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e6/Mini_Mini_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20131214220828', 'allows the user to become smaller than their actual size.', null, 'Lily Enstomach', null, 1),

('Atsu Atsu no Mi', 'Hot-Hot Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/b/b1/Atsu_Atsu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130624204211', 'gives the user the ability to produce and control vast amounts of heat, making them a 10,000 Degree Human (１万度人間 Ichiman Do Ningen).', null, 'Don Accino', null, 1),

('Noko Noko no Mi', null, false, 'Episode of Chopper Plus: Bloom in Winter, Miracle Sakura', 'https://static.wikia.nocookie.net/onepiece/images/4/45/Noko_Noko_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130520095054', 'allows the user to create and control poisonous mushroom spores.', null, 'Musshuru', null, 1),

('Ami Ami no Mi', 'Net-Net Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/5/5a/Ami_Ami_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20131025155034', 'allows the user to create nets, as well as turn their nets into any material they ingest.', null, 'Largo', null, 1),

('Kopi Kopi no Mi', 'Copy-Copy Fruit', false, 'One Piece Premier Show 2012', null, 'allows the user to copy the abilities of another Devil Fruit user.', null, 'Chameleone', null, 1),

('Modo Modo no Mi', 'Return-Return Fruit', false, 'One Piece Film: Z', 'https://static.wikia.nocookie.net/onepiece/images/5/54/Modo_Modo_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220106225523', 'grants the user the ability to generate pink energy which returns anyone and anything twelve years younger, which lets the user become a Return Return Human (モドモド人間 Modo Modo Ningen).', null, 'Ain', null, 1),

('Mosa Mosa no Mi', 'Grow-Grow Fruit', false, 'One Piece Film: Z', 'https://static.wikia.nocookie.net/onepiece/images/e/e0/Mosa_Mosa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220106225303', 'grants the user the ability to accelerate the growth rate of plants and control them to their desire.', null, 'Binz', null, 1),

('Gutsu Gutsu no Mi', 'Smelt-Smelt Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7a/Gutsu_Gutsu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160717205338', 'allows the user to turn their body into a blast furnace and melt metals inside it, making them a Blast Furnace Human (溶鉱炉人間 Yōkōro Ningen).', null, 'Bill', null, 1),

('Peto Peto no Mi', 'Pet-Pet Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/f/f8/Peto_Peto_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20140622022914', 'allows the user to control any living creature by giving them a green gel-like collar.', null, 'Breed', null, 1),

('Kone Kone no Mi', 'Knead-Knead Fruit', false, 'One Piece Premier Show 2014', null, 'allows the user to transform someone to look like someone else. The main strength of the fruit is being able to turn normal people into copies of others, giving them the appearance, abilities, and strength of those they are copying.', null, 'Bildy', null, 1),

('Moa Moa no Mi', 'More-More Fruit', false, '3D2Y: Overcome Ace''s Death! Luffy''s Vow to his Friends', 'https://static.wikia.nocookie.net/onepiece/images/5/5b/Moa_Moa_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20140901033934', 'allows the user to multiply the size and speed of any object they touch.', null, 'Byrnndi World', null, 1),

('Kyubu Kyubu no Mi', 'Cube-Cube Fruit', false, '3D2Y: Overcome Ace''s Death! Luffy''s Vow to his Friends', 'https://static.wikia.nocookie.net/onepiece/images/3/38/Kyubu_Kyubu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20140831215541', 'allows the user to transform anything they touch into a cube.', null, 'Gairam', null, 1),

('Maji Maji no Mi', null, false, 'Lucy & Lucy Coliseum the Battle', null, 'allows the user to use magic-based abilities like hypnotism, invisibility, and illusions.', null, 'Inchikin', null, 1),

('Nito Nito no Mi', 'Nitro-Nitro Fruit', false, 'One Piece Premier Show 2015', null, 'allows the user to gain the abilities of nitroglycerin.', null, 'Bürst', null, 1),

('Hore Hore no Mi', 'Fondly-Fondly Fruit', false, 'One Piece Premier Show 2015', null, 'allows the user to make people fall in love with them through lights.', null, 'Bonbon', null, 1),

('Nuke Nuke no Mi', 'Through-Through Fruit', false, 'One Piece Film: Gold', 'https://static.wikia.nocookie.net/onepiece/images/f/f8/Nuke_Nuke_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190414113527', 'allows the user to phase through solid objects.', null, 'Tanaka', null, 1),

('Koro Koro no Mi', 'Roll-Roll Fruit', false, null,'https://static.wikia.nocookie.net/onepiece/images/e/e3/Koro_Koro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190414114007', 'allows the user to turn their hands and feet into train wheels, making them a Rail Car Human (トロッコ人間 Torokko Ningen).', null, 'Aveyron', null, 1), 

('Jara Jara no Mi', 'Chain-Chain Fruit', false, 'TV Special: Heart of Gold', 'https://static.wikia.nocookie.net/onepiece/images/2/27/Jara_Jara_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160724063337', 'allows the user to grow chains from their body, making them a Chain Human (鎖人間 Kusari Ningen).', null, 'Mad Treasure', null, 1),

('Iro Iro no Mi', 'Color-Color Fruit', false, 'TV Special: Heart of Gold', 'https://static.wikia.nocookie.net/onepiece/images/5/50/Iro_Iro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160717172835', 'allows the user to create paint to camouflage or disguise people and objects.', null, 'Psycho P.', null, 1),

('Goru Goru no Mi', 'Gol-Gol Fruit', false, 'Movie 13', 'https://static.wikia.nocookie.net/onepiece/images/d/da/Goru_Goru_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220329091123', 'allows the user to telekinetically manipulate gold at will.', null, 'Gild Tesoro', null, 1),

('Raki Raki no Mi', 'Lucky-Lucky Fruit', false, 'One Piece Film: Gold', 'https://static.wikia.nocookie.net/onepiece/images/6/6f/Raki_Raki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20170107174256', 'allows the user to steal the luck of anyone they touch.', null, 'Baccarat', null, 1),

('Nepa Nepa no Mi', 'Heat-Heat Fruit', false, 'One Piece Premier Show 2016', null, 'allows the user to generate heat waves.', null, 'Wilder', null, 1),

('Mono Mono no Mi', 'Paste-Paste Fruit', false, 'One Piece Premier Show 2016', null, 'allows the user to create clones of people and things.', null, 'Pokke', null, 1),

('Bijo Bijo no Mi', 'Vision-Vision Fruit', false, '["One Piece Live Attraction 3: Phantom", "One Piece: Stampede"]', 'https://static.wikia.nocookie.net/onepiece/images/d/dc/Bijo_Bijo_no_Mi_Infobox.png/revision/latest/scale-to-width-down/334?cb=20191228120335', 'allows the user to ''phantomize'', or create illusory images, of any picture the user touches.', null, 'Ann', null, 1),

('Ute Ute no Mi', 'Gun-Gun Fruit', false, 'One Piece Premier Show 2017', null, 'allows the user to transforms their hands into guns, as well as sprout gun barrels on any nearby surface.', null, 'Bad One Gracie', null, 1), 

('Pocha Pocha no Mi', 'Fat-Fat Fruit', false, 'One Piece Premier Show 2017', null, 'allows the user to add excess fat to an opponent''s body.', null, 'Neiro', null, 1),

('Bana Bana no Mi', null, false, 'One Piece Premier Show 2018', null, 'allows the user to turn their jealousy into heat and flames.', null, 'Bounty', null, 1),

('Deri Deri no Mi', null, false, 'One Piece Premier Show 2018', null, 'allows the user to deliver anything they want to any point they can see.', null, 'Prize', null, 1),

('Dero Dero no Mi', null, false, null, null, 'allows the user to dissolve anything into a liquid, including themselves, by shooting beams out of their eyes.', null, 'Artur Bacca', null, 1),

('Basu Basu no Mi', 'Boom-Boom Fruit', false, 'One Piece Premier Show 2019', null, 'allows the user to turn anything they touch into a bomb.', null, 'Balzac', null, 1),

('Gasha Gasha no Mi', 'Clank-Clank Fruit', false, 'One Piece: Stampede', 'https://static.wikia.nocookie.net/onepiece/images/a/a6/Gasha_Gasha_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20191228120343', 'allow the user to telekinetically disassemble objects and reassemble them into whatever they please, making them an Assimilation Human.', null, 'Douglas Bullet', null, 1),

('Nibi Nibi no Mi', null, false, 'One Piece Premier Show 2021', null, 'allows the user to reproduce the appearance of the deceased.', null, 'Kardia', null, 1),

('Uta Uta no Mi', null, false,'One Piece Film: Red', 'https://static.wikia.nocookie.net/onepiece/images/4/40/Uta_Uta_no_Mi_Infobox.png/revision/latest?cb=20220807193822', 'allows the user to transport people''s consciousnesses into a virtual space by singing', null, 'Uta', null, 1),

('Hito Hito no Mi, Model: Nika', 'Human-Human Fruit, Model: Nika', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/12/Gomu_Gomu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20190419140206', 'after achieving an Awakening, the fruit''s true power as a Mythical Zoan is unleashed, giving the user a new transformation where their hair and clothes turn white, their eyes glow red with white ring-like pupils, and white clouds float around their neck, giving them the appearance of the mythical Sun God, Nika[6], granting their already rubbery body more  strength and freedom, turning the user into a ''Warrior of Liberation'' (解放の戦士 Kaihō no Senshi).', true, 'Monkey D. Luffy', null, 4),

('Ushi Ushi no Mi, Model: Bison', 'Ox Ox Fruit, Model: Bison', true, null, 'https://static.wikia.nocookie.net/onepiece/images/b/bf/Ushi_Ushi_no_Mi%2C_Model_Bison_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220408131623', 'allows the user to transform into a full bison or a half-bison hybrid at will.', null, 'Dalton', null, 2),

('Hito Hito no Mi', 'Human-Human Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/38/Hito_Hito_no_Mi_Infobox.png/revision/latest/scale-to-width-down/317?cb=20191228120250', 'allows its user to transform into a human hybrid or a human at will.', null, 'Tony Tony Chopper', null, 2),

('Ushi Ushi no Mi, Model: Giraffe', 'Ox-Ox Fruit, Model: Giraffe', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/8c/Ushi_Ushi_no_Mi%2C_Model_Giraffe_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141206185849', 'allows its user to transform into a giraffe hybrid and a full giraffe at will, making the user a Giraffe Human.', null, 'Kaku', null, 2),

('Sara Sara no Mi, Model: Axolotl', 'Sala-Sala Frui, Model: Axolotl', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/db/Sara_Sara_no_Mi%2C_Model_Axolotl_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130630175803', 'allows the user to turn into an axolotl hybrid and a full axolotl at will.', null, null, 'Caesar Clown''s poisonous gas: Smiley', 2),

('Uo Uo no Mi, Model: Seiryu', 'Fish-Fish Fruit, Model Azure Dragon', true, null, 'https://static.wikia.nocookie.net/onepiece/images/f/f9/Uo_Uo_no_Mi%2C_Model_Seiryu_Infobox.png/revision/latest/scale-to-width-down/294?cb=20211204205430', 'allows the user to turn into a giant, serpentine, blue-scaled dragon—specifically a category of Eastern dragon called the ''Azure Dragon''—and into a human-dragon hybrid. Apart from scales, acquired dragon features include horns, sharp fangs, and limbs with clawed hands and feet.', null, 'Kaidou', null, 4),

('Hebi Hebi no Mi, Model: Yamata no Orochi', 'Snake-Snake Fruit, Model: Yamata-no-Orochi', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/3e/Hebi_Hebi_no_Mi%2C_Model_Yamata_no_Orochi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210307032049', 'allows the user to transform into a hybrid and full version of the Yamata no Orochi, an eight-headed snake or dragon in Japanese mythology.', null, null, 'Kurozumi Orochi', 4),

('Hebi Hebi no Mi, Model: Anaconda', 'Snake-Snake Fruit, Model: Anaconda', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/3c/Hebi_Hebi_no_Mi%2C_Model_Anaconda_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210908193532', 'allows its user to transform into an anaconda hybrid and a full anaconda at will.', null, 'Boa Sandersonia', null, 2),

('Hebi Hebi no Mi, Model: King Cobra', 'Snake-Snake Fruit, Model: King Cobra', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/33/Hebi_Hebi_no_Mi%2C_Model_King_Cobra_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220408224556', 'allows its user to turn into a king cobra hybrid and a full king cobra at will. It can also give the user the ability to create and spit venom.', null, 'Boa Marigold', null, 2),

('Mushi Mushi no Mi, Model: Kabutomushi', 'Bug-Bug Fruit, Model: Rhinoceros beetle', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/ce/Mushi_Mushi_no_Mi%2C_Model_Kabutomushi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141006011335', 'allows its user to transform into a rhinoceros beetle hybrid and full rhinoceros beetle at will.', null, 'Kabu', null, 2),

('Mushi Mushi no Mi, Model: Suzumebachi', 'Bug-Bug Fruit, Model: Hornet', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d4/Mushi_Mushi_no_Mi%2C_Model_Suzumebachi_Infobox.png/revision/latest?cb=20140609062408', 'allows its user to transform into a hornet hybrid and full hornet at will.', null, 'Bian', null, 2),

('Inu Inu no Mi, Model: Okuchi no Makami', 'Dog-Dog Fruit, Model: Okuchi-no-Makami', true, null, 'https://static.wikia.nocookie.net/onepiece/images/1/1d/Inu_Inu_no_Mi%2C_Model_Okuchi_no_Makami_Infobox.png/revision/latest/scale-to-width-down/350?cb=20211204204735', 'allows the user to transform into a hybrid and full version of an ancient wolf deity at will.', null, 'Yamato', null, 4),

('Artificial Devil Fruit', 'Man-Made Devil Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/6/64/Artificial_Devil_Fruit_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141206075745', 'manmade fruits designed to give consumers special powers like a natural Devil Fruit would. The creation of artificial Devil Fruits is known to have been attempted twice. One such fruit was made by the great scientist Vegapunk but was deemed a failure; it was later consumed by Kozuki Momonosuke and granted him the ability to transform into a dragon.', null, 'Kozuki Momonosuke', null, 6),

('SMILE', 'SMILE', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e5/SMILE_Infobox.png/revision/latest/scale-to-width-down/350?cb=20141206075836', 'are artificial Zoan Devil Fruits created with SAD. They were formerly manufactured by Donquixote Doflamingo and Caesar Clown and were monopolized and consumed by the members of the Beasts Pirates. SMILEs do not have individual names like the standard Devil Fruits, and are instead referred to as ''<Animal species> no SMILE''.', null, 'Gifters', null, 6),

('Batto Batto no Mi, Model: Vampire', 'Bat-Bat Fruit, Model: Vampire', false, 'One Piece: Unlimited World Red', 'https://static.wikia.nocookie.net/onepiece/images/5/57/Batto_Batto_no_Mi%2C_Model_Vampire_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220329093540', 'gives the user the ability to turn into a vampire.', null, 'Patrick Redfield', null, 4),

('Tori Tori no Mi, Model: Nue', 'Bird-Bird Fruit, Model: Nue', false, 'One Piece Art NUE', 'https://static.wikia.nocookie.net/onepiece/images/f/f9/Tori_Tori_no_Mi%2C_Model_Nue_Infobox.png/revision/latest/scale-to-width-down/350?cb=20171001124834', 'allows its user to transform into a nue hybrid and a full nue at will.', null, 'Toratsugu', null, 4),

('Tori Tori no Mi, Model: Phoenix', 'Bird-Bird Fruit, Model: Phoenix', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/51/Tori_Tori_no_Mi%2C_Model_Phoenix_Infobox.png/revision/latest/scale-to-width-down/1000?cb=20211210062841', 'allows the user to transform into a phoneix and phoenix hybrid at will.', null, 'Marco', null, 4),

('Tori Tori no Mi, Model: Falcon', 'Bird-Bird Fruit, Model: Falcon', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/ea/Tori_Tori_no_Mi%2C_Model_Falcon_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20150514123230', 'allows its user to transform into a falcon hybrid and a full falcon at will.', null, 'Pell', null, 2),

('Tori Tori no Mi, Model: Albatross', 'Bird-Bird Fruit, Model: Albatross', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/87/Morgans_Anime_Infobox.png/revision/latest/scale-to-width-down/238?cb=20180401081646', 'allows its user to transform into an albatross hybrid and a full albatross at will.', null, 'Morgans', null, 2),

('The Tori Tori no Mi, Model: Eagle', 'Bird-Bird Fruit, Model: Eagle', false, 'One Piece 3D: Straw Hat Chase', 'https://static.wikia.nocookie.net/onepiece/images/d/df/Tori_Tori_no_Mi%2C_Model_Eagle_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130628213413', 'allows its user to transform into an eagle hybrid and a full eagle at will.', null, 'Buzz', null, 2),

('Inu Inu no Mi, Model: Bake-danuki', 'Dog-Dog Fruit, Model: Bake-danuki', false, 'One Piece: Unlimited World Red', 'https://static.wikia.nocookie.net/onepiece/images/0/05/Inu_Inu_no_Mi%2C_Model_Bake-danuki_Infobox.png/revision/latest?cb=20130929013736', 'gives the user the specific traits of the mythical raccoon dog in which it can transform ordinary leaves into anything else, from objects to other people and entire environments.', null, 'Patrick Redfield''s pen: Pato', null, 4),

('Inu Inu no Mi, Model: Jackal', 'Dog-Dog Fruit, Model: Jackal', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/4f/Inu_Inu_no_Mi%2C_Model_Jackal_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130919152838', 'enables the eater to become a large, black jackal at will, granting an increase in physical strength, speed, and senses.', null, 'Chaka', null, 2),

('Inu Inu no Mi, Model: Dachshund', 'Mutt-Mutt Fruit, Model: Dachshund', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d0/Inu_Inu_no_Mi%2C_Model_Dachshund_Infobox.png/revision/latest/scale-to-width-down/350?cb=20200625092631', 'allows its user to transform into a dachshund hybrid and a full dachshund at will.', null, 'Mr.4''s bazooka, Lassoo', null, 2),

('Inu Inu no Mi, Model: Wolf', 'Mutt-Mutt Fruit, Model: Wolf', true, null, 'https://static.wikia.nocookie.net/onepiece/images/e/e1/Full-Beast_Form_of_Jabra%27s_fruit.png/revision/latest?cb=20211029235543', 'user gains more physical strength in their hybrid and full wolf forms, equivalent to that of a real wolf and more.', null, 'Jabra', null, 2), 

('Inu Inu no Mi, Model: Tanuki', 'Dog-Dog Fruit, Model: Tanuki', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/33/Bunbuku_Manga_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210405204206', 'allows its user to transform into a tanuki hybrid and a full tanuki at will.', null, 'Kozuki Sukiyaki''s teapot, Bunbuku', null, 2),

('Inu Inu no Mi, Model: Kyubi no Kitsune', 'Dog-Dog Fruit, Model: Nine Tailed Fox', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/4d/Inu_Inu_no_Mi%2C_Model_Kyubi_no_Kitsune_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210717170215', 'allows the user to transform into a nine-tailed fox.', null, 'Catarina Devon', null, 4),

('Ryu Ryu no Mi, Model: Allosaurus', 'Dragon-Dragon Fruit. Model: Allosaurus', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/a3/Ryu_Ryu_no_Mi%2C_Model_Allosaurus_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220301122130', 'allows the user to transform into an allosaurus, a large and powerful theropod dinosaur from the prehistoric era, as a carnivorous Ancient Zoan the fruit grants them features much better suited for close combat than basic Zoans such as sharp teeth and claws. As is the case with every other Zoan ability, the user can also become a human-animal hybrid at will.', null, 'X Drake', null, 3),

('Ryu Ryu no Mi, Model: Spinosaurus', 'Dragon-Dragon Fruit, Model: Spinosaurus', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/92/Ryu_Ryu_no_Mi%2C_Model_Spinosaurus_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220807021957', 'grants the user the power to turn into a Spinosaurus, a large and powerful, semiaquatic, carnivorous theropod from the prehistoric era (considered to be the largest predatory dinosaur ever), as well as a hybrid between a Spinosaurus and human (or other) at will.', null, 'Page One', null, 3), 

('Ryu Ryu no Mi, Model: Pteranodon', 'Dragon-Dragon Fruit, Model: Pteranodon', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/96/Ryu_Ryu_no_Mi%2C_Model_Pteranodon_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220418123709', 'user of this fruit''s power can turn into a pteranodon: a large, flight-capable, predatory reptile from prehistory. Once transformed, they become able to fly at tremendous speed, covering large distances rapidly, and enjoy a significant boost to their overall physical abilities, as typical for a carnivorous Ancient Zoan user. Additionally, the full Beast Form as displayed by King is notably large, several times bigger than an average-sized human (though it is worth noting that King is already much larger than normal people in his normal form).', null, 'King', null, 3), 

('Ryu Ryu no Mi, Model: Brachiosaurus', 'Dragon-Dragon Fruit, Model: Brachiosaurus', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/40/Ryu_Ryu_no_Mi%2C_Model_Brachiosaurus_Beast_Form.png/revision/latest/scale-to-width-down/292?cb=20201004060008', 'allows the user to turn into a brachiosaurus, a very large and heavy-bodied sauropod dinosaur from the prehistoric era, granting them an immense boost to their size and bulk. Their size is comparable to that of a giant, as a fully-transformed Queen is shown to tower over Big Mom, who herself is extremely tall at over 8 meters.', null, 'Queen', null, 3),

('Ryu Ryu no Mi, Model: Pachycephalosaurus', 'Dragon-Dragon Fruit, Model: Pachycephalosaurus', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/4b/Ryu_Ryu_no_Mi%2C_Model_Pachycephalosaurus_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220227070532', 'fruit''s power is to turn into a full and hybrid version of a pachycephalosaurus: a bipedal, herbivorous dinosaur distinguished by its super-thick, durable skull roof. The Human-Beast Form already grants a significant increase in body size, with Ulti going from an ordinary height to over three times as tall, and her full Beast Form is even bigger, at least as large as her brother''s full spinosaurus form.', null, 'Ulti', null, 3), 

('Ryu Ryu no Mi, Model: Triceratops', 'Dragon-Dragon Fruit, Model: Triceratops', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/58/Ryu_Ryu_no_Mi%2C_Model_Triceratops_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220529042151', 'user of this Zoan can become a triceratops—a large, heavy-bodied, herbivorous dinosaur from prehistory—and assume a human-triceratops hybrid form.', null, 'Sasaki', null, 3),

('Zou Zou no Mi, Model: Mammoth', 'Eleph-Eleph Fruit, Model: Mammoth', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d4/Zou_Zou_no_Mi%2C_Model_Mammoth_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20211212162937', 'allows the user to transform in full or hybrid mammoth at will. The full mammoth form granted by this fruit gives the user a massive frame, significantly increasing Jack''s already abnormal size. As an Ancient Zoan, this fruit grants the user greater strength than a normal Zoan.', null, 'Jack', null, 3),

('Kumo Kumo no Mi, Model: Rosamygale Grauvogeli', 'Spider-Spider Fruit, Model: Rosamygale Grauvogeli', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7c/Kumo_Kumo_no_Mi_Model_Rosamygale_Grauvogeli_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220410040856', 'user of this Zoan can become a Rosamygale grauvogeli—a heavy-bodied, stout-legged mygalomorph spider from prehistoric times—as well as a human-spider hybrid.', null, 'Black Maria', null, 3),

('Neko Neko no Mi, Model: Saber Tiger', 'Cat-Cat Fruit, Model: Saber-Toothed Tiger', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/2a/Neko_Neko_no_Mi%2C_Model_Saber_Tiger_Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220623102748', 'user of this fruit''s power can turn into a ''saber-toothed tiger'' or Smilodon—a powerful, predatory big cat from prehistory that is characterized by its elongated, curved fangs on its upper jaw.', null, 'Who''s-Who', null, 3),

('Neko Neko no Mi, Model: Leopard', 'Cat-Cat Fruit, Model: Leopard', true, null, 'https://static.wikia.nocookie.net/onepiece/images/6/6e/Neko_Neko_no_Mi%2C_Model_Leopard_Human-Beast_Form.png/revision/latest/scale-to-width-down/350?cb=20220410054931', 'allows its user to transform into a leopard hybrid and a full leopard at will, making the user a Leopard Human (ヒョウ人間 Hyō Ningen).', null, 'Rob Lucci', null, 2),

('Hito Hito no Mi, Model: Daibutsu', 'Human-Human Fruit, Model: Buddha', true, null, 'https://static.wikia.nocookie.net/onepiece/images/4/45/Hito_Hito_no_Mi%2C_Model_Daibutsu_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160818203351', 'allows the user to transform into a giant, living, golden Buddha, gaining an extreme boost in strength to match the increased size. In this form, Sengoku''s limbs grow out of proportion, giving him abnormally large arms and relatively tiny legs. His entire body takes on a solid gold hue (gray color in Gigant Battle); in addition to a full and hybrid transformation that are available to all Zoan Devil Fruit users, he can use palm thrusts to launch powerful shock waves.', null, 'Sengoku', null, 4),

('Hito Hito no Mi, Model: Onyudo', 'Human-Human Fruit, Model: Onyudo', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d2/Onimaru_as_Gyukimaru.png/revision/latest/scale-to-width-down/350?cb=20200712035243', 'allows its user to transform into an onyudo, a large monk yokai, at will.', null, 'Onimaru', null, 4),

('Zou Zou no Mi', 'Elephant-Elephant Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/c1/Funkfreed_Anime_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160816232853', 'Funkfreed is Spandam''s sword, a unique weapon that ''ate'' the Zou Zou no Mi and became an Elephant Sword (象剣 Zōken). As such, he also serves as a pet and unofficial bodyguard for Spandam, compensating his master''s physical slightness.', null, 'Spandam''s sword, Funk Freed', null, 2),

('Unnamed Zoan Devil Fruit', 'Unnamed Zoan Devil Fruit', false, null, 'https://static.wikia.nocookie.net/onepiece/images/c/ca/Alpacacino_Anime_Infobox.png/revision/latest/scale-to-width-down/216?cb=20130129060954', 'a bazooka ''ate'' an unnamed Zoan Devil Fruit, allowing him to turn into a white alpaca with a metal band around his neck (a circular ring is attached to this) and his full body. His eyes turn red when he is taking his cannon position. He also has a purple crank on his left side. In his hybrid form, he also shows the handle of a bazooka.', null, 'Shuzo''s bazooka, Alpacacino', null, 2),

('Mogu Mogu no Mi', 'Mole-Mole Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/9/95/Mogu_Mogu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160814224126', 'allows its user to transform into a mole hybrid and a full mole at will, making the user a Mole Human (モグラ人間 Mogura Ningen).', null, 'Drophy aka Miss Merry Christmas', null, 2),

('Uma Uma no Mi', 'Horse-Horse Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/3/39/Uma_Uma_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220713111132', 'allows its user to transform into a horse hybrid and a full horse at will.', null, 'Gan Fall''s bird, Pierre', null, 2),

('Kame Kame no Mi', 'Turtle-Turtle Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/74/Kame_Kame_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160120235204', 'allows the user to become a turtle hybrid and full turtle at will.', null, 'Pekoms', null, 2), 

('Tama Tama no Mi', 'Egg-Egg Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/a9/Tama_Tama_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20171203040745', 'turns the user''s body composition into that of an egg, which if cracked open will cause the user to regenerate into a stronger body that features more and more chicken-like features each time.', null, 'Tamago', null, 2),

('Moku Moku no Mi', 'Plume-Plume Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/8d/Moku_Moku_no_Mi_Infobox.png/revision/latest?cb=20200912191830', 'allows the user of this fruit to generate, manipulate, and become smoke. Like with most other Logia fruits, when hit, the user can simply use the fruit''s power to become smoke, thus absorbing the attack and remaining unharmed. Like some of the other Logia type Devil Fruits, it allows its user to ''fly'', by turning their body or the lower part of it into smoke, greatly enhancing their movement and speed.', null, 'Smoker the White Hunter', null, 5),

('Suna Suna no Mi', 'Sand-Sand Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/7d/Suna_Suna_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220408131752', 'allows the user to generate, control and transform into large quantities of sand. Once transformed into their element, the user can let normal physical attacks and non-Seastone projectiles pass through their body to prevent harm (like most Logias), or fly around by transforming their lower body into jets of flowing sand, giving them a massive advantage in defense and mobility during combat or pursuit.', null, 'Crocodile aka Mr. 0', null, 5),

('Mera Mera no Mi', 'Flame-Flame Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/8/8c/Mera_Mera_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20151123200729', 'allows the user to produce as well as become the element they control. In this case, the user is able to create, control, and become fire. With this in mind, the user can create devastating fire-based attacks and gain a high resistance towards most heat-based attacks. The flames can also be used to increase the force of physical attacks. The user is also able to avoid normal physical attacks by turning into fire and allowing the attack to harmlessly pass through their fiery body. Igniting oneself also has the added effect of burning an opponent if he or she had tried to physically harm the user.', null, 'Sabo','Portgas D. Ace', 5),

('Goro Goro no Mi', 'Rumble-Rumble Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/d/d2/Goro_Goro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20181214005449', 'grants the power to create, control, and transform into lightning at will, making its user a Lightning Human (雷人間 Kaminari Ningen). Even for a Logia, this ability seems outstandingly potent, given the inherent destructiveness of lightning.', null, 'Enel', null, 5),

('Hie Hie no Mi', 'Ice-Ice Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/5/56/Hie_Hie_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20210322034024', 'allows its ability user to transform into the element of ice, as well as create and control it on a potentially massive scale, especially to freeze their surroundings. Particularly potent even by Logia standards.', null, 'Kuzan aka Aokiji', null, 5), 

('Yami Yami no Mi', 'Dark-Dark Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/f/f5/Yami_Yami_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20160123174331', 'allows the user to create, control, and transform into darkness. The darkness has strong gravitational properties and the user has an infinite amount of space inside of their elemental body.', null, 'Marshall D. Teach', null, 5),

('Pika Pika no Mi', 'Glint-Glint Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/6/66/Pika_Pika_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20110903091229', 'allows the user to create, control, and transform into light at will, turning the user into a Light Human (光人間 Hikari Ningen).It enables the user to move at the speed of light and transport themself by means of reflection.', null, 'Borsalino aka Admiral Kizaru', null, 5), 

('Magu Magu no Mi', 'Magma-Magma Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/0/07/Magu_Magu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220507164728', 'allows the user to become and produce magma to attack their opponents with. The intense heat can vaporize an iceberg instantly and boil seawater that the magma lands in.', null, 'Fleet Admiral Sakazuki, formerly known as Admiral Akainu', null, 5),

('Numa Numa no Mi', 'Swamp-Swamp Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/7/76/Caribou_Anime_Infobox.png/revision/latest/scale-to-width-down/350?cb=2014080110520', 'allows the user to create, control, and transform into mud. The user is a ''bottomless swamp'', granting them an infinite amount of space inside their elemental body. The mud can also take on the properties of quicksand.', null, 'Wet-Haired Caribou', null, 5),

('Gasu Gasu no Mi', 'Gas-Gas Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/c/cf/Gasu_Gasu_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20161120000041', 'allows the user to create, manipulate, and transform into gas at will.', null, 'Caesar the Clown', null, 5),

('Yuki Yuki no Mi', 'Snow-Snow Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/a/a9/Yuki_Yuki_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20170805155559', 'allows the user to create, control, and transform into the element of ''snow'' at will, turning the user into a Snow Human (雪人間 Yuki Ningen).', null, null, 'Monet', 5),

('Mori Mori no Mi', 'Woods-Woods Fruit', true, null, 'https://static.wikia.nocookie.net/onepiece/images/2/23/Mori_Mori_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20220801065220', 'allows the user to create, control, and transform into plant life at will, making the user a Forest Human (森人間 Mori Ningen).', null, 'Aramaki aka Admiral Ryokugyu', null, 5),

('Toro Toro no Mi', null, false, 'One Piece: Clockwork Island Adventure', 'https://static.wikia.nocookie.net/onepiece/images/7/71/Toro_Toro_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20130623120640', 'allows the user to create, control, and transform into an unidentified liquid at will.', null, 'Honey Queen', null, 5),

('Ame Ame no Mi', 'Candy-Candy Fruit', false, 'One Piece The Movie: Dead End Adventure', 'https://static.wikia.nocookie.net/onepiece/images/b/be/Ame_Ame_no_Mi_Infobox.png/revision/latest/scale-to-width-down/350?cb=20121001043257', 'allows the user to create, control, and transform into candy syrup.', null, 'Gasparde', null, 5);
