module.exports = [{
    'civilians' : [
        {
            name: "Boodle",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/c/c0/Boodle_Anime_Pre_Timeskip_Infobox.png/revision/latest?cb=20130622181253", "https://static.wikia.nocookie.net/onepiece/images/a/a8/Boodle_Digitally_Colored_Manga.png/revision/latest?cb=20211116025446"],
            origin: "Orange Town",
            birthdate: "January 16th",
            bounty: null,
            devilfruit: null, 
            haki_user: null,
            alive: true,
            position: "Mayor",
            crew: null,
            allies: "Straw Hat Pirates",
        },
        {
            name: "Chicken",
            profile_pic: "" / [""],
            origin: "Foosha Village",
            birthdate: "February 8th",
            bounty: null,
            devilfruit: null, 
            haki_user: null,
            alive: "",
            position: "",
            crew: null,
            allies: "Staw Hat Pirates",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
    ],
    'pirates' : [
        {
            name: "'Iron Mace' Alvida",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/9/95/Alvida_Portrait.png/revision/latest?cb=20220101044820", "https://static.wikia.nocookie.net/onepiece/images/8/8c/Alvida_Digitaly_Colored_Manga.png/revision/latest?cb=20131001094837", "https://static.wikia.nocookie.net/onepiece/images/9/99/Alvida_Sube_Sube_no_Mi_Digitally_Colored_Manga.png/revision/latest?cb=20211015001814"],
            origin: "East Blue",
            birthdate: "March 14th",
            bounty: 5000000,
            devilfruit: "Sube Sube no Mi", 
            haki_user: false,
            alive: true,
            position: "Former Captain",
            crew: "Alvida Pirates",
            allies: "Buggy Pirates",
        },
        {
            name: "Benn Beckman",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/2/2b/Benn_Beckman_Manga_Color_Scheme.png/revision/latest?cb=20211108010819", "https://static.wikia.nocookie.net/onepiece/images/d/d8/Beckman_Digitally_Colored_Manga.png/revision/latest?cb=20211026040042"],
            origin: "North Blue",
            birthdate: "November 9th",
            bounty: "unknown",
            devilfruit: null, 
            haki_user: ["Busoshoku Haki", "Kenbunshoku Haki"],
            alive: true,
            position: "First Mate",
            crew: "Red Hair Pirates",
            allies: null,
        },
        {
            name: "Bonk Punch",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/3/39/Punch_Episode_of_Luffy.png/revision/latest/scale-to-width-down/1000?cb=20211203021603", "https://static.wikia.nocookie.net/onepiece/images/f/f4/Bonk_Punch_Marineford.png/revision/latest?cb=20211230173406"],
            origin: null,
            birthdate: "March 14th",
            bounty: null,
            devilfruit: null, 
            haki_user: null,
            alive: true,
            position: ["Musician", "Officer"],
            crew: "Red Hair Pirates",
            allies: null,
        },
        {
            name: "Buggy the Clown ",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/8/82/Buggy_Manga_Color_Scheme.png/revision/latest?cb=20211212051802", "https://static.wikia.nocookie.net/onepiece/images/1/12/Buggy%27s_Full_Appearance.png/revision/latest/scale-to-width-down/1000?cb=20211212051855"],
            origin: "Grand Line",
            birthdate: "August 8th",
            bounty: null,
            devilfruit: "Bara Bara no Mi",
            haki_user: null, 
            alive: true,
            position: ["Captain", "Warlord of the Sea", "Yonkō"],
            crew: "Buggy Pirates",
            allies: "Alvida",
        },
        {
            name: "Cabaji the Acrobat",
            profile_pic: ["https://static.wikia.nocookie.net/onepiece/images/b/ba/Cabaji_Manga_Color_Scheme.png/revision/latest?cb=20181030094823", "https://static.wikia.nocookie.net/onepiece/images/0/0f/Cabaji_Digital_Colored_Manga.png/revision/latest/scale-to-width-down/1000?cb=20211113014618"],
            origin: "East Blue",
            birthdate: "September 8th",
            bounty: null,
            devilfruit: null, 
            haki_user: null,
            alive: true,
            position: "Chief of Staff",
            crew: "Buggy Pirates",
            allies: "Alvida",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "",
            haki_user: "" / [""], 
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "",
            haki_user: "" / [""], 
            alive: "",
            position: "",
            crew: "",
            allies: "",
        },
    ],
    'navy' : [
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "", 
            haki_user: "" / [""],
            alive: "",
            position: "",
            allies: "",
        },
        {
            name: "",
            profile_pic: "" / [""],
            origin: "",
            birthdate: "March 14th",
            bounty: null,
            devilfruit: "",
            haki_user: "" / [""], 
            alive: "",
            position: "",
            allies: "",
        },
    ]
}]